{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchossimulatorarm64-0.8.1.klib",
          "size": 4307,
          "sha512": "353c4900b89403ab48e9eb8bb8de7bb7b0f14f79f96bd45db26c72cf3090c72e5b6f6093cc9e0bd28e9ed4a2dbef76b6694373f34300f31bba0cc0ce2825907b",
          "sha256": "c04a8dcf2e58549aa860fffb3ff1c1ceb75ce7ff6864b6a92587d7d91ee9dcec",
          "sha1": "545cb2073b6ff3f0a721ba8e3cc1be8fe159bd70",
          "md5": "8b38aa44c80e8a3f6953c5b8a93205b5"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-watchossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "92359bebf03c8fd943f7fbd449e1ea294391d9bc4f0e89bbd3695f3179428f3e8e6d65e804baaa51a7f1bfe013aa2e7701fa653aba760819fb5b3de25a1b1622",
          "sha256": "b9a5a0d6d6a4e56e32aa4c1c356450df165c22d6eac2798590220be35f6e9099",
          "sha1": "ee5c7371b0afe25be478492283cdbc48b97e07e2",
          "md5": "5337fa770794ec2df029dfd2a0606cca"
        }
      ]
    }
  ]
}
