{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvossimulatorarm64-0.8.1.klib",
          "size": 4283,
          "sha512": "5800930c937abcccfc8e9eee9689f23fa6ef64426064d6bb5f84f57fc97c50cdf9575497d92a556645be5be7ee505921a4f9ef87a7dc1e8f80c5b3e18c50db9a",
          "sha256": "6427eee41c9f890012edafa1cb3854b4c0264783a6ddc8a3ed40b95ae2ae8cdd",
          "sha1": "b0d71d41763b038710bf3c41fc88036f4e0585e6",
          "md5": "0b233a6174fb6df0046db85e398c0c0d"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-tvossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "e8b346b31b24f98bd0c473d22d792a4b64f5a4ff958319df46a694ba0a7d0c5ea1da117edea0e160b433d7ffd8b742d6bd018528704be601c109d61d6a80fe75",
          "sha256": "e7c00aa036dd042891a9fd39ad587d0de3f893b1d7cd83fc3f2f1a1e75db34bf",
          "sha1": "12a68f3270763ea7d69c7be9050b077083cc2e1e",
          "md5": "7fac7dfe750638b190f1438a791e0526"
        }
      ]
    }
  ]
}
