{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.3-SNAPSHOT/lib-0.0.3-SNAPSHOT.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.0.3-SNAPSHOT.klib",
          "url": "lib-js-0.0.3-SNAPSHOT.klib",
          "size": 14174,
          "sha512": "653faa9d08579e2c43e38953e0a794e43fbf525cd8936ea53816d85ca6864ae95e9087a68704c778c053d39797a151bb293f75f2b843eeed0699c2521954e17b",
          "sha256": "a26fa6781bc9f4d214700024fa2ac8c4e77df6fe64202f1184004e3c2552f058",
          "sha1": "038c5476124e4309eb5ac47ca5d545b4acb3a868",
          "md5": "fd919100c7f221226be4c35a3e423da2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.0.3-SNAPSHOT.klib",
          "url": "lib-js-0.0.3-SNAPSHOT.klib",
          "size": 14174,
          "sha512": "653faa9d08579e2c43e38953e0a794e43fbf525cd8936ea53816d85ca6864ae95e9087a68704c778c053d39797a151bb293f75f2b843eeed0699c2521954e17b",
          "sha256": "a26fa6781bc9f4d214700024fa2ac8c4e77df6fe64202f1184004e3c2552f058",
          "sha1": "038c5476124e4309eb5ac47ca5d545b4acb3a868",
          "md5": "fd919100c7f221226be4c35a3e423da2"
        }
      ]
    }
  ]
}
