{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.4.2.klib",
          "size": 14828,
          "sha512": "9016da0813647e16626a6345971e9258c183545337cfba3316bb177f4138143be07efdfc7e6a660b5948ad2ccf672d64f668782a4b93b9711349951fe0e60a94",
          "sha256": "aca4b2fe272b60c0393c9c70d10cdac7f2cc3f624717d7bf8a28002328a20b06",
          "sha1": "44d3b9f2824749c12b8dae9c269859e54afe2126",
          "md5": "ab73e89c9809754a876c19207111964b"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.4.2-metadata.jar",
          "url": "lib-watchosarm32-0.4.2-metadata.jar",
          "size": 4128,
          "sha512": "43e236e36efd3728155db53f86f5aacb6bab778519220647e0c6f382c58099d19f6b82c79edc36933909ade610dce889da06576d0881e4103b6d1b6d509ff3a3",
          "sha256": "7671e6bbbd23e00a48bbbce2aef723837df67def779537bad22648b241bef8ef",
          "sha1": "85bfca18d9be46d8fa3188318de9ed0ae65f437a",
          "md5": "57c17462026952a9bb2e4c91540cca2b"
        }
      ]
    }
  ]
}
