{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.0/lib-coroutines-0.8.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosx64-0.8.0.klib",
          "size": 4178,
          "sha512": "02eff66d166c6255bf14d8ff740ad77927d4b9e1a42b6aeeac781d91d4ea2e33a87d7a70303c7003792ccbabb021d1e74798dc48e4f3b8bbc1aa2166b5bc48ec",
          "sha256": "f3b55746d3164ba3044e9b7cc572dbae5288f21eaf2eb72922959c43b43a7f93",
          "sha1": "dfa0061e1d4d3fbe704c622f567d99cae7fe1b90",
          "md5": "237577f5296b36576ab256595ea26cd2"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosx64-0.8.0-metadata.jar",
          "url": "lib-coroutines-tvosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "0aaf90042930543dd626c575aa02192aba5e61dc99459caade75285f1643d5660ad8879f18ddc6c1021fedbd03ea5f963365d766e8202c174b984fa76af624d2",
          "sha256": "d10da0278fca951144f15d8144282ce145bf573aa04115a421b0145291f48faf",
          "sha1": "034be7c0ffe502c8607b2fcb47a98acbd175d158",
          "md5": "5456601857a2f07ff8899cbfa3b896df"
        }
      ]
    }
  ]
}
