{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-metadata-0.4.0-all.jar",
          "url": "lib-coroutines-0.4.0-all.jar",
          "size": 2121,
          "sha512": "a095df660d336df78bea9d38e9059117d469e24babcb099060cd953fdd56e9c95fc9503c624037851c4247ba44cb6bb4af64168141759e1247067eef36611c92",
          "sha256": "107667753eb7e1f918cc8e4862a7893d50b264abd6636d97a2affd715e193697",
          "sha1": "fa11503d6017cc9f9b4c3ff977f2fa12df785210",
          "md5": "423ea82e92eee1eb9e94a70a327a16d2"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-0.4.0.jar",
          "url": "lib-coroutines-0.4.0.jar",
          "size": 679,
          "sha512": "24995132ab1ae3ea7695bbd1abe86603c3759f25104b7f1c324f2206832d498cd1d4f7332afd932482f6dd489ad4de03a4b6a8fb2944512b6b69bc14733b0ae2",
          "sha256": "1345356886f5913aa3edee9c60e55557de9950fde4abd01381d2d65a984d8a4d",
          "sha1": "35f22816d1b93a74252cd78d7c22356020e7d0f8",
          "md5": "852caa0540ba201aff7d0c1fe4f6fb23"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosarm64/0.4.0/lib-coroutines-iosarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosarm64/0.4.0/lib-coroutines-iosarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iossimulatorarm64/0.4.0/lib-coroutines-iossimulatorarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iossimulatorarm64/0.4.0/lib-coroutines-iossimulatorarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosx64/0.4.0/lib-coroutines-iosx64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosx64/0.4.0/lib-coroutines-iosx64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-coroutines-js/0.4.0/lib-coroutines-js-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-coroutines-js/0.4.0/lib-coroutines-js-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-coroutines-jvm/0.4.0/lib-coroutines-jvm-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-coroutines-jvm/0.4.0/lib-coroutines-jvm-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosarm64/0.4.0/lib-coroutines-tvosarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosarm64/0.4.0/lib-coroutines-tvosarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosx64/0.4.0/lib-coroutines-tvosx64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosx64/0.4.0/lib-coroutines-tvosx64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm32/0.4.0/lib-coroutines-watchosarm32-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm32",
        "version": "0.4.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm32/0.4.0/lib-coroutines-watchosarm32-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm32",
        "version": "0.4.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm64/0.4.0/lib-coroutines-watchosarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm64/0.4.0/lib-coroutines-watchosarm64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosx64/0.4.0/lib-coroutines-watchosx64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosx64/0.4.0/lib-coroutines-watchosx64-0.4.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosx64",
        "version": "0.4.0"
      }
    }
  ]
}
