{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.3.1/lib-coroutines-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-js-0.3.1.klib",
          "url": "lib-coroutines-js-0.3.1.klib",
          "size": 4490,
          "sha512": "a5bd391d3801a6f6f9dae82104499e9539229a95bc05ac668627cd11eeddaee6a89f1b28584baf4304ca0c7eac843fb486a600907bd7202846d95a1decb09721",
          "sha256": "e6940786477ea72dec492902676890a597e02bd10e067b773f896a614c87a268",
          "sha1": "76054861255641ab1da8f01f89c731948cb7e83f",
          "md5": "beef10196cefd91e9266fcbc124b5377"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-js-0.3.1.klib",
          "url": "lib-coroutines-js-0.3.1.klib",
          "size": 4490,
          "sha512": "a5bd391d3801a6f6f9dae82104499e9539229a95bc05ac668627cd11eeddaee6a89f1b28584baf4304ca0c7eac843fb486a600907bd7202846d95a1decb09721",
          "sha256": "e6940786477ea72dec492902676890a597e02bd10e067b773f896a614c87a268",
          "sha1": "76054861255641ab1da8f01f89c731948cb7e83f",
          "md5": "beef10196cefd91e9266fcbc124b5377"
        }
      ]
    }
  ]
}
