{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.0/lib-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.6.0.klib",
          "size": 8131,
          "sha512": "18f0929f0e5456b0fe7483c50bba6af2cd7bbf4ec8e04bc04414a013cb87b50dc7484f2fa0338ffccb66d5952fe24631208ba175697eb2a1000e6343ff61df48",
          "sha256": "64266ddf066a14766f24032b242e4ddfd6555561e12c4385d7de22b0b68bc3b4",
          "sha1": "a43c99463c47267fa259a33dc03bf8ea8e398194",
          "md5": "ad50786e0838db01c1029f2e834cb613"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.6.0-metadata.jar",
          "url": "lib-tvosx64-0.6.0-metadata.jar",
          "size": 3969,
          "sha512": "e8cecfde714c78ebffa2dbc4418716a3a4f8e3e743c9e51e69a73a692c0019e8d9878076aeeb8294db9833fd3b1cf44f44202bdfdd90e1f1182629426c099ae1",
          "sha256": "22cdeb619e46e472d87139d3babd406d253f2a22aa0289ddf009dd6f25259e82",
          "sha1": "6f396479548d982932bfbaaa6a0f2549b6635012",
          "md5": "03794661e0fc3224aff046e4c55ccc47"
        }
      ]
    }
  ]
}
