{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.2.jar",
          "url": "compiler-0.8.2.jar",
          "size": 224351,
          "sha512": "de67da0c85ea3e25e8277f25e24d4c5d18144f13662981d5029c5fab59ae8f301ab40481394de6ff2a971cbf892e34fe62bd764959f7434f6b6281d467d43d0b",
          "sha256": "35289dbf4aa144598fae1c9d10b45319aefdc89787220d2607e9bb25db9210f3",
          "sha1": "c2a3cb80a9ad62dac9b97de1a772ab3728587e02",
          "md5": "85210bcab8be62650b25573109e5d04c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.2.jar",
          "url": "compiler-0.8.2.jar",
          "size": 224351,
          "sha512": "de67da0c85ea3e25e8277f25e24d4c5d18144f13662981d5029c5fab59ae8f301ab40481394de6ff2a971cbf892e34fe62bd764959f7434f6b6281d467d43d0b",
          "sha256": "35289dbf4aa144598fae1c9d10b45319aefdc89787220d2607e9bb25db9210f3",
          "sha1": "c2a3cb80a9ad62dac9b97de1a772ab3728587e02",
          "md5": "85210bcab8be62650b25573109e5d04c"
        }
      ]
    }
  ]
}
