{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.8.1.klib",
          "size": 6846,
          "sha512": "c7e64074f84ff95b3f9fcc3f20f790551cc44ca495c7145ab52d42351cdcec9b87a4f8aaf2b56a9b602c4a647aa18618fe0399a4ce5cde8a7b92511360f8d75a",
          "sha256": "5a4e358e10cac21e637811b6e5f110604eaea9aef072036516989319c7ca39b0",
          "sha1": "886f4f7a540dff5e35b413b2da7030bae2579590",
          "md5": "c1cd509c8c22a2bec7a7658583f9ac42"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.8.1-metadata.jar",
          "url": "lib-watchosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "53e8a31b3ff0f5f46e8c8344a049eb539778e30c0c5af81c4c0be2510d5f9f76a05168cc52c459c0234b6c2b6c5b5b7a32c87acf383d639ca74c1ad1a3e977f7",
          "sha256": "103ae64747c74b94a1ce293d7bc1ce6bc60fc50d3eae9a2d5ca35435985e4840",
          "sha1": "6f1b941bef52bd0cdd709ebe4ec43c97814c641c",
          "md5": "cff1e0328352612266636e8540f9ee6e"
        }
      ]
    }
  ]
}
