{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.8.1.klib",
          "size": 6853,
          "sha512": "f7cd88a32676db6197e42cb04221837433a55e6dc08f1d4d2c74f7f59a7dea7b0c68c6dbdf6c712152b19ecd3ac88ae1eaa428efa962c3d2d3daef290f495849",
          "sha256": "a52c23af0464aaf8c56466afb1b845a884cc40c70e5c8472b80279753d4cc76e",
          "sha1": "803110bfcc5ea3d01a775c90bc8136df15d8736d",
          "md5": "dfccc7cab05b4de2f96ac9e701f3e612"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.8.1-metadata.jar",
          "url": "lib-watchosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "fe70f3c8db9bc51c22fcab6243482dc29da6db05402d9da731a33da826a0914a73bac615305f1af8bfe91f54d8ecc0a89522e9b3dc810c5eb4cde49b4c9b3f0f",
          "sha256": "4fe8900a6807cfe2230fab152512676beb10199711f51f59283cf4b883045019",
          "sha1": "f992ab00f3736fdc639151152987376f06db02f0",
          "md5": "0736b015150172c5e5f8aa00454b9f7a"
        }
      ]
    }
  ]
}
