{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.0/lib-0.8.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.8.0.klib",
          "url": "lib-js-0.8.0.klib",
          "size": 5891,
          "sha512": "10860131020ba0e2199aa58b1006e7337e70e08b6c36851aae8c5217989e1c076ba2a3de106af49587240f69a7d83e2cb6bd7fbe88c166b401b463cf1046ca2d",
          "sha256": "6a4fcc53578df2a8925bad36a2845165e0d631ee204f0b5814293b5f4afde3b1",
          "sha1": "0fb0d826452af5620d37feb1f37b60c9dd82fff1",
          "md5": "0631f5e837d573e0d75d1b001f8302d4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.8.0.klib",
          "url": "lib-js-0.8.0.klib",
          "size": 5891,
          "sha512": "10860131020ba0e2199aa58b1006e7337e70e08b6c36851aae8c5217989e1c076ba2a3de106af49587240f69a7d83e2cb6bd7fbe88c166b401b463cf1046ca2d",
          "sha256": "6a4fcc53578df2a8925bad36a2845165e0d631ee204f0b5814293b5f4afde3b1",
          "sha1": "0fb0d826452af5620d37feb1f37b60c9dd82fff1",
          "md5": "0631f5e837d573e0d75d1b001f8302d4"
        }
      ]
    }
  ]
}
