{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.8.1.klib",
          "size": 6820,
          "sha512": "19a6906390e1132fb7b2cb40abeffc57d2d2a2c0adcbb78fcc3824a25272c223c85eb5bf0975e916d457d98e04da2be907af13f2b90a5591baff6ad1423f628d",
          "sha256": "8324fe9a721b044225dd447301506a8ba0dd30c17b52050fb22f046f13577d70",
          "sha1": "8fd702a68956b44c174c5412f168176f7bb09225",
          "md5": "7ee57b26e14cb6f156e3ff1cd00bc4ac"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.8.1-metadata.jar",
          "url": "lib-tvosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "4acf53c6e89d9a3af9752f054e22e9941c6fb49e89be68595bef5dfdadc891ad4952e532c3f21a2929139d89002f5f283fbc194da90dded6609caf9cca76eb96",
          "sha256": "da52af3ac8dcec6411270ddf3ec15dcd4a4a95aa496aeceb7331259500ebbcf1",
          "sha1": "e65669310b4e8df77a61cd422f27cd532c694da0",
          "md5": "625829f4079b497dd5f04d7b782c71f7"
        }
      ]
    }
  ]
}
