{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-0.8.1.jar",
          "url": "lib-0.8.1.jar",
          "size": 3363,
          "sha512": "94783b7491c27e19d8cc5f65e1c2b36f8ab8930cd22a8742d32ff65da9091768ed76671db4fe5065f9131f367b4899755ba484f1a88bc103cbdecf5576c7666f",
          "sha256": "d72eb986a829915c9da87a8231c38d32b1d4a85cadac13a9643bf106387bfe43",
          "sha1": "4c8f05867e9072b4c161d2d16a1f7c9afc499bcc",
          "md5": "fcb592892c3ace306d3c6ba1427e594a"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.8.1/lib-iosarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.8.1/lib-iosarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.8.1/lib-iossimulatorarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.8.1/lib-iossimulatorarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.8.1/lib-iosx64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.8.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.8.1/lib-iosx64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.8.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.8.1/lib-js-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.8.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.8.1/lib-js-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.8.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.8.1/lib-jvm-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.8.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.8.1/lib-jvm-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.8.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.8.1/lib-tvosarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.8.1/lib-tvosarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvossimulatorarm64/0.8.1/lib-tvossimulatorarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvossimulatorarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvossimulatorarm64/0.8.1/lib-tvossimulatorarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvossimulatorarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.8.1/lib-tvosx64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.8.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.8.1/lib-tvosx64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.8.1/lib-watchosarm32-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.8.1/lib-watchosarm32-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.8.1/lib-watchosarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.8.1/lib-watchosarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchossimulatorarm64/0.8.1/lib-watchossimulatorarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchossimulatorarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchossimulatorarm64/0.8.1/lib-watchossimulatorarm64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchossimulatorarm64",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.8.1/lib-watchosx64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.8.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.8.1/lib-watchosx64-0.8.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.8.1"
      }
    }
  ]
}
