{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.4.1.jar",
          "url": "lib-jvm-0.4.1.jar",
          "size": 20631,
          "sha512": "3d19e36262247290365bb2b922a0bb4248ae92fb81e4fa11a2c0df3cce36c776bf6fb95ea164ee8c741216b60bfc4fe6624b3a23c3ca7801eff7c0f713e5b779",
          "sha256": "dac060e4cbe08cfc4bce80758ee5f35195fa459a60211ffbc2be680162416c31",
          "sha1": "23dce5aaa07578b3861ef65ef5d213da62b57f97",
          "md5": "e758b8f5817b3dc23218ed4abb2bf3b6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.4.1.jar",
          "url": "lib-jvm-0.4.1.jar",
          "size": 20631,
          "sha512": "3d19e36262247290365bb2b922a0bb4248ae92fb81e4fa11a2c0df3cce36c776bf6fb95ea164ee8c741216b60bfc4fe6624b3a23c3ca7801eff7c0f713e5b779",
          "sha256": "dac060e4cbe08cfc4bce80758ee5f35195fa459a60211ffbc2be680162416c31",
          "sha1": "23dce5aaa07578b3861ef65ef5d213da62b57f97",
          "md5": "e758b8f5817b3dc23218ed4abb2bf3b6"
        }
      ]
    }
  ]
}
