{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.8.1.klib",
          "size": 6853,
          "sha512": "d9a0d01a811b448e19ed2ec85faad547444eed390ffe71fbf044a00318337e9d40276668b6e979bbb8a41e4a2c3ea582e50da8f5a39f1036e4d746e96534fef1",
          "sha256": "19063c00f985d87358f10cc042e7df59fe1a77e6688bae008f143a0e59a92fb3",
          "sha1": "0223a29175489a5afdb85009bd2824d3ef400682",
          "md5": "5566b9703958decc7f8bd5ca8eb9260b"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.8.1-metadata.jar",
          "url": "lib-watchosarm32-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "fe70f3c8db9bc51c22fcab6243482dc29da6db05402d9da731a33da826a0914a73bac615305f1af8bfe91f54d8ecc0a89522e9b3dc810c5eb4cde49b4c9b3f0f",
          "sha256": "4fe8900a6807cfe2230fab152512676beb10199711f51f59283cf4b883045019",
          "sha1": "f992ab00f3736fdc639151152987376f06db02f0",
          "md5": "0736b015150172c5e5f8aa00454b9f7a"
        }
      ]
    }
  ]
}
