{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.8.1.klib",
          "size": 6846,
          "sha512": "c8e2b543b573471c83b4305dacdb9f5176f5cf252c20a97cb4a2f437cbb66390bdd626f877cd36268fdc6102f471b1a124133ce25d932cef0a7067c024ed6cf4",
          "sha256": "2ec4ca8048d89f5faadf6ddec0e62be8f0399c2a9796e4af53dc2ea6f7b34064",
          "sha1": "9b44d707150bd3d7e8581a2767070d063ec7cd04",
          "md5": "7aaae32905b77dd12471ac54251ccfbc"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.8.1-metadata.jar",
          "url": "lib-watchosarm32-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "db7bf4409c399b354679954326bda26fa55ae765c3f4f7cff98425a0bb17398f27679bad35a725c3dc981473b86d929f81be0bd48f6225531dea517ae25129b5",
          "sha256": "48b1df8168d2ac01c3c5cb60675d02484a6f34524c337c07a915d94e052ec52b",
          "sha1": "f0158ca17c52663f480bd60ca7e118a77e900234",
          "md5": "76fd49151f1fd5813b754e9dc7dfd7f2"
        }
      ]
    }
  ]
}
