{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iossimulatorarm64-0.8.2.klib",
          "size": 4271,
          "sha512": "ae4bb9e815251c0fbf0926c072f969f7f03d37683fa810b84efac6dccc34a3aa2046f96a9b50ce4ebe120ff112478bb5111045311632e0fbd060e759d06ac58c",
          "sha256": "147b6e60bf5f74daaf7253018a97b40cecd159c7732edf9bbb323c10bab17fbb",
          "sha1": "710dfb1ebf9da728531a6e54a3f13dad19dc4317",
          "md5": "485efe694d77cc8be575311eacab00f9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iossimulatorarm64-0.8.2-metadata.jar",
          "url": "lib-coroutines-iossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "44f1d9e3827a8a94cabe82ca0a77b485d75f115fbd206c5c2164b0a903b2c1c90299bb556ce085ede844b74a3c067edefaf390e6077990e9ad81a12602de6aa0",
          "sha256": "917a11549bab7e188ff655fa7239fce25d66248749f7a1d6d2cefa173779e36f",
          "sha1": "a6b05705e4440eded8ad5ec46558045e2476305f",
          "md5": "0259e2a4a00462427216e01bcfeb44c8"
        }
      ]
    }
  ]
}
