{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.0/lib-coroutines-0.8.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvossimulatorarm64-0.8.0.klib",
          "size": 4280,
          "sha512": "3dcd31b552a13bbf5be541ba2e0369ac79da48d88a29b3184a667fa3ff96e8846e8a3d06147b0667daf43fd42b472c829cdbde9650086be7bfbe84b5ed6e938d",
          "sha256": "af1b08bf4e8e9abaf23b64ef1b278961abb7ec183ef005480053bc1b759a27f9",
          "sha1": "8be48abb85049a7028336beaff13246ffcccd41a",
          "md5": "12920b4d29c559f3f4a7b13d87cdfba5"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvossimulatorarm64-0.8.0-metadata.jar",
          "url": "lib-coroutines-tvossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "0aaf90042930543dd626c575aa02192aba5e61dc99459caade75285f1643d5660ad8879f18ddc6c1021fedbd03ea5f963365d766e8202c174b984fa76af624d2",
          "sha256": "d10da0278fca951144f15d8144282ce145bf573aa04115a421b0145291f48faf",
          "sha1": "034be7c0ffe502c8607b2fcb47a98acbd175d158",
          "md5": "5456601857a2f07ff8899cbfa3b896df"
        }
      ]
    }
  ]
}
