{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.6.1.klib",
          "size": 8177,
          "sha512": "4e9fd78232c15e3c1c147cfe8c64981541768088c4700b201e6e6aafc81b9b0acdbf1cf31be8181efe3eda8a1bb0472e625dc50a4ba4d8953dea1e087c3842c1",
          "sha256": "8476988280281efb58e47942f0227f99441a3334691faed00a577e24392b1f96",
          "sha1": "1110ccbebe204514be6102131d4ce8e580dee290",
          "md5": "2d71ff709075ebeb7b44b669ce081cbd"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.6.1-metadata.jar",
          "url": "lib-watchosarm64-0.6.1-metadata.jar",
          "size": 3852,
          "sha512": "31d6abb5082f200798bfb7c6e27b41b00f503eab41083efb8b2f0266a451f6db37bcd4c57a81b92171176623c624df26301989fac5d5ba86b8b18abe463ced77",
          "sha256": "9e69a541e8397d61901ccc0142576befc2ae8fd0bc9741f9df6cf7a2498395ef",
          "sha1": "681f8d165d6689819fa6071ac124051fc420be2e",
          "md5": "0dcd47b51d829fe456691fc086656dff"
        }
      ]
    }
  ]
}
