{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.3-SNAPSHOT/lib-0.0.3-SNAPSHOT.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.0.3-SNAPSHOT.klib",
          "size": 14592,
          "sha512": "52eb7c62dee9032d798c9d635b7b3c6803fd2f6445a35c8ba0f5638f133431627d01ba1e647ba3669af03c45d7b20e09b119bc1d039d749999ac3a7abd6fd2da",
          "sha256": "0796f3bc37eac7d34a2594832b87ba43a742e1ff77908641ee0e0a563dd8763b",
          "sha1": "524b584735354cb7e31e4743044a34d67288f8bf",
          "md5": "fc09464b2139f92fa75b5b69a1bb03e2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.0.3-SNAPSHOT-metadata.jar",
          "url": "lib-watchosarm32-0.0.3-SNAPSHOT-metadata.jar",
          "size": 3750,
          "sha512": "9e8adbc8185ff25c42656fe5a11c4733ff99a8130325288363c3016a3cf7b285c0a0260991955ea2457792f0b89fbb3dc590dfc4616036087a36a5570fc12e52",
          "sha256": "408d04c00c71d273144f5a9f7b6ab0fc1039398052ac2e7aa18a7d5100c0758e",
          "sha1": "d0381347ab2b306b7af6b50f245d6f9150673ee3",
          "md5": "b58bf5f77417bc1a2f4c2938021d2873"
        }
      ]
    }
  ]
}
