{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosarm64-0.8.1.klib",
          "size": 4188,
          "sha512": "422c928e7edefa06bc60d502c31dce8adb2d1ebf511420edf1f45600bece679243019ae50595ebc11cccbbb297e3035d9c943462ee639f223b68096890d87368",
          "sha256": "b62d2c00718d394fb03bf470f9c0a7ede4bff690053216c1611a3a4f6356b813",
          "sha1": "aac0dcaacb4bef9a85a3c81484d5076bb48d635f",
          "md5": "19e23b041fce026ed3ca21420d4ff58b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-iosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f44f047ac2b0af45f3e563c3999981bb640f1fab60e27aa7bedcc83838f8f2591ec1ba7910e03c404ad142f69f5cf58e514b8b604e939e9a73ec2077ee1edbc5",
          "sha256": "f02ac83f65030fa6d824138b5fa0a3408abeb877e15c071f30b0efe519c14b2a",
          "sha1": "2124f1e45a2fa5df7c87922ccc27081a8b2d5066",
          "md5": "a950aecc98c6498d4ea9621c059c77ed"
        }
      ]
    }
  ]
}
