{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosarm64-0.8.1.klib",
          "size": 4185,
          "sha512": "f02a4142fa2c25eb3f81e88bb55a0db917930b1ba3fdcfb01e662e1964b16e6be69ebe6f08fd1523958d576e51c853db120ef28bfeb661abfa636fbea50bec47",
          "sha256": "871d52d959eacbb171f6730db3f11d26c388e58b921559dfd49e5ee6d4c90532",
          "sha1": "c05caa693b464555ffdb370fab5206e8e14e2b74",
          "md5": "a4666da7de74d3fbbd5528005fabe0cd"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-iosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "bbf04d594815f37f0d761407b0268f65fa0b51a2f16f09d704c264e7019cbfa603f36cf9107617d2e5c4c8921b1721338b28f88c9b9676aa4c44f9c868adc278",
          "sha256": "d036a9f1231fcf9b2712978829a2d8544bf7726461bcd46d6345f48202317f7e",
          "sha1": "dbe73ae6cd12a26d86720c0f31ed656c64f384fd",
          "md5": "3d888cfb5c07e3e9310ba082a84eb4db"
        }
      ]
    }
  ]
}
