{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.4.2.klib",
          "size": 14811,
          "sha512": "a2ac2c650e032d2e5c6e8e81a2822b7e04a08681cd6957e29cfe12a7d52ceca5f21cb7f043e49689aeb37da7982d1f1304828ebe0db3d6f87c09f33bd8e59dc7",
          "sha256": "d99785bd1ec4f86d4ee85843a48844e8c4c40d9d811338431a95c12b1b951f69",
          "sha1": "f9a3434c973a2d6001cc055ebf4275392c862b8e",
          "md5": "7831d77546657f1bd885badf5d507ee9"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.4.2-metadata.jar",
          "url": "lib-watchosx64-0.4.2-metadata.jar",
          "size": 4128,
          "sha512": "43e236e36efd3728155db53f86f5aacb6bab778519220647e0c6f382c58099d19f6b82c79edc36933909ade610dce889da06576d0881e4103b6d1b6d509ff3a3",
          "sha256": "7671e6bbbd23e00a48bbbce2aef723837df67def779537bad22648b241bef8ef",
          "sha1": "85bfca18d9be46d8fa3188318de9ed0ae65f437a",
          "md5": "57c17462026952a9bb2e4c91540cca2b"
        }
      ]
    }
  ]
}
