{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvossimulatorarm64-0.8.1.klib",
          "size": 6907,
          "sha512": "997a7fa90cc1928045157964a4c29adb613ee37d90cc0844d9a774365fc7858c4031abfb6d4295b99b7d0879e2ddd8d8a6fc916f1585106e286217a06eb887ae",
          "sha256": "bbf87288a24a1256dec0a72830ddb98e5f145433da0f9545ce4cc1691828349e",
          "sha1": "a7d37f63f4a32fb6e499de5f3f81e8e4267000dd",
          "md5": "689760e03c18de8b8ba30bccd1fed876"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-tvossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "edc5b0f7a1f0e15f5585a6615a860a7f389115fcdb8db870eb0def6033c0cd4bc3a01f166935b78f86d66a8bf9cfa875edcd997b5b0ad1c810d4968c58dae753",
          "sha256": "c6291ae49cc999f1d10ebe9a3f157ee1e4b2f2399757f9c87cc62950fc188a5e",
          "sha1": "3859e2e555d8e546c597d9ab42e0f05209752c11",
          "md5": "13e93c287a2d9a05c65c7e7c6eb2d33a"
        }
      ]
    }
  ]
}
