{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.8.1.klib",
          "size": 6802,
          "sha512": "c1cdd1aabb1650adbaf438980bf27a691b47a9c302807336c194a3e151325aa18f4f2c1264933c94e2b7cb5812b39990177ca7c29c5aafe9977814a52608c188",
          "sha256": "8a208417635c4e0393d6d1a09846214b0e81cb1b2448929166f202aa0ec11eef",
          "sha1": "267aade19d0c7ad52b15938372b83dac4b6dde71",
          "md5": "eb5e4c4c78b391220e98d6e8d818989f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.8.1-metadata.jar",
          "url": "lib-iosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "8282e4a291ab8444e848cf9993884091776ad0193b87701009e5681c6859c09e4be40f6a838f978bd53206595d7df68c4c2db2124ad4946e32cc52f2c20de341",
          "sha256": "d62e349a01e15a36a9b6a4f6d2fc61f28ddc114950a11cc04de9683df3a3028d",
          "sha1": "64c47071b2399c5f8f84dd60500defa3c58476d9",
          "md5": "80c57d71d54a41ddd0c24112122ddeea"
        }
      ]
    }
  ]
}
