{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.8.1.klib",
          "size": 6795,
          "sha512": "391096ad7deca3c715b3707b0e9e51e2773f72bc6611ebe21a7c9731ee903cc837a151eb260fa283d3c8b40fdafd811392d8c876a7e0938cb985780745813386",
          "sha256": "8a74bc2d60c39a2086db635527015a7ca122f653926c2a401dee0e973560f9f1",
          "sha1": "3e091a2d708a1645c647117388ac7e2e002e97f3",
          "md5": "446d8c3bb1155018916dbd52350e4844"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.8.1-metadata.jar",
          "url": "lib-iosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "3e643e3e12c28ddb7078d0b1bea56f367202c008d7bd8be3bf1a763028e648ace02275e24f0838cccd09e0ac99b84b76f757aadf5dd5a6fcbb46793241784608",
          "sha256": "4e7fffabcf9cf4b7795cc87e5c09f6e98d3166dab7faf2776832078c5c22f2e4",
          "sha1": "485e299c5306ce974ca3e34a360b7e550422976d",
          "md5": "21765da4824b24c388ad26b92b1d9638"
        }
      ]
    }
  ]
}
