{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm32-0.8.1.klib",
          "size": 4221,
          "sha512": "ae6acbd6cce449dd72a059cfff7e4fb25c42378037d130ea9c5ea9dbe020d4e24781f05f56d2eb808dd96304bbe915e56d74c36c6577cf266adc605070d4f398",
          "sha256": "d055590b4865fc04e5822a5e19cb47fe113ec3dd967140f5abb6a88816167f20",
          "sha1": "0f342fa15f68ef2887a79c18c8b3926ae514363c",
          "md5": "878bcb60275bdb361748fefef1a05562"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm32-0.8.1-metadata.jar",
          "url": "lib-coroutines-watchosarm32-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "aca0347259c3e90c2e916cfcd5724b61bad7d08c0c08c3c0daa6fe51814f79ca82e08ebc7e28b53c2bf2999959a889487ff88062cdb53ccf2a69669deee9e870",
          "sha256": "0698e44658ae19f0e4363f950a9c5ff46b8f33166c92651c28aa4070d4289a9d",
          "sha1": "2d2d1a465f2c5b3e583694ac156ce1b485be7fa2",
          "md5": "b51432dd368b5368357a461ec4992d37"
        }
      ]
    }
  ]
}
