{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.1.klib",
          "url": "lib-js-0.3.1.klib",
          "size": 14171,
          "sha512": "6904336426d854b9a994a67fb337b9ebed1a31d8173f6d4907b95dad3625e6bfdc0f654a35da243929b702b4f0a669d9928095900d773b40c2d5815b05cfaae5",
          "sha256": "a7862dd25dd3ba066f3720939c39cbe4954faea3d5b17f15e94e8935f1940d3e",
          "sha1": "1b9684e6629f867c2cec62ce16770afcba189e32",
          "md5": "da3f2e9b6fbc9020adb4e8c3a5c917be"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.3.1.klib",
          "url": "lib-js-0.3.1.klib",
          "size": 14171,
          "sha512": "6904336426d854b9a994a67fb337b9ebed1a31d8173f6d4907b95dad3625e6bfdc0f654a35da243929b702b4f0a669d9928095900d773b40c2d5815b05cfaae5",
          "sha256": "a7862dd25dd3ba066f3720939c39cbe4954faea3d5b17f15e94e8935f1940d3e",
          "sha1": "1b9684e6629f867c2cec62ce16770afcba189e32",
          "md5": "da3f2e9b6fbc9020adb4e8c3a5c917be"
        }
      ]
    }
  ]
}
