{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.8.2.klib",
          "size": 6795,
          "sha512": "391096ad7deca3c715b3707b0e9e51e2773f72bc6611ebe21a7c9731ee903cc837a151eb260fa283d3c8b40fdafd811392d8c876a7e0938cb985780745813386",
          "sha256": "8a74bc2d60c39a2086db635527015a7ca122f653926c2a401dee0e973560f9f1",
          "sha1": "3e091a2d708a1645c647117388ac7e2e002e97f3",
          "md5": "446d8c3bb1155018916dbd52350e4844"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.8.2-metadata.jar",
          "url": "lib-iosx64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "7cdbc82687a67975c2edaa17b14ad0d916abcd74ea5ecbb3ea296383524043403267e3bb8f41aa4c5a5dd89b2cd92822b33472e84b96d95ed7b2c9967ed030d5",
          "sha256": "85c820b307462f16fccd2fa8975a82f09b60b15d09b96ae708ba125b02b1e72a",
          "sha1": "2cd04ca28bc1f16058aee89dbc4b4d0503ad3ee1",
          "md5": "90db32ffbd87ac7869cce1134ef1b9c4"
        }
      ]
    }
  ]
}
