{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.0/lib-coroutines-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.4.0.klib",
          "size": 3931,
          "sha512": "f794c8d44aa2b1826633f7aa4335c8bfda6fca6d0eb71d04a470fe1a61c4685fca2eed572ad71f66d979267383883eed7c9d7cfb54a9c941095d360f8f802b5a",
          "sha256": "6acc1cea0420b0c4325ba7f6ac62de81505433f231a054bbef8f068cb4d24401",
          "sha1": "82a37bee9623701a4dfb2bd627e1c6f29aab87fe",
          "md5": "727a1a0d274668185803f1cdcc14e0bc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.4.0-metadata.jar",
          "url": "lib-coroutines-iosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "a6a7443cb87decb574afe40ac7fdf5c5d1e0d93b81de78e095ed7dd3a4190a63b19dd6e2f8cc7dede8812d2974575d52ec6c69015b26d6e672f6b81366f88977",
          "sha256": "be6620ee1218a707e0c922f236ffe5f499b5c6f9b94e180e025f54be1708a71b",
          "sha1": "fbd19734ae53a6ce2de72dd5b1616b78ecddcc53",
          "md5": "29d18f2789929e342005a193aa4835e0"
        }
      ]
    }
  ]
}
