{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.0/lib-0.8.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.8.0.klib",
          "size": 6829,
          "sha512": "2d958e71292a37f2363c4250fcf0ac82f954f28f3dd62dd530e08b222de9a0817b9a1fc5fd454f69a0734f3a014b990609b2455abef1412538f3303b84061abc",
          "sha256": "17823d3a65dbecc60156f0f56254be01ddda5885f7d7d4b6227fe7b6d1babc7c",
          "sha1": "7746fc9018adae0cc98a71a1be6d0128ea8c31b2",
          "md5": "f8de3a970e6fb68ce58502793c132c65"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.8.0-metadata.jar",
          "url": "lib-watchosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "edcc34c044adbbcf2833d7bd4871c27f04d969acabce5a078bfa32e8415210ed19f370b29b17fe61566d7711720fd3fe8c3f8b7a970ffe64e07a7749b44cf9d6",
          "sha256": "81e1e9b839c674998cc71e82b10307585accc73f7c39fb3d5bd3546d63ff4f6f",
          "sha1": "d0f8c846037d56947f6d7cd104b5405c30aa511d",
          "md5": "628a410365ca4042b7e3f34d239f1149"
        }
      ]
    }
  ]
}
