{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.5.0/lib-coroutines-0.5.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm32-0.5.0.klib",
          "size": 4226,
          "sha512": "a6dbb6a56fc52918e65c811b9f2186f9e55513086de807d761af7adab9a5e1d2d4a9635e0733f4cf5ec3ad125aa779ccaf546514a1f62005659b93bc045b2912",
          "sha256": "5e9a4b2d76bb63614594d3a1bf17355adcf31c0c42e605dde0705794aeeec02c",
          "sha1": "21e194ff12635eaf7690e9e328934b64b0007d4c",
          "md5": "13e7a008939f128e43e6e4bf609dedb9"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm32-0.5.0-metadata.jar",
          "url": "lib-coroutines-watchosarm32-0.5.0-metadata.jar",
          "size": 261,
          "sha512": "000cdb6661416397ff721c6ce230e712d12c90c0e218cfffdb715369a0f0095d79514dc302ac5caa9900d78f99daaa6c6ae2934573ae923dee72047b246107fe",
          "sha256": "885a7715d8f3c8326ec8c6bed6532a665cffdbb81af2ce102d69e1487d275c0c",
          "sha1": "17e6fefa90a06c5a31aee14fa5cdf65937b6aee9",
          "md5": "acd2668b102a68ce58849b16c8127c5e"
        }
      ]
    }
  ]
}
