{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.5.0/lib-coroutines-0.5.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.5.0.klib",
          "size": 4173,
          "sha512": "52736da0abc759f21628e72444cf8b6076e40441031cf6389faa5c78d216e93c2e40cc6a87363c1044e10799ade59a97e7575d9690fcaa5ac5fd2bbddb917e0c",
          "sha256": "af5d98c6acbc59fe8bda72648e19a03d655405673031ed0e5955684be99c17a0",
          "sha1": "25beec836498551d098dee5f8adf9dfbd6f2a7fc",
          "md5": "cfd58639a935a5c934157af7ddc493b2"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.5.0-metadata.jar",
          "url": "lib-coroutines-iosx64-0.5.0-metadata.jar",
          "size": 261,
          "sha512": "000cdb6661416397ff721c6ce230e712d12c90c0e218cfffdb715369a0f0095d79514dc302ac5caa9900d78f99daaa6c6ae2934573ae923dee72047b246107fe",
          "sha256": "885a7715d8f3c8326ec8c6bed6532a665cffdbb81af2ce102d69e1487d275c0c",
          "sha1": "17e6fefa90a06c5a31aee14fa5cdf65937b6aee9",
          "md5": "acd2668b102a68ce58849b16c8127c5e"
        }
      ]
    }
  ]
}
