{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.8.2.klib",
          "size": 6819,
          "sha512": "1c0fa99e6eb270f36f2e8e412df2090c81db1912af8c89dfb5c6b4d4beeaa6d13921c0eeaa0815a28b5f247b4e6eebf40ab3fd5073d4b832cad488ef09216410",
          "sha256": "22ee576abc141bf9f37c4d4f79c090cd7cc37034f34e5476480130829b5ddfb2",
          "sha1": "21a124ec2af5a223604d53ee791c70a302cc4b3c",
          "md5": "ef16eb2b18a4ea9e1c13a70e7e13e2fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.8.2-metadata.jar",
          "url": "lib-iosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "bd9f32f5e4adde7aaf42f9979fbdf91a7fd23c0da3bacf08992caa477ad5762ecdad872cf09bcb92bb46b27ab7943741710580040fc2f8230594bd36ae5bd7db",
          "sha256": "e5cc3b43e7ece3f8a66ce0c19da0ef30a84ab277460cd927fd9ea7ba5729ce4d",
          "sha1": "3ebc4ac36a3e03779ec38b59f92c1763c9f73044",
          "md5": "728f223c3e9320ed8c0821c8562b19bc"
        }
      ]
    }
  ]
}
