{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.8.2.klib",
          "size": 6812,
          "sha512": "57509f248e8fca38fe0c6134d44cd82163fc876f67ce116fa589b77425b9c0a3dc56a4b95739e83fa213aec4b5c942275826734e39fbad73d3e709a8f49c35a3",
          "sha256": "e59e24d9e65aa676ce806b76787559da1495fef6aafcbb5889863b9f1e8697ce",
          "sha1": "28188106942edc1ed61458bb8b67d51aeeb0a1ee",
          "md5": "94942edb39bf3fcfd63d4c6dbfeb89ac"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.8.2-metadata.jar",
          "url": "lib-iosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "761df28d2f7a4ddf5de17423f2fb32d9ba47d42c0fee00e3c9f49d1027f2d27076165fe2e9423f61b3a0328b64cf741099a928f2f7690375ddc1c0a43880cd5c",
          "sha256": "f3e7338f382abbdea8f0947c47614271d72297fbd792e384dbc8cadc4a24ab77",
          "sha1": "cfe93aa231345935af2f2dbf056e75469f9774b6",
          "md5": "591823da8c9fa275d6f15ef817da9405"
        }
      ]
    }
  ]
}
