{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.6.1.jar",
          "url": "lib-jvm-0.6.1.jar",
          "size": 4324,
          "sha512": "f4e8f641ba26ad16f8c85fcda049834240236593eb73d3ab83627251df11b59d2f58a5dfe5ecd357f95bcbb71c8a5e68912f117f7d570f4d1bb39170f316dc00",
          "sha256": "44a87c72d867b98ae5b406c018e8856d11d9fad7ca72f1f770dcf36b12911563",
          "sha1": "f11dc746302c12c84cf0b0fee0deeffe54470ff1",
          "md5": "58ddf5a1833829a9f8d2e103bfcb1cfb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.6.1.jar",
          "url": "lib-jvm-0.6.1.jar",
          "size": 4324,
          "sha512": "f4e8f641ba26ad16f8c85fcda049834240236593eb73d3ab83627251df11b59d2f58a5dfe5ecd357f95bcbb71c8a5e68912f117f7d570f4d1bb39170f316dc00",
          "sha256": "44a87c72d867b98ae5b406c018e8856d11d9fad7ca72f1f770dcf36b12911563",
          "sha1": "f11dc746302c12c84cf0b0fee0deeffe54470ff1",
          "md5": "58ddf5a1833829a9f8d2e103bfcb1cfb"
        }
      ]
    }
  ]
}
