{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.3.1/lib-coroutines-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosarm64-0.3.1.klib",
          "size": 3957,
          "sha512": "2486eb2f60d6fc6a735d69d101d500aac0c7fbb4129ef6f56df542fa54430e6f74e783eda41ac87a85ea5bd88355001eeaea874fc08d9dc6ab7178fe8146dd9a",
          "sha256": "cbb64fde4fbf5d836e28727be2a072690962cd96c9766e0802f730a42051fd4f",
          "sha1": "57fd90f8f73ffc1fd534786703ee62e132446938",
          "md5": "d428ba2a5b505978f653cd4bece96d44"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosarm64-0.3.1-metadata.jar",
          "url": "lib-coroutines-tvosarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "d859250890e7e1465fa8ced98453359213584064f23d1564c1df922f3e8b42fe5c03f7dacf28e952906b7e381a04b59129c183ad283ef4100994ffef77c0f1cc",
          "sha256": "64e6ccd1550b2e3dc90453d461116446e272c2886b65dcf9653b57710f15ccd4",
          "sha1": "6b39e2361e74d2e9d385c28fea6bb64aece0813e",
          "md5": "55dfdcc7d4ac83af6857a0064eef1fbd"
        }
      ]
    }
  ]
}
