{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosx64-0.8.2.klib",
          "size": 4178,
          "sha512": "02eff66d166c6255bf14d8ff740ad77927d4b9e1a42b6aeeac781d91d4ea2e33a87d7a70303c7003792ccbabb021d1e74798dc48e4f3b8bbc1aa2166b5bc48ec",
          "sha256": "f3b55746d3164ba3044e9b7cc572dbae5288f21eaf2eb72922959c43b43a7f93",
          "sha1": "dfa0061e1d4d3fbe704c622f567d99cae7fe1b90",
          "md5": "237577f5296b36576ab256595ea26cd2"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosx64-0.8.2-metadata.jar",
          "url": "lib-coroutines-tvosx64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "4a28a495eba64a80960037f7134ff3b483355ab9c8637460ba4cf8e6f0db7a95494eca51c1a838134773bb46558829f6d4498d1f453fa4d9dbaf02ede227551b",
          "sha256": "0ead03b4fe32f4ce9d08552ce4496e785df0258f5a5fdba00d2abfbd35b26d0c",
          "sha1": "1e166a4058d340039dc6a211b26b391b8584fba6",
          "md5": "175ea1e8cf2cef66adb94cefb379f944"
        }
      ]
    }
  ]
}
