{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.7.0/lib-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.7.0.klib",
          "size": 8177,
          "sha512": "3a2bac6faf6993485e13b9eec6c353e9c25e5c1aa0a6abadcf702f59f21f1f6ecfdeb86148787aaca2f15d26bd948cb052d4b91d3c3e04f131d60507a5d9ff5c",
          "sha256": "d05452824184b0eef663ef906e458a478cfae209d8bc846e59351d34b8425336",
          "sha1": "557273110430ac82a3a6a8d79055ce267cffcda4",
          "md5": "049e1a80cbc89a095d0fd2d825e75b28"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.7.0-metadata.jar",
          "url": "lib-watchosarm64-0.7.0-metadata.jar",
          "size": 3852,
          "sha512": "0fd68279ec30aa78a730b538e720024c1e21037717f99351f56983ca69757a67f171d07c90d684ad7f9665523e4adf16fdcc9b3bac4a9f4e25381a2b2cda8dd1",
          "sha256": "2ecfcdf3366015aaac2219ffffeafb7e5bb86c762d267509fdba98e63830ee9d",
          "sha1": "7ac042b7570355c1e9f47f35ea290e34125438f3",
          "md5": "f26a240ce49d33641898c9f33591791b"
        }
      ]
    }
  ]
}
