{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchossimulatorarm64-0.8.2.klib",
          "size": 6933,
          "sha512": "c6b4bf7260fb5c348dcf3251a76a17a70658ea6cac972b5774c2e82108f41961243cfa2e561a158dae1f175f7462686385f06da0e94d42147719b7d81d17d2ef",
          "sha256": "89e068a4826f63c6ea93c4bffb47edbd86a2388ea6ef20a7e0c31254b97321a1",
          "sha1": "a407c9830fa35e73e39f499358116dbcfc832705",
          "md5": "14151e5deb027ba92ec2540e95bc51bd"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchossimulatorarm64-0.8.2-metadata.jar",
          "url": "lib-watchossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "0cae9526c6f4ef4c5c9382ade86b8a39d5c342fad246dad534072bea4bb84276247a10e58c753f4b3f09676a25d9a17e0feb7a9351633237a85c7b46f41bdb74",
          "sha256": "039ac479e95a11c6d00598941aa403d9d1e180bc4babc356c03c01ded73366d8",
          "sha1": "766af9c127658846361dfdf7599aa39c00778fe7",
          "md5": "192b0a443daeebff4b400d7ac1ea34bf"
        }
      ]
    }
  ]
}
