{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.4.1.klib",
          "size": 14562,
          "sha512": "0e824e9e197ce727949871cc7ed217e761a215ade8ffe5bd3a1626bbf14ddf1a6e01c16efb724e4e2df5532239ba3a937003f4218d7e17aa36c110316495a8de",
          "sha256": "885dc8a4ad7b5f00c8ffb6b2892262270ea7404995a8bf2315c598a10dd9ba6d",
          "sha1": "e4306e51a40a547e664e0c9754d2694d233f55b5",
          "md5": "35461a55f49d4304e002e2c946c30a27"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.4.1-metadata.jar",
          "url": "lib-iosx64-0.4.1-metadata.jar",
          "size": 4558,
          "sha512": "207ce19bf3b11bb655ba1bf401bcaf3283ea04e661d40c6c480f94737581167d47a3cadcf6e94bb3ccb1ea878fbad9861fe6d593c6a39d61e84071efdbc74666",
          "sha256": "2e85d05d5a8f31f9d6226eccc1f324a993e1d08eb4520553b8511826028ff044",
          "sha1": "dc96b9fcd2597efae6168b20728b83e9589d618c",
          "md5": "2232f8e1baaffc6f36423925a25ad3a4"
        }
      ]
    }
  ]
}
