{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosarm64-0.8.2.klib",
          "size": 4198,
          "sha512": "c5d8a84ad26873d0d57adaf406e4033e52fe4372124893c92df396498ee1dad8ad4f47c408ed9ec830deda9b3f3b9e4298943620ed7e99c233911757198fab4b",
          "sha256": "b82f1d86efeb2835ea2227e02604872b972e87a5a7fcf6fb363804830999648b",
          "sha1": "26fe9ae4a6fe8cd73a5891b314fb65e1caf6a20f",
          "md5": "c655b487e85dfa694926f42eef1c6456"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosarm64-0.8.2-metadata.jar",
          "url": "lib-coroutines-tvosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "b630ee6bf594f1cb7b42504d0d5864bcdcff9ba4cf76849389fc0c2928704cb3b5052ca0d9dd3f4af6bd151528676afde94ad2c91e2605e25ebf65f04b73ebda",
          "sha256": "5c6afdd20ca75aef1cf94390fb7919e528e41e60373515f4a87697248496c992",
          "sha1": "ab9633fccbfacdd3400d1563abb06ba038e03c2a",
          "md5": "fad31fdc9511032d7530751f250f2c18"
        }
      ]
    }
  ]
}
