{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosarm64-0.8.2.klib",
          "size": 4195,
          "sha512": "58b63320e821412c55b803ee68dd695a5d140f3dca4ab51c7a59f4013cd5daf8c7aa31d3dfdf8d3eb38079eb04587c083803a12f8e9532e05d8fc5383de26a0b",
          "sha256": "e85b166bf709da843f78b45c8131084ee13b90aed68bfa4bece4841116c0d6c5",
          "sha1": "c7dcccd644c19c2822a5ff7cc48dff7ca8a1eb31",
          "md5": "9bddfb6161458f687b7063323dbb37d9"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosarm64-0.8.2-metadata.jar",
          "url": "lib-coroutines-tvosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "4a4378de18dfac9b1f490d0e6ab3d3616ddbc2a88b21a6e38230c138e61c5b647bfaa0e9f07f8698ad9df47fa4f509f6d60f90a489721f72f379e1bdd7ae44fa",
          "sha256": "8efe6489002b2149dd2ef37008be71edaec8338734888aa5912cf6462bb2014f",
          "sha1": "e634d5f057b92ac8ca53e4177de2e2d575846a97",
          "md5": "0fbd41301bbf03b429db03e7fac76748"
        }
      ]
    }
  ]
}
