{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.4.0.klib",
          "size": 14683,
          "sha512": "b2cfe46437cbb538e946096bdae1032d4454dbf11d3991624e98037c430f06a0cf6631bf21bd4f4af7285f617a24d8ec19129da18cfbae6501fdf42e7ac91549",
          "sha256": "a2d415f3ae51ef5b81af034bb502f0932add434b7abbc3ee1ff6b293f7a373de",
          "sha1": "d377e55a5c45086a0b18e91de5c58c9338bc54ce",
          "md5": "5a2dbc0095b1c18b36354d07ee9c6b70"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.4.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "37a1707e7e22295f2c11fa9d7108edb7c070c11b3bd4f7d80eb5cbfa457d842c2cddd574bf8695fe5323f7de8ec2537d3fba77af290213c8c4afaa3fbaa72343",
          "sha256": "5cf066677af7297caae4d11a12db8b9ce51ab2133c45af9a07f1ad458fbfe578",
          "sha1": "6abcea90e8e443c6736330e84a34706d425d58a4",
          "md5": "767347de1ca6ff7628c0dc1722aef8f6"
        }
      ]
    }
  ]
}
