{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.7.0/lib-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.7.0.klib",
          "size": 8148,
          "sha512": "4163c8198c85bb21fc6f664f7fed46449e9e72610a7dcc27f95376c66994630bbe6f02ba3b73238489cb8a1d1a827515abc530429410fb19edf8367b7f1464be",
          "sha256": "77601155b0f846bc6af547f4aad83ec1fa618f0dc8e3d2cbeb0b4396d01746dc",
          "sha1": "faca6d57e85ba92e6c9af2c4f92daaa27bab8886",
          "md5": "32c312ce189246560518320e70b334c1"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.7.0-metadata.jar",
          "url": "lib-tvosarm64-0.7.0-metadata.jar",
          "size": 3979,
          "sha512": "f715c76c17a906891e60077ef2e33a4f0a5802f01c9138a26fb7b8ca035093878b567b5bd7c19f180f51c61d030354ec27c4437d698101f11845eaf5756e3d44",
          "sha256": "3a71ef808b1b9cb0cfb815c4c72366ea7d3e114ee087391e3506399fab94bb4e",
          "sha1": "e77505243898b1eff84a9b288348a9e2d248dcae",
          "md5": "acc730711f1c6c31d4ad6f8c69652e55"
        }
      ]
    }
  ]
}
