{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-0.0.3-SNAPSHOT-all.jar",
          "url": "lib-0.0.3-SNAPSHOT-all.jar",
          "size": 4595,
          "sha512": "2ecfa78e5372640315e55033d5f7cdc9c8a85b05e89f58e3d4c396d99c216412cef581e24c31306cd88a5de3aebb1eb20b191a355338f7eecbb6b4b8610e8331",
          "sha256": "eb029d8fe342676ff0f48628c256b5d3884ed3fadbc376a4c378b13213e3b483",
          "sha1": "1d3f1f286e9e6c377223d604f8ddf2e2a9790e7c",
          "md5": "0e0b58aaea709dc4e57a22d81a04a7e5"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.0.3-SNAPSHOT.jar",
          "url": "lib-0.0.3-SNAPSHOT.jar",
          "size": 8811,
          "sha512": "c2a0c31d18156b7ca5cea7c7afc3a3f168087005b043772b358b54c6f93241e288c9b8b0bbd11003f9fc593bc0d471909942e880ad189cf725f1735911ce5e80",
          "sha256": "6951417a68afa03bb0852dbfbcbbfc804912985e8a4c6abcaefd60045d5ff055",
          "sha1": "86ac10c1ab9f5a830bb917fe65925eba26d9310f",
          "md5": "713f6e8f19b88bef6389c0ee5e88ad58"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.0.3-SNAPSHOT/lib-iosarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.0.3-SNAPSHOT/lib-iosarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.0.3-SNAPSHOT/lib-iossimulatorarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.0.3-SNAPSHOT/lib-iossimulatorarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.0.3-SNAPSHOT/lib-iosx64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.0.3-SNAPSHOT/lib-iosx64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.0.3-SNAPSHOT/lib-js-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.0.3-SNAPSHOT/lib-js-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.0.3-SNAPSHOT/lib-jvm-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.0.3-SNAPSHOT/lib-jvm-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.0.3-SNAPSHOT/lib-tvosarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.0.3-SNAPSHOT/lib-tvosarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.0.3-SNAPSHOT/lib-tvosx64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.0.3-SNAPSHOT/lib-tvosx64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.0.3-SNAPSHOT/lib-watchosarm32-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.0.3-SNAPSHOT/lib-watchosarm32-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.0.3-SNAPSHOT/lib-watchosarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.0.3-SNAPSHOT/lib-watchosarm64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.0.3-SNAPSHOT/lib-watchosx64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.0.3-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.0.3-SNAPSHOT/lib-watchosx64-0.0.3-SNAPSHOT.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.0.3-SNAPSHOT"
      }
    }
  ]
}
