{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.0.klib",
          "url": "lib-js-0.1.0.klib",
          "size": 14174,
          "sha512": "866728ed3194ffb3e14fd5ebadf0a85c265fa40fcdf984e7da5520235cbc18fb6b059c526b559ea4c8213c5480913f222e669f0860765733826ec35f35643220",
          "sha256": "cf85e50590d72053587a2fd20d15a0d87278adf220e2a7fa96d5c644ba46a257",
          "sha1": "6ca0862c5f3deb7d9562205ce38a68ee5522ffc6",
          "md5": "7d9c2bc627934169af13f6d3a7225e3d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.0.klib",
          "url": "lib-js-0.1.0.klib",
          "size": 14174,
          "sha512": "866728ed3194ffb3e14fd5ebadf0a85c265fa40fcdf984e7da5520235cbc18fb6b059c526b559ea4c8213c5480913f222e669f0860765733826ec35f35643220",
          "sha256": "cf85e50590d72053587a2fd20d15a0d87278adf220e2a7fa96d5c644ba46a257",
          "sha1": "6ca0862c5f3deb7d9562205ce38a68ee5522ffc6",
          "md5": "7d9c2bc627934169af13f6d3a7225e3d"
        }
      ]
    }
  ]
}
