{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.8.2.klib",
          "size": 6803,
          "sha512": "4511f06a23267c9e239fde8fbb608c9e8decc7487dbb998a8316f948e4d7c7ebeaf5e79faf3fd90eaa19b97be0afeb512f89b23ba73d0f8bb35e41bed48e7378",
          "sha256": "90177852bc3d34da6f2f1796675add0834133036c34ceaf1a556cfd145caede8",
          "sha1": "a2350d83a100022d756c70a3a3d96409f0ec219f",
          "md5": "0bddf98d85427180ebdcb18cd58584ac"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.8.2-metadata.jar",
          "url": "lib-tvosx64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "3f680cea8704ce70130ff5a8700ebbef90961316a7cb4809869dd6e6dfc60a809e378ed3a6a042be9f052ce8637f10078bace7bea6ba92d9a4030417b0892c2c",
          "sha256": "7822aa6b54b046c4847eb8bea1d2fe2d5c54403c01793e281d4b8e1bd5c4d18a",
          "sha1": "28f24233ee92c12832dcc9a61031850edb42de99",
          "md5": "6e759fd8d71049b9c75c61f21810a423"
        }
      ]
    }
  ]
}
