{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.0/lib-coroutines-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm64-0.6.0.klib",
          "size": 4224,
          "sha512": "015350de8520ac58ebe61387ae4a812861d968a16ce1641cc2374d79fde6fe77f46fb69fc896acf7a380e047a54b7aee3317a9a6c17586cf1824bb78b7cebcc3",
          "sha256": "782850602c63fc8b9a96e6dd3985915497710770e433ad233a7ab07c844a74c4",
          "sha1": "24c401d2e11e19de5b8c5420a9395ea40e8f0507",
          "md5": "21d0caaef5b0aed05028d4b4340675b8"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm64-0.6.0-metadata.jar",
          "url": "lib-coroutines-watchosarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "1fcdc5d614e84d4d099b4126d85fd0ac17f330a7fc084bf82d2b4a15f0ee4b33b9acf4ab562a13abf2ddd4bb7e41d7165b850dd04b72ec7c4a716376a4f075c4",
          "sha256": "801bf6062b239a27faa3b81e4e7f43211b0e0aff6a01f67bc5e9d128a03d69bd",
          "sha1": "11b55cfe9a249cc5591684ac4711260391247e23",
          "md5": "91adb4b5b3f7a77cea3011561cfb3ba7"
        }
      ]
    }
  ]
}
