{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.8.1.klib",
          "size": 6812,
          "sha512": "57509f248e8fca38fe0c6134d44cd82163fc876f67ce116fa589b77425b9c0a3dc56a4b95739e83fa213aec4b5c942275826734e39fbad73d3e709a8f49c35a3",
          "sha256": "e59e24d9e65aa676ce806b76787559da1495fef6aafcbb5889863b9f1e8697ce",
          "sha1": "28188106942edc1ed61458bb8b67d51aeeb0a1ee",
          "md5": "94942edb39bf3fcfd63d4c6dbfeb89ac"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.8.1-metadata.jar",
          "url": "lib-iosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "442edfcd86a2f9206a95398088e1c6814d52225084f06831ef7cc90c528a1de18ab528b5c60d5d7d46e83543b2af787cb39d31ba62554f31e78739ad90362cfe",
          "sha256": "b2f7247e8ee420e83361634341476879177feaaaac8ac7e5d7007856f694834e",
          "sha1": "45875a3a254549b7396090873f8821579aede216",
          "md5": "8e57dadd92b0b7fbd2c231342a115179"
        }
      ]
    }
  ]
}
