{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.8.1.klib",
          "size": 6819,
          "sha512": "1c0fa99e6eb270f36f2e8e412df2090c81db1912af8c89dfb5c6b4d4beeaa6d13921c0eeaa0815a28b5f247b4e6eebf40ab3fd5073d4b832cad488ef09216410",
          "sha256": "22ee576abc141bf9f37c4d4f79c090cd7cc37034f34e5476480130829b5ddfb2",
          "sha1": "21a124ec2af5a223604d53ee791c70a302cc4b3c",
          "md5": "ef16eb2b18a4ea9e1c13a70e7e13e2fe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.8.1-metadata.jar",
          "url": "lib-iosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f3dc7a2921f3ece1daea626484e21bbc3438b80b67dea90717b2e8ce1cdc48924d4791f5542e4ed27e3cabd41fac56f7f1423da3d71401d764271fd6e56af78a",
          "sha256": "59f4d7dded4fc235184e54dd4d2ec6c034fea2b1c9d8ae6cdc3a25deccb56a5d",
          "sha1": "16f455566fa157ffc21795503949dde3ceb32caf",
          "md5": "5a35a78817fbaee7d4e8feeef4ae73e1"
        }
      ]
    }
  ]
}
