{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.1.jar",
          "url": "compiler-0.3.1.jar",
          "size": 214441,
          "sha512": "f52fb63a1079a43f6118f6f78e86a119088e6443292cc24011c0ff5b739cafdb626f90bfb509d64e69194ad478d2e51128771ad27bf2ce674d7f812391345d48",
          "sha256": "7b2076cff76500fc3421791eee35b38b70e77dcd375baa4e2ecbf7fd266c893f",
          "sha1": "e364c901365b3c1883601c2fe4453bf5f55f0de9",
          "md5": "521e49ae1ca50c49ec6469096097ed7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.0-1.0.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.1.jar",
          "url": "compiler-0.3.1.jar",
          "size": 214441,
          "sha512": "f52fb63a1079a43f6118f6f78e86a119088e6443292cc24011c0ff5b739cafdb626f90bfb509d64e69194ad478d2e51128771ad27bf2ce674d7f812391345d48",
          "sha256": "7b2076cff76500fc3421791eee35b38b70e77dcd375baa4e2ecbf7fd266c893f",
          "sha1": "e364c901365b3c1883601c2fe4453bf5f55f0de9",
          "md5": "521e49ae1ca50c49ec6469096097ed7b"
        }
      ]
    }
  ]
}
