{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.1.jar",
          "url": "compiler-0.3.1.jar",
          "size": 214441,
          "sha512": "a3c238eaacc9f2d4b4bf675656721bf5b26948152530f02ea06eecffc407eb7d94ed913b199802d9e5f870e4c3f43becc548680dafbafe7d4420d2938f86c246",
          "sha256": "da6684fce67be925ef8d46d102f7d5455ff8dbaaa8333db041e85cdf7da77edb",
          "sha1": "1fe3c67211245c994d740b33ab361d387eece515",
          "md5": "44218846e27e03d2ed7bdf7afd43c85b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.3.1.jar",
          "url": "compiler-0.3.1.jar",
          "size": 214441,
          "sha512": "a3c238eaacc9f2d4b4bf675656721bf5b26948152530f02ea06eecffc407eb7d94ed913b199802d9e5f870e4c3f43becc548680dafbafe7d4420d2938f86c246",
          "sha256": "da6684fce67be925ef8d46d102f7d5455ff8dbaaa8333db041e85cdf7da77edb",
          "sha1": "1fe3c67211245c994d740b33ab361d387eece515",
          "md5": "44218846e27e03d2ed7bdf7afd43c85b"
        }
      ]
    }
  ]
}
