{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.0/lib-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.6.0.klib",
          "url": "lib-js-0.6.0.klib",
          "size": 7119,
          "sha512": "1a8eeac5666644ace5053a10ce1db2969567f76860a24ae8bfaa570a2574727dc60dd9d99d650bee468f541b1361bff15cbbae7c4f5ca6c66c30c288df3327ad",
          "sha256": "ae765749637e57879ab9a01efb9babb518934da57a57100940fcb61fd7f62303",
          "sha1": "af28085f1278d91c173a2f5a1e0f667c1983fa4c",
          "md5": "a7bf0adedb91ac38cb55153f1eeae353"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.6.0.klib",
          "url": "lib-js-0.6.0.klib",
          "size": 7119,
          "sha512": "1a8eeac5666644ace5053a10ce1db2969567f76860a24ae8bfaa570a2574727dc60dd9d99d650bee468f541b1361bff15cbbae7c4f5ca6c66c30c288df3327ad",
          "sha256": "ae765749637e57879ab9a01efb9babb518934da57a57100940fcb61fd7f62303",
          "sha1": "af28085f1278d91c173a2f5a1e0f667c1983fa4c",
          "md5": "a7bf0adedb91ac38cb55153f1eeae353"
        }
      ]
    }
  ]
}
