{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.8.1.jar",
          "url": "lib-jvm-0.8.1.jar",
          "size": 2725,
          "sha512": "4c8fcf0cdd2253894a1c626588e687bd46fc7b505351b0cc2ebca3c0889ffed444e7a8fe9b33999a999239f76fb502d7fc6628ef41fc3ca25fa9031bdc665de3",
          "sha256": "7b96dee8f8ccc97305705cd7f862549fd35733c4836381068b2dc4c647381df5",
          "sha1": "0f1018b243b71d6e643a87e398b9d10c60289af0",
          "md5": "3de414411039d955e7807fd30f62a3f8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.8.1.jar",
          "url": "lib-jvm-0.8.1.jar",
          "size": 2725,
          "sha512": "4c8fcf0cdd2253894a1c626588e687bd46fc7b505351b0cc2ebca3c0889ffed444e7a8fe9b33999a999239f76fb502d7fc6628ef41fc3ca25fa9031bdc665de3",
          "sha256": "7b96dee8f8ccc97305705cd7f862549fd35733c4836381068b2dc4c647381df5",
          "sha1": "0f1018b243b71d6e643a87e398b9d10c60289af0",
          "md5": "3de414411039d955e7807fd30f62a3f8"
        }
      ]
    }
  ]
}
