{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.1.2.jar",
          "url": "compiler-0.1.2.jar",
          "size": 206217,
          "sha512": "c5b226dcf6dcbe698c6f34173b51fb6097feb07e4119dfe8e7bdce25a23ee99cf50c3e6cc3e6b489981adfcd1ba8d46097c7823ae3668eaf295001c503c59eed",
          "sha256": "974c3a40ae17d2a806678d2970f79b33a0908d87520de1912cf0fa4d0cb4a8a9",
          "sha1": "034be74ffec5657ee3f63f6061a6c32395410b8c",
          "md5": "45290baa9063e9574826bfbab8c57352"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.1.2.jar",
          "url": "compiler-0.1.2.jar",
          "size": 206217,
          "sha512": "c5b226dcf6dcbe698c6f34173b51fb6097feb07e4119dfe8e7bdce25a23ee99cf50c3e6cc3e6b489981adfcd1ba8d46097c7823ae3668eaf295001c503c59eed",
          "sha256": "974c3a40ae17d2a806678d2970f79b33a0908d87520de1912cf0fa4d0cb4a8a9",
          "sha1": "034be74ffec5657ee3f63f6061a6c32395410b8c",
          "md5": "45290baa9063e9574826bfbab8c57352"
        }
      ]
    }
  ]
}
