{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.0/lib-coroutines-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosarm64-0.6.0.klib",
          "size": 4197,
          "sha512": "836a8cfdf11e32e51a5eddbcd8801afddba9c8c919f39afef70757270d2d59abb3cd68b2da7fd4604897199e831640de135590aabbd390d59ef6c36f5e8ffe7f",
          "sha256": "98d6613b4bba607b361090d9c0fd373bbb50f1d4a74118b0f8e4a65afaf7becf",
          "sha1": "b3043d218c4b2315c5ea076c44769b596a6f6847",
          "md5": "147c9c1040febecceaeafc7caf181d9a"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosarm64-0.6.0-metadata.jar",
          "url": "lib-coroutines-tvosarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "1fcdc5d614e84d4d099b4126d85fd0ac17f330a7fc084bf82d2b4a15f0ee4b33b9acf4ab562a13abf2ddd4bb7e41d7165b850dd04b72ec7c4a716376a4f075c4",
          "sha256": "801bf6062b239a27faa3b81e4e7f43211b0e0aff6a01f67bc5e9d128a03d69bd",
          "sha1": "11b55cfe9a249cc5591684ac4711260391247e23",
          "md5": "91adb4b5b3f7a77cea3011561cfb3ba7"
        }
      ]
    }
  ]
}
