{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.1/lib-coroutines-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iossimulatorarm64-0.6.1.klib",
          "size": 4274,
          "sha512": "0c2ca0cdedd7140516a838b5d64cdbbc4e78fe846c98e1ee3611c40615a11659ecab8572f716a63cdcd9a6f9defad524af2204d9b0a62914ddc08b5ea6ed3204",
          "sha256": "1f4edc50eb0ac36cf9b45bee93ef465db427acd018fd69fb211162d9c087d084",
          "sha1": "803336d4a8c34937c4d46447bfc173a883fbf3cd",
          "md5": "6b4d1f4bf7a705fe3034df5e502dd937"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iossimulatorarm64-0.6.1-metadata.jar",
          "url": "lib-coroutines-iossimulatorarm64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "181194e15dca1964a4597a1d0228ccfbf1737c79efd5e89a240a07f37b0b6e6103d82927f62fa4c6c205eb51ce2d7ac6120d5408447476102e7188df9b326d06",
          "sha256": "548b4d5a4559b854eda48c04bb77a0df6a86f2babee47e56486b1faea3d09902",
          "sha1": "a04b3249beb1edf025ff68c6221fd3afb819a82a",
          "md5": "4fcf19c6662b6d2c84995918f22fb583"
        }
      ]
    }
  ]
}
