{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.0/lib-coroutines-0.8.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.8.0.klib",
          "size": 4168,
          "sha512": "70daeea5e8e86133dc43c101d4420bc03cf27c6014348e0817d0289a4f9d1c22c0ee4297b27b37cfb31bb99770173cc88d32f8f573271c14dcd2bbfb4c2aece1",
          "sha256": "c18c12bbd55f54cd55fdf6fa357186eb28dac6995ce0857af4b0fcfd790bddb8",
          "sha1": "39bed6ac81c752cf1f54346867e1ef893f83ecca",
          "md5": "c8afff7da5925266fdc762a6ed604898"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.8.0-metadata.jar",
          "url": "lib-coroutines-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "6689f1bb08069b9f302121ffad055d6e73d8d60517fc7482b4a778fe243d2588de4c250fa2c535906796ea767717b8f9cfd98ed98b868721263b2133d32aa843",
          "sha256": "88aa5ef844080b9d041fd89616b288ec014c0afcd76f2988d005d30920a675d6",
          "sha1": "46acd34606d6ed1705e3bc8478f51d048eb19f40",
          "md5": "d982d516852969d90ed7849b3481c1fd"
        }
      ]
    }
  ]
}
