{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.0/lib-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.6.0.klib",
          "size": 8117,
          "sha512": "43a90c5e7c8acf22a00c0fa177c81d96808f27a995fc134fcaa9260c73b02afe6d63ea5f955043f91036df57b6dfa7f4af16a5214d0f1272a79d47a637efef07",
          "sha256": "32d92cc71bc7d7fa4d8d1215c970324526889a51e2b5485678575d3c78cd44ef",
          "sha1": "aa317ef889a97e7a9a4a4d298cabdfa50e8ccccb",
          "md5": "86e991f993010a0a8c158b5581138e79"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.6.0-metadata.jar",
          "url": "lib-iosx64-0.6.0-metadata.jar",
          "size": 4266,
          "sha512": "d4cac2d041fe5edcd95455d7eb894db28c9a49a6cbb047aea4eb503dd47e3cb73b4b2687440ff229fb7f5a776d32ef5636f89014afde3583d8d17b543b7c62df",
          "sha256": "d37343b9ab3a0667cc30a683221e578ed5860c33d2efdde121ae90b349298c6f",
          "sha1": "7c9ab7b7ff1405103166c14aaac20e8d550813c3",
          "md5": "78e9ae95a2b14507ee25d772ff154579"
        }
      ]
    }
  ]
}
