{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.6.1.klib",
          "size": 8131,
          "sha512": "18f0929f0e5456b0fe7483c50bba6af2cd7bbf4ec8e04bc04414a013cb87b50dc7484f2fa0338ffccb66d5952fe24631208ba175697eb2a1000e6343ff61df48",
          "sha256": "64266ddf066a14766f24032b242e4ddfd6555561e12c4385d7de22b0b68bc3b4",
          "sha1": "a43c99463c47267fa259a33dc03bf8ea8e398194",
          "md5": "ad50786e0838db01c1029f2e834cb613"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.6.1-metadata.jar",
          "url": "lib-tvosx64-0.6.1-metadata.jar",
          "size": 3976,
          "sha512": "132a817d7e0d72f63a1e35738737ae989eddccb1a073fc08105bb11a0f057764342ecd2b0f723a342c01001d48ab8303056d43aceb6949e1cec10aaea4c5e61d",
          "sha256": "ca40f75c2bf556a69ef863173a02e367656c92c673dcbc0ec3a1af823b263b43",
          "sha1": "6e61b2268cedc6266ef2f9113f6bc264265cf5b7",
          "md5": "eb9d8ff78e8acfeba6cca003fefb4939"
        }
      ]
    }
  ]
}
