{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.0/lib-coroutines-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm32-0.6.0.klib",
          "size": 4224,
          "sha512": "7b717fb7ab4548b434ed61e3adb4a45e634395a489e5182ece085e8823fe68468cd4f01123931c556ea7191b18c4daba1f75414b7bcf4ce352e99260cc56d2ab",
          "sha256": "c48497ff5ec272e18081fe70a118d5980227d3767c2c970e586422a756b02c62",
          "sha1": "c169d67be843d323dab6ce23b75a550dd27c2836",
          "md5": "818999fef6d8c30ebbc94f1b11e96e99"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm32-0.6.0-metadata.jar",
          "url": "lib-coroutines-watchosarm32-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "1fcdc5d614e84d4d099b4126d85fd0ac17f330a7fc084bf82d2b4a15f0ee4b33b9acf4ab562a13abf2ddd4bb7e41d7165b850dd04b72ec7c4a716376a4f075c4",
          "sha256": "801bf6062b239a27faa3b81e4e7f43211b0e0aff6a01f67bc5e9d128a03d69bd",
          "sha1": "11b55cfe9a249cc5591684ac4711260391247e23",
          "md5": "91adb4b5b3f7a77cea3011561cfb3ba7"
        }
      ]
    }
  ]
}
