{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.0/lib-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.6.0.klib",
          "size": 8148,
          "sha512": "4f84bc70acce73ad80b192bd28de0532a0cba7548317dbcfa34377137ce050b057864084310874a879f49eb45073d3f8194cfe6e07cbcf3855c650640623e2ef",
          "sha256": "bc0637721fea1eec0aff6d76567acaacc0d111b9decc06d27d617b14394c1580",
          "sha1": "f01508697b304f854f086939a0fc0f72afc801f0",
          "md5": "cd4aa99b6368f3839dc384b64826642b"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.6.0-metadata.jar",
          "url": "lib-tvosarm64-0.6.0-metadata.jar",
          "size": 3969,
          "sha512": "e8cecfde714c78ebffa2dbc4418716a3a4f8e3e743c9e51e69a73a692c0019e8d9878076aeeb8294db9833fd3b1cf44f44202bdfdd90e1f1182629426c099ae1",
          "sha256": "22cdeb619e46e472d87139d3babd406d253f2a22aa0289ddf009dd6f25259e82",
          "sha1": "6f396479548d982932bfbaaa6a0f2549b6635012",
          "md5": "03794661e0fc3224aff046e4c55ccc47"
        }
      ]
    }
  ]
}
