{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.0/lib-coroutines-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iossimulatorarm64-0.4.0.klib",
          "size": 4034,
          "sha512": "18f6b0e5806db3e432b2f71fc4463d0af38134f2df71b5819e886a86ec20fd2d6cf71d02866bb4e9575cc69ced2b87eb2423d2cf8ec693e002121e72e5be35d3",
          "sha256": "cc104d2696dccd676cd5977393181c1997e6509ecd50396511b61b50293994b0",
          "sha1": "1ca530aa920ca040e92e6986d54778efb1d0aaf0",
          "md5": "90cff7395a13295308a332fa22051070"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iossimulatorarm64-0.4.0-metadata.jar",
          "url": "lib-coroutines-iossimulatorarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "a6a7443cb87decb574afe40ac7fdf5c5d1e0d93b81de78e095ed7dd3a4190a63b19dd6e2f8cc7dede8812d2974575d52ec6c69015b26d6e672f6b81366f88977",
          "sha256": "be6620ee1218a707e0c922f236ffe5f499b5c6f9b94e180e025f54be1708a71b",
          "sha1": "fbd19734ae53a6ce2de72dd5b1616b78ecddcc53",
          "md5": "29d18f2789929e342005a193aa4835e0"
        }
      ]
    }
  ]
}
