{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.7.0/lib-coroutines-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm64-0.7.0.klib",
          "size": 4221,
          "sha512": "db61f355cb7ccfcd136fb81d5a5bc428b4f060757d3e724d456e67516885755536e53125cb96e608d2e556beee505d3aa299dd17e8c3edc6351812df4bb1d365",
          "sha256": "e3fba90869dcd67def3b8355b25744c559394462dd1fdbfcbb4fd8c905ab3851",
          "sha1": "9898ada3d1d0d1d71483abfb64a55ba23272f0fd",
          "md5": "e54c94700b4947f0de83bd3f559a5ce7"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm64-0.7.0-metadata.jar",
          "url": "lib-coroutines-watchosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "61c24a55ab4326025874716d833bbd7f60359642c4f25923fe983faa5dff1f77d90a0792288816d50644f6662fb898aa491026c6e346bbb7d5642f2dd0608066",
          "sha256": "f76f1517f924dfd9805600843342b8b6e9af15a291f7fe920762ec5a3272ed0e",
          "sha1": "6b45cce37bacbb425a1b1b90fbb348c3b1de610b",
          "md5": "71fad30cb330480b380497b7c855ab6f"
        }
      ]
    }
  ]
}
