{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.8.1.klib",
          "size": 4168,
          "sha512": "70daeea5e8e86133dc43c101d4420bc03cf27c6014348e0817d0289a4f9d1c22c0ee4297b27b37cfb31bb99770173cc88d32f8f573271c14dcd2bbfb4c2aece1",
          "sha256": "c18c12bbd55f54cd55fdf6fa357186eb28dac6995ce0857af4b0fcfd790bddb8",
          "sha1": "39bed6ac81c752cf1f54346867e1ef893f83ecca",
          "md5": "c8afff7da5925266fdc762a6ed604898"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.8.1-metadata.jar",
          "url": "lib-coroutines-iosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "2e1493a891792f2d6ef60b9e2e7f72561a51a0f4e835d799d8fe8bd41e8c1322d937a21d1234fef0bafa31039b476b8a36d4e02d9e769c8e9d577f18548a0d57",
          "sha256": "0476ea283ef56f26bce40e5c3913d4fa4197176e97041af85de869cfef24bfa0",
          "sha1": "1f2c22eb43917fd415e2276bde98fb2cdab3ab14",
          "md5": "87cfac8e9d78c8b324c91e21bd984149"
        }
      ]
    }
  ]
}
