{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvossimulatorarm64-0.6.1.klib",
          "size": 8234,
          "sha512": "0b7a65a60fc3bcad9e3400cd8d0b7a6258fa55c750e48946ca6976e3e97d3afecf3ffdd09cfd55c395487a418304aa66948deb1c03c5805acb316dc930b24d93",
          "sha256": "1f60db77570e59180ac19475a189f89d7a00179f0ef046470c80d2675315e7fd",
          "sha1": "02673e951bba829757b14cddfd36ef42c17bf2bf",
          "md5": "428a2c960d1048c28c90792972698b45"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvossimulatorarm64-0.6.1-metadata.jar",
          "url": "lib-tvossimulatorarm64-0.6.1-metadata.jar",
          "size": 3976,
          "sha512": "865551774a45b296484b5538a696504815c94609509afdb4b3013fb6950f0a8b8f0c893e7bb99c1d0bfd416679d56ef4dec51eee5f26636d4ae92f4708d18834",
          "sha256": "005a634c97fa3412758e18c6d84a924a954092efbc3640681a9ebbe413de380d",
          "sha1": "f446efc35447b1071ad4b6a8b65813940589f07d",
          "md5": "f0fcfaa0575c5145f8b261861b1a5fb2"
        }
      ]
    }
  ]
}
