{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.8.2.klib",
          "url": "lib-js-0.8.2.klib",
          "size": 5896,
          "sha512": "5f0a6755afe972ba3536f789c7405edff8e17aedcf0dacf4038c60c417c52b4efe483030ce682c9f2b12e440f50684a9528638b40c5a25996d5c54e5f4f09cfb",
          "sha256": "3156c72cb6dc977bc24922648da34643baa8ded16db12a23e23d01a218556389",
          "sha1": "54a3b494470e4a2129b16c3ebaa4c941046a7158",
          "md5": "c95165e45d0299a89dbf6ad4a4f4c20f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.8.2.klib",
          "url": "lib-js-0.8.2.klib",
          "size": 5896,
          "sha512": "5f0a6755afe972ba3536f789c7405edff8e17aedcf0dacf4038c60c417c52b4efe483030ce682c9f2b12e440f50684a9528638b40c5a25996d5c54e5f4f09cfb",
          "sha256": "3156c72cb6dc977bc24922648da34643baa8ded16db12a23e23d01a218556389",
          "sha1": "54a3b494470e4a2129b16c3ebaa4c941046a7158",
          "md5": "c95165e45d0299a89dbf6ad4a4f4c20f"
        }
      ]
    }
  ]
}
