{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.1.0.klib",
          "size": 14592,
          "sha512": "52eb7c62dee9032d798c9d635b7b3c6803fd2f6445a35c8ba0f5638f133431627d01ba1e647ba3669af03c45d7b20e09b119bc1d039d749999ac3a7abd6fd2da",
          "sha256": "0796f3bc37eac7d34a2594832b87ba43a742e1ff77908641ee0e0a563dd8763b",
          "sha1": "524b584735354cb7e31e4743044a34d67288f8bf",
          "md5": "fc09464b2139f92fa75b5b69a1bb03e2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.1.0-metadata.jar",
          "url": "lib-watchosarm32-0.1.0-metadata.jar",
          "size": 3750,
          "sha512": "387baf66eefd317d39f16103f82655279c0f9bc93609ef41f6b3707b85a97c8600cff7d0d9aba9485fd4b64a158fc92b6e0c3ede66be151fd51af803bc8bf45e",
          "sha256": "2ecfacd83ca825d10ab87a09bb9f2e48383587ef596303f8c30f9727d36ab7de",
          "sha1": "ac2a0a7ebe9fb9471d3e4572a04163b59fcc4e26",
          "md5": "165aa286205ddbb82dd03ffa51c58f19"
        }
      ]
    }
  ]
}
