{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.1.0.klib",
          "size": 14592,
          "sha512": "52eb7c62dee9032d798c9d635b7b3c6803fd2f6445a35c8ba0f5638f133431627d01ba1e647ba3669af03c45d7b20e09b119bc1d039d749999ac3a7abd6fd2da",
          "sha256": "0796f3bc37eac7d34a2594832b87ba43a742e1ff77908641ee0e0a563dd8763b",
          "sha1": "524b584735354cb7e31e4743044a34d67288f8bf",
          "md5": "fc09464b2139f92fa75b5b69a1bb03e2"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.1.0-metadata.jar",
          "url": "lib-watchosarm32-0.1.0-metadata.jar",
          "size": 3750,
          "sha512": "cda7ee1b69fe437600c65f66a64a8c72b5b4ca22cc7dedfec7bfb9b0f92573c4619dca1f861a64a63768bca50d1f14bd413a96cdeb869e13438795d0c96ab305",
          "sha256": "243ac507d7ad91e0bdfe9fd8963473a21ba922a24d89587cc333af9cdaf480ba",
          "sha1": "163f5a71d7cad12844d7769d9588ea94997b52ae",
          "md5": "15ddb566b786adab28cd53103b9901d5"
        }
      ]
    }
  ]
}
