{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.8.2.klib",
          "size": 6846,
          "sha512": "c8e2b543b573471c83b4305dacdb9f5176f5cf252c20a97cb4a2f437cbb66390bdd626f877cd36268fdc6102f471b1a124133ce25d932cef0a7067c024ed6cf4",
          "sha256": "2ec4ca8048d89f5faadf6ddec0e62be8f0399c2a9796e4af53dc2ea6f7b34064",
          "sha1": "9b44d707150bd3d7e8581a2767070d063ec7cd04",
          "md5": "7aaae32905b77dd12471ac54251ccfbc"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.8.2-metadata.jar",
          "url": "lib-watchosarm32-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "a5640fe36abd1edd4f464d6f2fb9fb5a28fe33b017771798ace7a7436efb75922595247cc3e01e99ada1601d971fe6eca9385819b92fe44731d7b5e3c9651eb9",
          "sha256": "f4560e1037e2b757794836cafbc181c50a9ae6aaa1d2b8db61e8ae1b4da61d56",
          "sha1": "d9af81e41cc5f590b5cad4376a417a0e29991e24",
          "md5": "4225999139397ed6f11d133efcb6f66d"
        }
      ]
    }
  ]
}
