{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvossimulatorarm64-0.8.2.klib",
          "size": 4280,
          "sha512": "3dcd31b552a13bbf5be541ba2e0369ac79da48d88a29b3184a667fa3ff96e8846e8a3d06147b0667daf43fd42b472c829cdbde9650086be7bfbe84b5ed6e938d",
          "sha256": "af1b08bf4e8e9abaf23b64ef1b278961abb7ec183ef005480053bc1b759a27f9",
          "sha1": "8be48abb85049a7028336beaff13246ffcccd41a",
          "md5": "12920b4d29c559f3f4a7b13d87cdfba5"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvossimulatorarm64-0.8.2-metadata.jar",
          "url": "lib-coroutines-tvossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "aedcfe7567db8c2b6169684caa3566d5de03019f8080e186760eea66f9d210f075567530f90f92c6295b9413a81710f4fc26ab19ecdce242aa86575837f20762",
          "sha256": "70399974e2eaf9d2705ad3194b82edcd7b33a13d3cdf7b84bf847879dd289689",
          "sha1": "ab5d5d3189bd65fb5621a2780dd650c48efe9e7c",
          "md5": "8e308c21177cd71ac59668ec11fc04c6"
        }
      ]
    }
  ]
}
