{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.1.2.klib",
          "size": 14783,
          "sha512": "c37a7df16a992e2931587c8f4597c1215d399d912738478b610cd8718c1f62c7178d035bf518af3b34665618958cdabbc30e2119153c6e06b0532aea92b7c595",
          "sha256": "aca346001fc1441445cf7632774e6b01c718eb34dc7f067e8b81bf3637c162a4",
          "sha1": "bbc66e6866ffa948c702674a90a6a43f0b54f9ea",
          "md5": "989072f4b6fc6f7f41b9a7c09a09c4c1"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.1.2-metadata.jar",
          "url": "lib-watchosx64-0.1.2-metadata.jar",
          "size": 3750,
          "sha512": "ac9e06b91e7cfdc371de598fce755ff27510fbdb83370a6868356ba002b86cae526e0f972639b1effe2abf1f13a15b84d59277e4761ec0ffbee081ddb82c4410",
          "sha256": "a80120c700e0d1b7f7ba5fd0ecb308171d62d7085c11a31e2de14a58068b9b5a",
          "sha1": "c254d7be389c106fd027a4616b348b131206006f",
          "md5": "c7a93b46d3adc43e3f893cca7867cb04"
        }
      ]
    }
  ]
}
