{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvossimulatorarm64-0.8.2.klib",
          "size": 6914,
          "sha512": "0d45749f049f6c04aba42ec7400f720d77af96b5b08bd51cc39bf16a4cdc2353f4f66dfa148329f4d344f52c38db2cd1a291ca038847c8056f1786bfea9a5487",
          "sha256": "d7060c89c5ff51b22eb806dd5e2d2a16ef7dec95b381d22253ca7aa05c5135f1",
          "sha1": "7d02781fd7d9d0a68bd4ecd110e430d22591f58b",
          "md5": "14bc322d6ad6fc71798b2d5f7a67bb7c"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvossimulatorarm64-0.8.2-metadata.jar",
          "url": "lib-tvossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "e80978b64de6300942ead3c1ae7550b2396e939b16a45e441be65d7e4bc90b1e837c14232a3f8696e05a16d4656c3a1af438f8d20f0f5c27b8d7b8c1ee556cb8",
          "sha256": "4cc3ecc7fc0e6a9440d226dd9bfa934192c59c88e8d7d63c0375ead5342247e5",
          "sha1": "23ff90f5fa00dfd50c033d604dc11d79e4a420bd",
          "md5": "e6271c16e5712039fe2a231ca2bc7697"
        }
      ]
    }
  ]
}
