{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvossimulatorarm64-0.8.2.klib",
          "size": 6907,
          "sha512": "997a7fa90cc1928045157964a4c29adb613ee37d90cc0844d9a774365fc7858c4031abfb6d4295b99b7d0879e2ddd8d8a6fc916f1585106e286217a06eb887ae",
          "sha256": "bbf87288a24a1256dec0a72830ddb98e5f145433da0f9545ce4cc1691828349e",
          "sha1": "a7d37f63f4a32fb6e499de5f3f81e8e4267000dd",
          "md5": "689760e03c18de8b8ba30bccd1fed876"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvossimulatorarm64-0.8.2-metadata.jar",
          "url": "lib-tvossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "724be7c47c93f09615edb7d65433c97aa8c0b040a878051b4585f813d5a4f2fb4bcfe459807af9d1b829b65d85d85a10b9e6c6fe5a561d6e5e621c28f025a05c",
          "sha256": "cbdf0baaafb9ef696c49a3327eeb3cdd7fed6bd4ab7cc5a17c2a94f215360f3e",
          "sha1": "4697c419a8b1fdd34a508195ba0d60720ae84a17",
          "md5": "bff12eeeedcbf0c92009faa5bded5b60"
        }
      ]
    }
  ]
}
