{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.3.0.klib",
          "size": 14861,
          "sha512": "ae9dce48d7b20baa95be2b81d38965170ba85ec9c44232625ffa8c2eafb38662ee6e2a2403b80e00a8c9031591f0ef6621b7bcbc89f869d1efea16dd8ede3873",
          "sha256": "93dc104c573223a8a6e27a0c56c6193910d113608204209c641013d8fde8121d",
          "sha1": "ec7b1047becdd3eaf852b17fd5364fce2eee5a0b",
          "md5": "c73218a52e4d8ec98cad29a3ef0924f4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "10fbd762a51e24e30390140289bfc77795f4d44df3cb9578e4a976ea97a6c520f0c41874105378553697b3610830cd5e363a51463723c146d1f4b9df1ecbd444",
          "sha256": "88d2ae1570c969f0f36deb634ffb7a5c4f1dc198906758122a2fef4829574914",
          "sha1": "e2c62ee684eb1cf34bce5172b48c40211ac5c447",
          "md5": "016b2319a4df9d7fc6ce330b3c5aac57"
        }
      ]
    }
  ]
}
