{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.7.0/lib-coroutines-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iossimulatorarm64-0.7.0.klib",
          "size": 4271,
          "sha512": "ae4bb9e815251c0fbf0926c072f969f7f03d37683fa810b84efac6dccc34a3aa2046f96a9b50ce4ebe120ff112478bb5111045311632e0fbd060e759d06ac58c",
          "sha256": "147b6e60bf5f74daaf7253018a97b40cecd159c7732edf9bbb323c10bab17fbb",
          "sha1": "710dfb1ebf9da728531a6e54a3f13dad19dc4317",
          "md5": "485efe694d77cc8be575311eacab00f9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "lib-coroutines-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "6d8927b9b2134ed36811cdddae0d4fbf2ff7b9fe83cd218122920751f3e4d4c73461f431e2ba4749b1e6a5588da875e701bc44ef002baeb1230b4c2da87faa3f",
          "sha256": "57a9e8067c863ff593fbf498bdf4079b88e52156044225d3a43875ccb461cb87",
          "sha1": "85d1c45952c27943e399588189773f3b838e67a4",
          "md5": "d5f3e2fb83634d6941b49b7ec58c51a3"
        }
      ]
    }
  ]
}
