{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.6.1.jar",
          "url": "compiler-0.6.1.jar",
          "size": 226216,
          "sha512": "dede579738c41026d4aa853b8fb06bccecf6daceb59d76c0bf169de39f182e992cef5af22d05164bdd263d7bc66f2ba39a61cba9b77e18c6cd3bcd1b8958937d",
          "sha256": "21db4f4b7ad136f74cfa934cd67690d0fe5fad88454931cce001dabf7d76fcdb",
          "sha1": "407ccd70d5855cce538cb6271a5ce85d99af2151",
          "md5": "25944c309b04f358b0caee23e3e110db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.21-1.0.5"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.6.1.jar",
          "url": "compiler-0.6.1.jar",
          "size": 226216,
          "sha512": "dede579738c41026d4aa853b8fb06bccecf6daceb59d76c0bf169de39f182e992cef5af22d05164bdd263d7bc66f2ba39a61cba9b77e18c6cd3bcd1b8958937d",
          "sha256": "21db4f4b7ad136f74cfa934cd67690d0fe5fad88454931cce001dabf7d76fcdb",
          "sha1": "407ccd70d5855cce538cb6271a5ce85d99af2151",
          "md5": "25944c309b04f358b0caee23e3e110db"
        }
      ]
    }
  ]
}
