{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.4.0.klib",
          "size": 14578,
          "sha512": "47cab87ba5c102a048804bc75a4886077a63657ad0b4f7f8f54ea38c74824e3e4df0362a06f4044ac99377e913df49bac9aaab442fdff7d1cbae57f25a2c57da",
          "sha256": "ef4ffb726aad52bf3f4d76d8918371f9e77817bcd7ccc353d34a67f82efedfa0",
          "sha1": "b7aadd80797a9310831a429819bd96e73d6fe113",
          "md5": "b2f14af1f151a294d3fe4389effbf822"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.4.0-metadata.jar",
          "url": "lib-iosarm64-0.4.0-metadata.jar",
          "size": 4558,
          "sha512": "35245b6bb98e6312e4425e5a8d31afcb13b26bc7c54e123801848f425595edd91c3316ad61f1f392697cb59f25f46d69fab2986be2cd2880e8f0f30fc896e1fb",
          "sha256": "cc343e4e7a7e4d220d880c59511a19069d4025c353568921500e5526311b30a9",
          "sha1": "e0665bb149c00db2ef2c399bcfcc727700389e49",
          "md5": "812d21e477d2984b24a01106fc918d2a"
        }
      ]
    }
  ]
}
