{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.3.1.klib",
          "size": 14592,
          "sha512": "23aa50d59f434dc10c77efd31e6f71a271fa433926ef7f55a84c23baf56c1ee1fb6f99abd7da4398cc8c8949dbce9ce0aa9861e86a5eda9d057685acab5022b5",
          "sha256": "edf9d8c71811d788cbd7a2f303fcee004ef09f3c82ee6610fc489585ef3df2ab",
          "sha1": "a8575bf22692eb76aa7e8d280dfe8f46482da2e6",
          "md5": "55a68ec9943e34a61c1907f5c0e8e806"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.3.1-metadata.jar",
          "url": "lib-watchosarm32-0.3.1-metadata.jar",
          "size": 3752,
          "sha512": "c69963f493c25676a79c5107fc97c49885b37187c349b2e940cbbedcebdc45db03a14ce9e16302cf4b41b7d30a60c46f986b9d157d4748eb0f9e760669607d41",
          "sha256": "64ba41fcae8c0f68d4dd464aeb3312992c28c0c2687e7597c3bdc7da18084503",
          "sha1": "010cefc3df6af8ccfaf1a07c2712d3b11b886772",
          "md5": "30fd9e6b697e817998ff130a42046a31"
        }
      ]
    }
  ]
}
