{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.3.1/lib-coroutines-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.3.1.klib",
          "size": 3931,
          "sha512": "f794c8d44aa2b1826633f7aa4335c8bfda6fca6d0eb71d04a470fe1a61c4685fca2eed572ad71f66d979267383883eed7c9d7cfb54a9c941095d360f8f802b5a",
          "sha256": "6acc1cea0420b0c4325ba7f6ac62de81505433f231a054bbef8f068cb4d24401",
          "sha1": "82a37bee9623701a4dfb2bd627e1c6f29aab87fe",
          "md5": "727a1a0d274668185803f1cdcc14e0bc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.3.1-metadata.jar",
          "url": "lib-coroutines-iosx64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "d859250890e7e1465fa8ced98453359213584064f23d1564c1df922f3e8b42fe5c03f7dacf28e952906b7e381a04b59129c183ad283ef4100994ffef77c0f1cc",
          "sha256": "64e6ccd1550b2e3dc90453d461116446e272c2886b65dcf9653b57710f15ccd4",
          "sha1": "6b39e2361e74d2e9d385c28fea6bb64aece0813e",
          "md5": "55dfdcc7d4ac83af6857a0064eef1fbd"
        }
      ]
    }
  ]
}
