{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.3.0.klib",
          "size": 14798,
          "sha512": "1db3a6207eb9c04f213ecdd4a47d58c9efd08b75d1a4b6e6f92bb5cbfbcdb11ab2b623a75d127aa33ed3484d6146158e842781953be1458eede821e2d4dc3637",
          "sha256": "5b3a685f309da56b18f4ab02d8e9b4bc3ea157b220f4b2980eb9b6735a0f4473",
          "sha1": "ee301ab40152f9c7f8abb72529a23bd9eb3d56bd",
          "md5": "5086dc7074172841050f809adcfcf23a"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.3.0-metadata.jar",
          "url": "lib-watchosarm64-0.3.0-metadata.jar",
          "size": 4126,
          "sha512": "6586ee8730e010897f7660e9cbc10af384476b38efa4e3ae62f613c5f605aa760cb2285280c0c8e844ee4e6e6bddd5a7a751cf20ca4f7a5a0eb32a788347228b",
          "sha256": "ad58e0d245376c0b5d223b1d377fbae45e039774d6dfb538f1b18087ae083c76",
          "sha1": "2f7565c6f071ed251ecfdb7263cf6d1b1700d185",
          "md5": "73ae0b096dbabfe93eb4aa449bc7ed23"
        }
      ]
    }
  ]
}
