{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.1.0.klib",
          "size": 14562,
          "sha512": "b2b7530b8468a13bcdbd3d16f6faae3139f958871ce54f6efa1b8096e9cf461a7ca4a0d0e0fb2f07dcba74ef78c8b4ba04ca60de2bf7917c7a9787e093ef3adb",
          "sha256": "bffc939e8b6dd258064c9feb1aa6a3178ba70f4a408c450d2bdec35469c7c3f5",
          "sha1": "1a5849b6ce99a16f8b0fdbbe34093a66f7a40ea8",
          "md5": "f9740c99c80f91793f78e7bb352a9c44"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.1.0-metadata.jar",
          "url": "lib-tvosarm64-0.1.0-metadata.jar",
          "size": 3608,
          "sha512": "36680adda65076ac6b0e7a98379d6019096ad9944347e7c50eb6891628d9a8ff8fce0e31f034d547893d2351eb8ecb44cbfbf8c483f1f800f5eb6db1c05f011c",
          "sha256": "32f3ee7ca0b83a4a609929254d33305e4ae53190f26adbacb30ab90f1dadc61a",
          "sha1": "601e50e4215e7f96ba03aa713d4d19d33da1eb42",
          "md5": "60c3f25559db07f7c3fca68fc3a632f5"
        }
      ]
    }
  ]
}
