{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.7.0/lib-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchossimulatorarm64-0.7.0.klib",
          "size": 8264,
          "sha512": "d06b0a41dd0b555cf388602786f4c6da9a12d84d4e50d20f5d0a65d4c018d77a004fc1bae1e1d8458d941e424ddad431b41fdde5091656594a9f668a20efb286",
          "sha256": "a80313f34d883e5494a90d12ac01ba1c34ca64769ee93cf845e9587f31366d38",
          "sha1": "331b7a16f2066c18b27c5f3f4da66cb60b298224",
          "md5": "29b51795b134dbb228f3cf5f69be6ab0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchossimulatorarm64-0.7.0-metadata.jar",
          "url": "lib-watchossimulatorarm64-0.7.0-metadata.jar",
          "size": 3852,
          "sha512": "812dfdd05c11738543359626d70a0de27b3863d0e0d9d7cf2b3b126e7bde4e4772dfa1b9f92a37b7850496f2a09288a1cafc66e5c9a5935043f817b84790e98b",
          "sha256": "dac5321024b438a51e3f11e0c347e43dad14032f9ebe512bd3c716805e38a256",
          "sha1": "1bc4a5e71ae40d8c277c55985f75b83ddb7abaa8",
          "md5": "74760e011c0313c10df8bfbaae0b3c67"
        }
      ]
    }
  ]
}
