{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-0.6.1.jar",
          "url": "lib-0.6.1.jar",
          "size": 3779,
          "sha512": "ac0678987b5eef98e260bb48a7caa3ae21e269e4194edfb7a564a6536b54a5319079dc121ad9f72760f453eaed453f6de07273d680b0426653fad80e4b91417e",
          "sha256": "a507968f74387e8d41a28baba273a867903baf8f073b217dcd8b085c023d24a2",
          "sha1": "d32586017d585664f036eb417fe828ef8aa53158",
          "md5": "d79eeeb2ed7a321bbbc8ec9abf331592"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.6.1/lib-iosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.6.1/lib-iosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.6.1/lib-iossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.6.1/lib-iossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.6.1/lib-iosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.6.1/lib-iosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.6.1/lib-js-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.6.1/lib-js-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.6.1/lib-jvm-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.6.1/lib-jvm-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.6.1/lib-tvosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.6.1/lib-tvosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvossimulatorarm64/0.6.1/lib-tvossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvossimulatorarm64/0.6.1/lib-tvossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.6.1/lib-tvosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.6.1/lib-tvosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.6.1/lib-watchosarm32-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.6.1/lib-watchosarm32-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.6.1/lib-watchosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.6.1/lib-watchosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchossimulatorarm64/0.6.1/lib-watchossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchossimulatorarm64/0.6.1/lib-watchossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.6.1/lib-watchosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.6.1/lib-watchosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.6.1"
      }
    }
  ]
}
