{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.4.0.klib",
          "size": 14573,
          "sha512": "158563604788a6aeeb84657ac98e3347d17100a11ca1966a2a5b53fad8beefae73e0f205fab1276b0873bfd42c5fa73373b98215893dce123074c6a2e15adb8f",
          "sha256": "b785b8adb5155752c69c68439e47da06d6164fc98e26f5b7e54b2806702a7ff4",
          "sha1": "7d4a88eb07e9c280157465e586d53c26b3a619fd",
          "md5": "fb2db37a184e70ec40d4b5adafc8e16d"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.4.0-metadata.jar",
          "url": "lib-tvosx64-0.4.0-metadata.jar",
          "size": 4263,
          "sha512": "5e2e6482682d9d266174605e426c6914eb43804aa1d5c4360877912669157593f2f4976321d3171bfea2fd6215f595b3dc73d5e8c1d01579fd12f9e77fd05c7c",
          "sha256": "beb06ef99ecdcc9bc7659933fb9223b868a4aa5beef6dc4cf005304265332f21",
          "sha1": "9e0caa78221c899f1f4aafcb7f0a16e83c183eec",
          "md5": "408b97e2ffceddac9d050d2ca4c855bb"
        }
      ]
    }
  ]
}
