{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.0/lib-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.6.0.klib",
          "size": 8238,
          "sha512": "b89353683e3b02d32f1e9c8934b0dbd5bd08f26379249b00f8a0bd72df3ab0a1496ca40fc0e7b6f8038211e62954f6adceea5e3e5926d9cd683b04df646be10d",
          "sha256": "a9ae69284b742ceb072a4b971673a1e86c4aaa7e5b00633f49253c49fb8dc788",
          "sha1": "174745db7f4032a410e87fe26e67c793c6bac9f8",
          "md5": "2befffb32ceb6ecc4b860f0552084bff"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.6.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "f6d4a201262b2a2576122fa47f4014e8cbed9a706e014a86c56e87f8d484038b7b74fcf2079afde6db2105c90e8bcbaf2ec96d2afe48100feb8671b054acc3de",
          "sha256": "bc7faeb64bb40b6bed6f60ff48359d371752298c5dd6150943ac07d93a8bad55",
          "sha1": "46850f23ded59510b8c36dbe68fa6c2e2441aa94",
          "md5": "ee633b4776df8379c1645389cc3f2835"
        }
      ]
    }
  ]
}
