{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.8.1.klib",
          "size": 6905,
          "sha512": "4ff2a0ade5fda550aa7ae12f4e25152654ad05945017e78c5ea316926587f669c584d0a94feca048152bd86dbffb81193ce0420796c3a81d40de395eb7417c1c",
          "sha256": "9ad8c469be19d3a2e96bfb69ddf3fe31938388f4a5915af57b5861e6015a7a39",
          "sha1": "b55725ce4b8eab8cc7401b266421aa19d36361b1",
          "md5": "dc6477b0108a118f71a9bde98647ba69"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-iossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f3dc7a2921f3ece1daea626484e21bbc3438b80b67dea90717b2e8ce1cdc48924d4791f5542e4ed27e3cabd41fac56f7f1423da3d71401d764271fd6e56af78a",
          "sha256": "59f4d7dded4fc235184e54dd4d2ec6c034fea2b1c9d8ae6cdc3a25deccb56a5d",
          "sha1": "16f455566fa157ffc21795503949dde3ceb32caf",
          "md5": "5a35a78817fbaee7d4e8feeef4ae73e1"
        }
      ]
    }
  ]
}
