{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.3-SNAPSHOT/lib-0.0.3-SNAPSHOT.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.0.3-SNAPSHOT.jar",
          "url": "lib-jvm-0.0.3-SNAPSHOT.jar",
          "size": 20713,
          "sha512": "d42ce4ab6fb16bc6fc0171065bf9556328428f34c80901960f0fac89da255cc644b31897012ce3ba24d47fca37ca08746461c27f3a747e686c69df4f2c0dcce9",
          "sha256": "2c8053986610e0182927957610fe37ac696866d8ee06028b6ca93269e2a41fbc",
          "sha1": "7ab41ae0651b9a6824e184718d3a6bcc8115b9a5",
          "md5": "1d72d9607e011d37c4befec014652ac4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.0.3-SNAPSHOT.jar",
          "url": "lib-jvm-0.0.3-SNAPSHOT.jar",
          "size": 20713,
          "sha512": "d42ce4ab6fb16bc6fc0171065bf9556328428f34c80901960f0fac89da255cc644b31897012ce3ba24d47fca37ca08746461c27f3a747e686c69df4f2c0dcce9",
          "sha256": "2c8053986610e0182927957610fe37ac696866d8ee06028b6ca93269e2a41fbc",
          "sha1": "7ab41ae0651b9a6824e184718d3a6bcc8115b9a5",
          "md5": "1d72d9607e011d37c4befec014652ac4"
        }
      ]
    }
  ]
}
