{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.8.2.klib",
          "size": 6820,
          "sha512": "19a6906390e1132fb7b2cb40abeffc57d2d2a2c0adcbb78fcc3824a25272c223c85eb5bf0975e916d457d98e04da2be907af13f2b90a5591baff6ad1423f628d",
          "sha256": "8324fe9a721b044225dd447301506a8ba0dd30c17b52050fb22f046f13577d70",
          "sha1": "8fd702a68956b44c174c5412f168176f7bb09225",
          "md5": "7ee57b26e14cb6f156e3ff1cd00bc4ac"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.8.2-metadata.jar",
          "url": "lib-tvosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "57dc68e882a3bd571b0016f03fc620e926678023a4da92201049fdfd9996b0d332e892b88846d8022e2f00b59bae3cc8de54fe0c692a6eb532511f7c2dad4290",
          "sha256": "502bb676dca4496f43519304c5cc58e72356b44494d3736b8c3a3114d6c29cc2",
          "sha1": "39d64c4953054d237acd3d60e5f14e0a307b39f8",
          "md5": "3a76aae4e6295a61344eebf3d727b173"
        }
      ]
    }
  ]
}
