{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.8.2.klib",
          "size": 6853,
          "sha512": "f7cd88a32676db6197e42cb04221837433a55e6dc08f1d4d2c74f7f59a7dea7b0c68c6dbdf6c712152b19ecd3ac88ae1eaa428efa962c3d2d3daef290f495849",
          "sha256": "a52c23af0464aaf8c56466afb1b845a884cc40c70e5c8472b80279753d4cc76e",
          "sha1": "803110bfcc5ea3d01a775c90bc8136df15d8736d",
          "md5": "dfccc7cab05b4de2f96ac9e701f3e612"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.8.2-metadata.jar",
          "url": "lib-watchosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "84521e1925ae419d1304cfb3284a2418f2ad4273a8133c84126f972cea147d35d80996cd8bc20db0b934530498292bf9f3da77bbf4a7702a6a6896676e1d0564",
          "sha256": "ce90996ffd9137cac7fbc306e36577173272e68f8ef86ff3e83916ea72329be6",
          "sha1": "a007a854c297ea3ed2d164ceefa0f5d87b8e9e4e",
          "md5": "3b24f4459a4f88e2ae18948719032485"
        }
      ]
    }
  ]
}
