{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.8.2.klib",
          "size": 6846,
          "sha512": "c7e64074f84ff95b3f9fcc3f20f790551cc44ca495c7145ab52d42351cdcec9b87a4f8aaf2b56a9b602c4a647aa18618fe0399a4ce5cde8a7b92511360f8d75a",
          "sha256": "5a4e358e10cac21e637811b6e5f110604eaea9aef072036516989319c7ca39b0",
          "sha1": "886f4f7a540dff5e35b413b2da7030bae2579590",
          "md5": "c1cd509c8c22a2bec7a7658583f9ac42"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.8.2-metadata.jar",
          "url": "lib-watchosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "db39f4417e3a46eacc8c70cf1365987d8dff4b0f2aadf341fa50f760555708ea6b65031eed9faecdc55b35f8535b1cfa18868f056bbe6e8428278097980d3e76",
          "sha256": "6568c000935592c496569cb05404ebadd19333b3c4252627a130be0310f13b68",
          "sha1": "201ab28bbc761b577e4d4377b386a17e54f477c0",
          "md5": "5df4a7214f798c04451f2c2ef7d2778e"
        }
      ]
    }
  ]
}
