{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.1.2.klib",
          "size": 14760,
          "sha512": "734b26b80ca61c37413f3217d7afa2a5b951b4058158272df381ed8ce2276b3226c0facb4170187fc11419c6732fe962d2e7482f2dae8273ca92799069b4b753",
          "sha256": "ea8932f17f6dfed09b52c1896f368e034a6f2a5e887e6d08e32af42049461d47",
          "sha1": "29dd0e53b985623f11e5117c6fe15204dc1dba6f",
          "md5": "8f005e41b47ba9102228d4cc5e9b5089"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.1.2-metadata.jar",
          "url": "lib-iosarm64-0.1.2-metadata.jar",
          "size": 3562,
          "sha512": "26b57b2ef09602fb3124b15a185250aba596ec977bcb91e0fe67e54eaa931b3fcf67e019d6a31547306b88410cd01e21bc82bbc0740278e1ee1f0f48ba382e5b",
          "sha256": "08db9279878e424590bb8fdef5b6e47ed3f3d059cf1668d82c6c68265c523e49",
          "sha1": "64003abfe1706d7b4218bcd50507dfa383e1eb05",
          "md5": "b72987665495c459847b01498c74e04a"
        }
      ]
    }
  ]
}
