{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.0/lib-coroutines-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosx64-0.6.0.klib",
          "size": 4207,
          "sha512": "98c745ded2f361b867edc522a6cea206194f3c5a256810c80fb5274e56d829544938447b7fd83f1fa7dc134429a5b61de7d421fd38e0b18edf6b73e8c58f7b21",
          "sha256": "99339620d64aeb98e9725c498e14cae3bbe8be0f68590a1c7b7c827d768b38f9",
          "sha1": "ea686967c5951a1e373484afe37ba5d4be0ad5f5",
          "md5": "3802637e037c9496b4443ac121568110"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosx64-0.6.0-metadata.jar",
          "url": "lib-coroutines-watchosx64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "1fcdc5d614e84d4d099b4126d85fd0ac17f330a7fc084bf82d2b4a15f0ee4b33b9acf4ab562a13abf2ddd4bb7e41d7165b850dd04b72ec7c4a716376a4f075c4",
          "sha256": "801bf6062b239a27faa3b81e4e7f43211b0e0aff6a01f67bc5e9d128a03d69bd",
          "sha1": "11b55cfe9a249cc5591684ac4711260391247e23",
          "md5": "91adb4b5b3f7a77cea3011561cfb3ba7"
        }
      ]
    }
  ]
}
