{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.4.1.klib",
          "size": 14683,
          "sha512": "b2cfe46437cbb538e946096bdae1032d4454dbf11d3991624e98037c430f06a0cf6631bf21bd4f4af7285f617a24d8ec19129da18cfbae6501fdf42e7ac91549",
          "sha256": "a2d415f3ae51ef5b81af034bb502f0932add434b7abbc3ee1ff6b293f7a373de",
          "sha1": "d377e55a5c45086a0b18e91de5c58c9338bc54ce",
          "md5": "5a2dbc0095b1c18b36354d07ee9c6b70"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.4.1-metadata.jar",
          "url": "lib-iossimulatorarm64-0.4.1-metadata.jar",
          "size": 261,
          "sha512": "57fb7bae60070d028762cd150157fd19380f056820fae1d93c9635af304d7414e7546434f9103a4a20f57a7b533239b97e0a096d20debeffcefae4bbbffc3bbb",
          "sha256": "ad5d76e003b4a238f7759a3b0ca31ab0c59e0bf90cca2d9bd1e532095d51e210",
          "sha1": "53d7cdebed339a6e58c7849d1a60890174406509",
          "md5": "63ee3a657fe8f003f870ad4c7321959b"
        }
      ]
    }
  ]
}
