{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.6.1.klib",
          "size": 8161,
          "sha512": "34177faf6021e8b38cd182b4779ca8deb1fb969f4a205b6310a21927dd1419a44931bdf94007f991171e0bf6e88346b16e36444d4bbea58bf382e9c4d4c077e8",
          "sha256": "b54a9c1fb69603840a4eafcc4e4d86071ef80c8dc65332888dbddd67e575d1c5",
          "sha1": "d04a2df3482f86353404e7b951f5ff50af212696",
          "md5": "4e2c5ab80c1cf68aacb0094a2eab4b17"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.6.1-metadata.jar",
          "url": "lib-watchosx64-0.6.1-metadata.jar",
          "size": 3852,
          "sha512": "a728a389119d6f0d52864aeed1c7f7cfe2dfed3864f89dce2c0dc43a7b2dd48a1e2eacc22e6338f7e1c51eeb07b873f6a6273bcf517931eb12d832df184b6fea",
          "sha256": "c73da8b87526f357557c02887981d6112b04928cc88c43375406f5b2d1e3b3eb",
          "sha1": "bfe1d6d77f6b84b2eff2b2a5d9f8630ce7281597",
          "md5": "9d9060ced95c9fd2c8afea300524a132"
        }
      ]
    }
  ]
}
