{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.1.0.jar",
          "url": "compiler-0.1.0.jar",
          "size": 205340,
          "sha512": "2def97625d901f113c487cdc660901ace8fc3b4731c4509712035f8911a88f2f3eada3e443fb41dd0643ee0750f4fb7c53ef14dcc85739ec6d7d09d605285105",
          "sha256": "c65844120af9f37ab94b02dfb5b498a44cd1f4b784db8efa8bd0c3c4421556ec",
          "sha1": "0c593440aecb3eaa0c438306c2a862d189cfaec4",
          "md5": "ab50fd352d945239cbb95ac9df0a7f3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.1.0.jar",
          "url": "compiler-0.1.0.jar",
          "size": 205340,
          "sha512": "2def97625d901f113c487cdc660901ace8fc3b4731c4509712035f8911a88f2f3eada3e443fb41dd0643ee0750f4fb7c53ef14dcc85739ec6d7d09d605285105",
          "sha256": "c65844120af9f37ab94b02dfb5b498a44cd1f4b784db8efa8bd0c3c4421556ec",
          "sha1": "0c593440aecb3eaa0c438306c2a862d189cfaec4",
          "md5": "ab50fd352d945239cbb95ac9df0a7f3e"
        }
      ]
    }
  ]
}
