{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "samples",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "samples-metadata-0.4.2-all.jar",
          "url": "samples-0.4.2-all.jar",
          "size": 672,
          "sha512": "def47c5612c1a14509a88bbdb543db08cf344af1e694fca9ab4bba6cb39a9d8c59e4d7c39acf3397125cc7338de719b2aee7a05fb83cff694d0ac8dfa94f7dc9",
          "sha256": "782e8d48f09cfca4db1bd9457429ffb07575c3f26653c8ccef0290c0bc0f10a2",
          "sha1": "010c6d9189532db1c0ffbb30460e13a2476ee6e8",
          "md5": "b1cb85fd1a5336f532668d1b9f78967d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "samples-0.4.2.jar",
          "url": "samples-0.4.2.jar",
          "size": 22373,
          "sha512": "d729c390730e81dbb88bb6f2d23404858adabb8990e1defc70dc876f36b0468237d5bc740746f74889b567b5897778ba67a3052b8ab453aca5b9b02925995f29",
          "sha256": "92b0d38d309f5a019640e5bc94e1530e3040ad0897444b236cfd9d617f1fdf7e",
          "sha1": "9add3792357f69e51756f258bfb0a72673bc3d54",
          "md5": "1325003e341f5018839362ee76e19cc7"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../samples-js/0.4.2/samples-js-0.4.2.module",
        "group": "deezer.kustomexport",
        "module": "samples-js",
        "version": "0.4.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../samples-js/0.4.2/samples-js-0.4.2.module",
        "group": "deezer.kustomexport",
        "module": "samples-js",
        "version": "0.4.2"
      }
    }
  ]
}
