{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosx64-0.8.2.klib",
          "size": 4207,
          "sha512": "78835a230de3d6bd3e40963aff77c912286a601d75f2b6059fa731169421d4d145ef89f786a7fe8f64a0794e41bd5deb272da3195dbd1a552d56e77cdf00d3eb",
          "sha256": "45a5ece7ffcb0b7d3967379195c36c94d511a782108295f54799e9c4ccbd9881",
          "sha1": "b144bd36c709eadb8b6e53a17fc43a106f53ac93",
          "md5": "2fd32a92363ae4166483348aecab7ae4"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosx64-0.8.2-metadata.jar",
          "url": "lib-coroutines-watchosx64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "31f56205163363c6dc963923cc1a1d7a2fdf54b43abb83ae1dc425cc8820575a51911a5e1e2fc9638b64aabb6f28ea956cff361daee187d59fc4e9d7cfd2e7e2",
          "sha256": "937a1fce44f6763a089c40f41f736f02288541d70e9afc8cba5e7f7b7e3541e9",
          "sha1": "c3217598e5e9c342d9a9cb822791a9eb1e5c0397",
          "md5": "606eec209fc1ef63fd9434e4bc96d01c"
        }
      ]
    }
  ]
}
