{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.1.0.klib",
          "size": 14550,
          "sha512": "0b283551457ced63dcf151790c7773839553758197aa73488df2f2a3209bd6fb01046d997589eef6fe963bf679b671f1875837166e3719032bb5b60af1dd645b",
          "sha256": "711987ac38446a34d8bc0ad9cf8affb55d56eb0126754edfcf7f5cc9c584309d",
          "sha1": "c3244854c7ad87faa7f61bf137c37d29045838c0",
          "md5": "f05025b53d68e54df5942927b948d8af"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.1.0-metadata.jar",
          "url": "lib-iosarm64-0.1.0-metadata.jar",
          "size": 3562,
          "sha512": "a77db4e04e783750a9fa6f4c0272caac9d36413308d8591971b29bcefcaed6101f6b013c7f180bf5e595e1e3fe546ede23fea538160e1338119b88c526a3a21f",
          "sha256": "758b1ee56317bd99af9f925772db536c97d49152137d4f375a0cbfa65219c17e",
          "sha1": "3c7f5931925b14bd668493f4e68801322c49bfb1",
          "md5": "cb6e1373eb9bc4fbcd97cf066394e51d"
        }
      ]
    }
  ]
}
