{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.3-SNAPSHOT/lib-0.0.3-SNAPSHOT.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.0.3-SNAPSHOT.klib",
          "size": 14545,
          "sha512": "c069f367b16c180f64018f87ee0afbb28843195c311d4fea925fa4b45cbdffdc21edb509031ff42c08f89f9f04cbd7d3492fbf069e3edcb4c1d8ca9abc66e010",
          "sha256": "3ff37f75c618b6117dbaa4580cb6977d42254d17fc1a23ffcad800e176ad9bbf",
          "sha1": "95a775d52432f9ca9633c6c88214196040f07ec9",
          "md5": "264ccb76aca770c754e9e40eb82ff71b"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.0.3-SNAPSHOT-metadata.jar",
          "url": "lib-tvosx64-0.0.3-SNAPSHOT-metadata.jar",
          "size": 3608,
          "sha512": "f4d8c9deaee74c98a9886ab45084337348ab6509b673e81f3d944d41fc2e6db33b14697ce8f38e4cf6c0396102472f04d68a357c84c24370f095b42b13f4401f",
          "sha256": "768ab4f5cffb1499d66d443ddbf90f62f077631dfa3339ad370bdb42c1a6cb33",
          "sha1": "8b0204727e65c1c429dde6a85d5d542fc6279896",
          "md5": "15fcc977bf75a4845fb3fc8f82b1f8df"
        }
      ]
    }
  ]
}
