{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.1.jar",
          "url": "compiler-0.8.1.jar",
          "size": 224271,
          "sha512": "448c3558bd9f58353dd51ec970c57aa4e7bd0c25db934bfcf25f746c3982c697bc21ef5f14dc21f163a4665d08b30abe2686aa5c8f9997d3f161447f661513cb",
          "sha256": "c12116647a7fe28ba5e827980049a815b833acaa33335b8035db5e4e2713fa80",
          "sha1": "3410b1371714932fddcea00e802c12809ae2dedc",
          "md5": "165762c8c3fe57fac28f92c27d966054"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.1.jar",
          "url": "compiler-0.8.1.jar",
          "size": 224271,
          "sha512": "448c3558bd9f58353dd51ec970c57aa4e7bd0c25db934bfcf25f746c3982c697bc21ef5f14dc21f163a4665d08b30abe2686aa5c8f9997d3f161447f661513cb",
          "sha256": "c12116647a7fe28ba5e827980049a815b833acaa33335b8035db5e4e2713fa80",
          "sha1": "3410b1371714932fddcea00e802c12809ae2dedc",
          "md5": "165762c8c3fe57fac28f92c27d966054"
        }
      ]
    }
  ]
}
