{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.1.jar",
          "url": "compiler-0.8.1.jar",
          "size": 224271,
          "sha512": "e28c2b94950536967a065fa663c19d2a8a18fd65fe4288375b86455f784897f512136bd98966a5e7c6e19bccda41b74c15ff0e2ef10636475a95454e507795c5",
          "sha256": "b6df4ba21c64c1bd34a4cf4cd2094c2817e189d3fddc16e954df09b958555584",
          "sha1": "ddf0c39e1567ba910857344781cf4e40668a314d",
          "md5": "c0d1b3d0d332912dc90b1d2e6b8157f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.1.jar",
          "url": "compiler-0.8.1.jar",
          "size": 224271,
          "sha512": "e28c2b94950536967a065fa663c19d2a8a18fd65fe4288375b86455f784897f512136bd98966a5e7c6e19bccda41b74c15ff0e2ef10636475a95454e507795c5",
          "sha256": "b6df4ba21c64c1bd34a4cf4cd2094c2817e189d3fddc16e954df09b958555584",
          "sha1": "ddf0c39e1567ba910857344781cf4e40668a314d",
          "md5": "c0d1b3d0d332912dc90b1d2e6b8157f8"
        }
      ]
    }
  ]
}
