{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm64-0.8.1.klib",
          "size": 4221,
          "sha512": "db61f355cb7ccfcd136fb81d5a5bc428b4f060757d3e724d456e67516885755536e53125cb96e608d2e556beee505d3aa299dd17e8c3edc6351812df4bb1d365",
          "sha256": "e3fba90869dcd67def3b8355b25744c559394462dd1fdbfcbb4fd8c905ab3851",
          "sha1": "9898ada3d1d0d1d71483abfb64a55ba23272f0fd",
          "md5": "e54c94700b4947f0de83bd3f559a5ce7"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-watchosarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f6a540627fd9de90eb6d946cd72f7393260b82c29d4104ebdd73b02a3ffde18d8f6a6f75725291018f01f8425b23f1779c86fb7728452914c7baf3a2cf6ea129",
          "sha256": "98b630564b15610f535d4f52580a80fc87fbaf355dcf65259d6ec95f275a2957",
          "sha1": "4a2d7dc7fa4f6f771a0505a331724f24c4964d59",
          "md5": "18a236c36c528c6302e87fe6977a0b1c"
        }
      ]
    }
  ]
}
