{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.0.jar",
          "url": "lib-jvm-0.3.0.jar",
          "size": 20607,
          "sha512": "96236d7af9479d91177ddf592cc66140d863b7e58c581b0db562e32a087053931b98f57127299a1bb4e31c9dd180552a17af374dbb59c3a08b61b05ff61c4685",
          "sha256": "25ac5e6a7f94bddb7820a13e203b0fac39e44e83dfc8a2507693bee9e8ef16d2",
          "sha1": "142d4445992512c5a2511cd641f81674c4710fcf",
          "md5": "9fd1e7c5ba057908f4932aee01f3ff73"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.0.jar",
          "url": "lib-jvm-0.3.0.jar",
          "size": 20607,
          "sha512": "96236d7af9479d91177ddf592cc66140d863b7e58c581b0db562e32a087053931b98f57127299a1bb4e31c9dd180552a17af374dbb59c3a08b61b05ff61c4685",
          "sha256": "25ac5e6a7f94bddb7820a13e203b0fac39e44e83dfc8a2507693bee9e8ef16d2",
          "sha1": "142d4445992512c5a2511cd641f81674c4710fcf",
          "md5": "9fd1e7c5ba057908f4932aee01f3ff73"
        }
      ]
    }
  ]
}
