{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.8.2.klib",
          "size": 6898,
          "sha512": "0d6a0d5ad6a78e29f58be898d3a6a2e90d0c341b5edb6c1fbe29837d1f50e3d44a91a367c1d93bbb29a7ece4c14ef60ea7afba740f69bc1c4fae04497cab0780",
          "sha256": "d24360784990423a582de81dee1224e9afdceaa4cd4d4056a80c07e8de5732eb",
          "sha1": "c7290fdd035b134c20cc1e512751740a4b0e677d",
          "md5": "b24cf5ed8225484c61af6ad2ee8aa341"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.8.2-metadata.jar",
          "url": "lib-iossimulatorarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "e88f0e963914bf2ba665937b8e4025b2ba0af7fe6e9622f7ca9a989fe305c7f853c3585e009f71e0ae69c6057f8a62667f783a87576ac052250a8123d98f7235",
          "sha256": "a6814fb92576062aa529a47d00481206ef66014dfedb2ce89d92bfa534b21213",
          "sha1": "2d13d5150f75d735fc6da8ca3d953f076c8aac4d",
          "md5": "cb6d18784cbb4ecd3dbfc4dd46249e2f"
        }
      ]
    }
  ]
}
