{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-metadata-0.6.1.jar",
          "url": "lib-coroutines-0.6.1.jar",
          "size": 2220,
          "sha512": "7c437112701f757d3fc9573484b45b126cd76e3eceef15be4cf63ae60f8361624668fad6f72eebe84d7cbdb82459c35da9d575c1256f9d92a289ee3e9d96a9cd",
          "sha256": "a31f4596656498779166b0c74b5a9ada7a50b0ba598732e536f66947986db5a0",
          "sha1": "88e40ed1668e0b9d9724ee35c4fcffc8d0a4613b",
          "md5": "8a819fbc9587dc69008a146ffbc00447"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosarm64/0.6.1/lib-coroutines-iosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosarm64/0.6.1/lib-coroutines-iosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iossimulatorarm64/0.6.1/lib-coroutines-iossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iossimulatorarm64/0.6.1/lib-coroutines-iossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosx64/0.6.1/lib-coroutines-iosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosx64/0.6.1/lib-coroutines-iosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-coroutines-js/0.6.1/lib-coroutines-js-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-coroutines-js/0.6.1/lib-coroutines-js-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-coroutines-jvm/0.6.1/lib-coroutines-jvm-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-coroutines-jvm/0.6.1/lib-coroutines-jvm-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosarm64/0.6.1/lib-coroutines-tvosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosarm64/0.6.1/lib-coroutines-tvosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvossimulatorarm64/0.6.1/lib-coroutines-tvossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvossimulatorarm64/0.6.1/lib-coroutines-tvossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosx64/0.6.1/lib-coroutines-tvosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosx64/0.6.1/lib-coroutines-tvosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm32/0.6.1/lib-coroutines-watchosarm32-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm32/0.6.1/lib-coroutines-watchosarm32-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm32",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm64/0.6.1/lib-coroutines-watchosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm64/0.6.1/lib-coroutines-watchosarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchossimulatorarm64/0.6.1/lib-coroutines-watchossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchossimulatorarm64/0.6.1/lib-coroutines-watchossimulatorarm64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchossimulatorarm64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosx64/0.6.1/lib-coroutines-watchosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosx64",
        "version": "0.6.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosx64/0.6.1/lib-coroutines-watchosx64-0.6.1.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosx64",
        "version": "0.6.1"
      }
    }
  ]
}
