{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.3.0.klib",
          "size": 14770,
          "sha512": "32809a512534e4b473db506e54626f501303f26f47e2080542636b57ee23003b54046f880bfc17afc21c98a15757b68a9134b1f29c261cd25f8d3a4df1d22443",
          "sha256": "a70dcaf02a133ae31b0768a71cef99c73c9aa36b28495835692cd532946e78c3",
          "sha1": "cadd955a4be1fc85a1d2f2d56ea7ead30404ca76",
          "md5": "af36e81492e68094e514e23ac2e3b117"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.3.0-metadata.jar",
          "url": "lib-tvosarm64-0.3.0-metadata.jar",
          "size": 4265,
          "sha512": "7f50508f731308799a458a5b0f094c944e71249cf22a073c71e943fc2fa820ffe8ba8ba2d323a5578ff77fc2d579b7dee02658f3495b9d7a2777c06a2a5f97b4",
          "sha256": "0f3cc84eaba989c38c4cd5f4f1f8ebccc9b78c923aa2ab5f8a7df36a99e1a6bf",
          "sha1": "200cf2bcaf843357f311ca2ab1ff6f21d1ab732c",
          "md5": "8afe82d9bb107c8c3308e9a20087b1cd"
        }
      ]
    }
  ]
}
