{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchossimulatorarm64-0.8.1.klib",
          "size": 6933,
          "sha512": "c6b4bf7260fb5c348dcf3251a76a17a70658ea6cac972b5774c2e82108f41961243cfa2e561a158dae1f175f7462686385f06da0e94d42147719b7d81d17d2ef",
          "sha256": "89e068a4826f63c6ea93c4bffb47edbd86a2388ea6ef20a7e0c31254b97321a1",
          "sha1": "a407c9830fa35e73e39f499358116dbcfc832705",
          "md5": "14151e5deb027ba92ec2540e95bc51bd"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-watchossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "9b313d0b26c8389f1886201a61ada38d74fed0d12f466a2a45146f9285f5709a865112f9a80cf3d7294e45172db43e4b8c121f51289794e59f38b3658b52809d",
          "sha256": "f080ac5153a801188886d60ce89ce83d4e2001b9dde3c8f41f10da20382b16ea",
          "sha1": "64cda9d7edfc76e65d769d03ffabf2372ad6a2d8",
          "md5": "1b4cf8bd721487cd6c7f7b965c8e8eb6"
        }
      ]
    }
  ]
}
