{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchossimulatorarm64-0.8.1.klib",
          "size": 6940,
          "sha512": "095df3c4f927ff940cbd2cbb4b7a214351db938c99238a3c249d2c427b1b05fa65caf877baec99f223a3995a4e084f5f5d2d15c9e2ba5216bcfeacbf31ff0cf0",
          "sha256": "771498355e4f031bd412a71605d8851bae4708a7eb39a50bac6e585124bee49a",
          "sha1": "fb3820f0937fc9924c07f6aa927cb98e688336f6",
          "md5": "eb74bcacddccb0b80d314324fe7bc0bb"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-watchossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "423e49116a634e8aaa867de91a06912e4b61d154c5f037e1f2916a11424770e76a2c43a6b4b1c73e7b16a4e146a19bbdf2bbbed3dafb42d7284e01fbf7b3a3c8",
          "sha256": "0132130f8ade1e3a99b62e8574d23b7d183e8fc37953495599049cbe388bbd90",
          "sha1": "0665cd0f2292f88f5d74b52c01b7c98bf900b433",
          "md5": "aeccf2fbd22fb8aaab8e971985631e63"
        }
      ]
    }
  ]
}
