{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.1/lib-0.1.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.1.1.klib",
          "size": 14863,
          "sha512": "73629939336775ac4e0f2a104a4a9fc5c52b6d3a4effdb0129cb3f4dc0d987481be96e779b74fa179f3673f43d8d824f5f900be56805a5e22ee50f6c61e5e12f",
          "sha256": "65397ada145ea8de3ebded3ba9005754b2a16cf98ce0dd42f9dba9f5c71f6f74",
          "sha1": "2cc7ecdba221f30c2280393a9805ef7ba7170cd0",
          "md5": "9a1f439f71f60358356933403b55cf96"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.1.1-metadata.jar",
          "url": "lib-iossimulatorarm64-0.1.1-metadata.jar",
          "size": 261,
          "sha512": "826126808c992dc6bf7d89cbf9887f5bfe414b0999f364b03d651934de95cc746d976cffa1b7d8c2e2d64a719c7f06b73ef98ac77e7df4918b91890870d94246",
          "sha256": "66c3a66311009f76ee72f4e154a3b9fa3f162765e1a7a021f5473ef3549285e4",
          "sha1": "f4d8a4ad5995d9c159d4fd3bcb07d4ad624a42eb",
          "md5": "d3cde433a6b5018e3a11b7b50815e054"
        }
      ]
    }
  ]
}
