{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.0/lib-0.5.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.5.0.klib",
          "size": 8489,
          "sha512": "7417538132d459620212142619aa36d5e8d2b047b71cfba70776ac5ab45bbcad1c0ca5d04950323a84c5df1158ad2bcfd98e4cc527dbdaf5205867991148fe80",
          "sha256": "b9d160ecea945ce9f321910366ecf3d9d456a672f9b32ad49fa26a2869586379",
          "sha1": "4accd23c5dd1c889a5608a3016026f509acab260",
          "md5": "8144a5ca396adaecd3d4af6170bb3bbe"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.5.0-metadata.jar",
          "url": "lib-watchosx64-0.5.0-metadata.jar",
          "size": 3785,
          "sha512": "5fb607aa83fd20693d90f4babeb665e69096ae3f5cf7dc65ab188bcd6f9f63ebb439b76c327c250e4a980255c23a48baa2780ea096088ffb558577c69cc7c2b7",
          "sha256": "35e048b262b2e548303ad66ed9cf5d20eabc8f55f648ce3bf7a4430625f1bb82",
          "sha1": "b2128b57d0e0624ff15b8f49b3aac6d6cd253a90",
          "md5": "668d1f7a271fcebab5e268053139d968"
        }
      ]
    }
  ]
}
