{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.2.0/lib-0.2.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.2.0.klib",
          "size": 14758,
          "sha512": "96af1a1c5b56a45f292bb317f4a7a865ce637c52c8bae668017fe536cfad5116035423dcd7c573662e324d4c172bb6aaf685939905c54c8886f0ecaa207355ec",
          "sha256": "1ef1532c1e4cb5a7a12522ee327af0434ff5b0a7b471719f7ca7cf128c7d2edd",
          "sha1": "0b753082f2701fa223dd3ba7cdf29368a64d3cbb",
          "md5": "20f8cae1c562521ff4b594afea9bcc1c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.2.0-metadata.jar",
          "url": "lib-iosarm64-0.2.0-metadata.jar",
          "size": 4558,
          "sha512": "bf4470b5514a7e9fecd3cb8104a67116fa77b2d51fcaf3b1287a80bc8cc8c0c45f1d72ce4a6ee713fcf8a22473055939cbda2959df1bb7f77970d9174ea2188d",
          "sha256": "9951cd1870cdb015516e90ad9865437bb6292c0c97520634cc98c5f45f9923e7",
          "sha1": "b8ff86efa72c4a3bb7ff4d901d78e6f51243e41e",
          "md5": "b4fcfd36b8d4c7d743aa711299981bd3"
        }
      ]
    }
  ]
}
