{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.3.0.klib",
          "size": 14758,
          "sha512": "96af1a1c5b56a45f292bb317f4a7a865ce637c52c8bae668017fe536cfad5116035423dcd7c573662e324d4c172bb6aaf685939905c54c8886f0ecaa207355ec",
          "sha256": "1ef1532c1e4cb5a7a12522ee327af0434ff5b0a7b471719f7ca7cf128c7d2edd",
          "sha1": "0b753082f2701fa223dd3ba7cdf29368a64d3cbb",
          "md5": "20f8cae1c562521ff4b594afea9bcc1c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.3.0-metadata.jar",
          "url": "lib-iosarm64-0.3.0-metadata.jar",
          "size": 4558,
          "sha512": "ac619c57e53a3c15d4314ff0dee2068731cd98e84b0649aa31f2e635c62d3ed22e7e94b55ea11863c67e8af5c282266296a75f5abf4609ccf36ee2928bfa0571",
          "sha256": "03501b74a4fb735e9737c059666a86f7967fc8b68e2a37eff6c1d547424e5980",
          "sha1": "68678b38e970bf0c3af2ab345b16a0397f4601bf",
          "md5": "c95358e524ee2b71fe366fe1077a223c"
        }
      ]
    }
  ]
}
