{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.1.2.klib",
          "size": 14800,
          "sha512": "341e777726c3219d6345abf42569b7f3b8db8e5a003358895097eba54095af2e5b9014ad74b6ee574241b72c377e73af63e7cc0d8beec3f532e5870ed1929ffa",
          "sha256": "724df6c05eaed86a8889fe38d1816c33aa4be7059678a30d646d1a12a9c18ad0",
          "sha1": "8dc0dac12e5418c3e685a6e99a872d751c17511e",
          "md5": "64ace19f4e38fb2ed2df568cef7c20de"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.1.2-metadata.jar",
          "url": "lib-watchosarm64-0.1.2-metadata.jar",
          "size": 3750,
          "sha512": "ac9e06b91e7cfdc371de598fce755ff27510fbdb83370a6868356ba002b86cae526e0f972639b1effe2abf1f13a15b84d59277e4761ec0ffbee081ddb82c4410",
          "sha256": "a80120c700e0d1b7f7ba5fd0ecb308171d62d7085c11a31e2de14a58068b9b5a",
          "sha1": "c254d7be389c106fd027a4616b348b131206006f",
          "md5": "c7a93b46d3adc43e3f893cca7867cb04"
        }
      ]
    }
  ]
}
