{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.3.1/lib-coroutines-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosx64-0.3.1.klib",
          "size": 3940,
          "sha512": "4759326a642560fc33600cb968484aa5611e8361b1578f2aa60a840c9becdd020bd51569b2d3065a585159e3d340ac94c64958284a61269bcd610dad74be298d",
          "sha256": "2492635f5d79b00fff90640e0f9c1fd3f09dfd80ab86c382df807a3f590216fd",
          "sha1": "c136bb125f42f2bc57d35d29b14ab15de0c83d8a",
          "md5": "ee80a3bf77f56e3b6b88daae71cc2f23"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosx64-0.3.1-metadata.jar",
          "url": "lib-coroutines-tvosx64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "d859250890e7e1465fa8ced98453359213584064f23d1564c1df922f3e8b42fe5c03f7dacf28e952906b7e381a04b59129c183ad283ef4100994ffef77c0f1cc",
          "sha256": "64e6ccd1550b2e3dc90453d461116446e272c2886b65dcf9653b57710f15ccd4",
          "sha1": "6b39e2361e74d2e9d385c28fea6bb64aece0813e",
          "md5": "55dfdcc7d4ac83af6857a0064eef1fbd"
        }
      ]
    }
  ]
}
