{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.0.jar",
          "url": "compiler-0.8.0.jar",
          "size": 224272,
          "sha512": "26f5e60da76f2d83fdabcadfae2c392e7d1ca62befd717f314d4ad99bbe68a60fe16510d8c046df715107472844409785ac9cd2ef6d6236c3bb9d6c3ce5d4302",
          "sha256": "12cce89de39e3fb8e51ae8b38eff4c89e650311007a6e9ee6ff246cd8f69693b",
          "sha1": "c8d88e379f6f3648a02bcabeea05a9630f12f2fd",
          "md5": "08086dd28dd0a8f2b01c28e1cdfb668f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.8.0.jar",
          "url": "compiler-0.8.0.jar",
          "size": 224272,
          "sha512": "26f5e60da76f2d83fdabcadfae2c392e7d1ca62befd717f314d4ad99bbe68a60fe16510d8c046df715107472844409785ac9cd2ef6d6236c3bb9d6c3ce5d4302",
          "sha256": "12cce89de39e3fb8e51ae8b38eff4c89e650311007a6e9ee6ff246cd8f69693b",
          "sha1": "c8d88e379f6f3648a02bcabeea05a9630f12f2fd",
          "md5": "08086dd28dd0a8f2b01c28e1cdfb668f"
        }
      ]
    }
  ]
}
