{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.2/lib-coroutines-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosx64-0.4.2.klib",
          "size": 7356,
          "sha512": "3ede8948c087c77e8e7fab611eebc4be75752137ade8771f5c942f330b7d0cd1cfad319803a40eefd698de50968bb989327d2d4e97b3ce7a799345227643f009",
          "sha256": "4223b20431a24f9d4a98a9e45bd4388b1940088e22e6212137cc00abfe56dcf6",
          "sha1": "2961ef50d6c85a47732c7f5b597ebb87428d92ff",
          "md5": "6f6f5e68667dff2fe7a5aeaae51b4d49"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosx64-0.4.2-metadata.jar",
          "url": "lib-coroutines-watchosx64-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "afa14ecb224036e72bf678054b377821af628c7e9d01863e4f43dcad27ac07e0f5dc3d3f6363a240acbb43e60d5c0ff4e75e30047d339871b63f78059d98abda",
          "sha256": "e83a57e3c614717279c6f3e5449b4d3ae80a21a736c12ef2245ae671ba693ddb",
          "sha1": "80d752056b2637c5328757d089aabc00a38b5319",
          "md5": "2b5a23245f52a15de4d298245dac54c0"
        }
      ]
    }
  ]
}
