{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.7.0/lib-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.7.0.jar",
          "url": "lib-jvm-0.7.0.jar",
          "size": 4310,
          "sha512": "53b24938203a8fa16788790e9a233f2f2d6b8a0877b9a3dd65c9f84ebd212e942fe28569780235df2c0366e3f857ca14de7c9b3ca971ca2ecdebcb4afa20204f",
          "sha256": "e8b14aa21d2fbc58af9d2afbae3e4aa3e749c6394e56e1be5534f4c0787366ee",
          "sha1": "0741ee941043e868b85ff197460ff8d997fb8871",
          "md5": "427f14179d27915ff5ea2048f1680ab3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.7.0.jar",
          "url": "lib-jvm-0.7.0.jar",
          "size": 4310,
          "sha512": "53b24938203a8fa16788790e9a233f2f2d6b8a0877b9a3dd65c9f84ebd212e942fe28569780235df2c0366e3f857ca14de7c9b3ca971ca2ecdebcb4afa20204f",
          "sha256": "e8b14aa21d2fbc58af9d2afbae3e4aa3e749c6394e56e1be5534f4c0787366ee",
          "sha1": "0741ee941043e868b85ff197460ff8d997fb8871",
          "md5": "427f14179d27915ff5ea2048f1680ab3"
        }
      ]
    }
  ]
}
