{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.1/lib-coroutines-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosx64-0.6.1.klib",
          "size": 4207,
          "sha512": "98c745ded2f361b867edc522a6cea206194f3c5a256810c80fb5274e56d829544938447b7fd83f1fa7dc134429a5b61de7d421fd38e0b18edf6b73e8c58f7b21",
          "sha256": "99339620d64aeb98e9725c498e14cae3bbe8be0f68590a1c7b7c827d768b38f9",
          "sha1": "ea686967c5951a1e373484afe37ba5d4be0ad5f5",
          "md5": "3802637e037c9496b4443ac121568110"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosx64-0.6.1-metadata.jar",
          "url": "lib-coroutines-watchosx64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "ed214f7da34a2efc35bff8e258aa3becf25ca73862fdd34f32c15e4a289cba597996d22d2c2760e456c8067e4350fe51d308e6b2504c4f3a69a91bfb00b6123a",
          "sha256": "70436865f181e1fd4d87cb6f9c29ba2b802eb1b442f08e73036c4c10c98bd892",
          "sha1": "f71c379278589c2c50ec9704e3d0fa7e2ebc900a",
          "md5": "9eea0a10d78c18f96bab3764de585778"
        }
      ]
    }
  ]
}
