{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.8.1.klib",
          "size": 6803,
          "sha512": "4511f06a23267c9e239fde8fbb608c9e8decc7487dbb998a8316f948e4d7c7ebeaf5e79faf3fd90eaa19b97be0afeb512f89b23ba73d0f8bb35e41bed48e7378",
          "sha256": "90177852bc3d34da6f2f1796675add0834133036c34ceaf1a556cfd145caede8",
          "sha1": "a2350d83a100022d756c70a3a3d96409f0ec219f",
          "md5": "0bddf98d85427180ebdcb18cd58584ac"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.8.1-metadata.jar",
          "url": "lib-tvosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "5bf33ef941fc47a6c4ece635c23646c223c7262d97a2adbd51f95e5cd9cf2bbd1229798b8daafdf87eac9e126e61df5aed29fc0ad2e7afc6c2203ae380a6dc19",
          "sha256": "a072e09f9ddc46a0f559561298d40feecf268d3ca1c19eecaf871756ae1af113",
          "sha1": "c6e8bbcfd49606f8e41f9e0347ebd3c608f13d78",
          "md5": "0c83a84997967cf39a1e56e96035e531"
        }
      ]
    }
  ]
}
