{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.3.1.klib",
          "size": 14550,
          "sha512": "5a3edd29539c8b633c70104964abb42680e21bc22f1db5466665464564f01b8c495bdbf8b17121f0099ea6ee7ee810133e63f1fff70239a8ac8d5b8ce5454fad",
          "sha256": "778d3d0b529e45e0c57b777b549683ccfeaab7908f486dc3e28d79543d4b7178",
          "sha1": "022ca6468040c890363ae2975d1d25f33218f1db",
          "md5": "1668a4dce9681c68c24b78c0614ec6df"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.3.1-metadata.jar",
          "url": "lib-iosarm64-0.3.1-metadata.jar",
          "size": 3563,
          "sha512": "7e1aa49441d026b7b866becfc27fae81440bb2f3e90ee6476f13a9488a549d92541b611705b11f65d849add031618986f48f7a9d7d1f0d67df2ed51ad1f1c9f8",
          "sha256": "8a82d4c4e2c56d3e3111ccddc26afccd4a056c7512c2101d9552ef0bb968e585",
          "sha1": "6a7a237f5a9d7291fb5862999d95185c17fd260f",
          "md5": "02e6c1c07aa6a771883993ae8405d1a9"
        }
      ]
    }
  ]
}
