{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosx64-0.8.1.klib",
          "size": 4178,
          "sha512": "02eff66d166c6255bf14d8ff740ad77927d4b9e1a42b6aeeac781d91d4ea2e33a87d7a70303c7003792ccbabb021d1e74798dc48e4f3b8bbc1aa2166b5bc48ec",
          "sha256": "f3b55746d3164ba3044e9b7cc572dbae5288f21eaf2eb72922959c43b43a7f93",
          "sha1": "dfa0061e1d4d3fbe704c622f567d99cae7fe1b90",
          "md5": "237577f5296b36576ab256595ea26cd2"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosx64-0.8.1-metadata.jar",
          "url": "lib-coroutines-tvosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f684e14b6c5296633a8973ae0844b311204f4a0ec9ca7147d10815871c441db78e59fc9de876fac8bf9b08cb4c63fa7768fd2c8adef326498a78be613e442ce0",
          "sha256": "4a5b1208c596a32f133220756e797da7a12e31569e4ef871111c2753476b51e9",
          "sha1": "82f72c6731f7a52d057669b36596c7b1e5b46a64",
          "md5": "48a17ded0e34ce7199211ca2ba01d6ab"
        }
      ]
    }
  ]
}
