{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.4.2.jar",
          "url": "lib-jvm-0.4.2.jar",
          "size": 20631,
          "sha512": "d544833d7978ce8ecd0efb2457f08c224302b57ab50dfd1045f63fb9c143ce59dde355fafdb6baceec4c9088022f9aa044e9ae250cbbe3cb35fd7f526ac61177",
          "sha256": "aaa907606ab6412de7a4e39cd4b810aac5ef415db8ec83e57bca1ef32b305811",
          "sha1": "adff1b30f7ca11fc5d5d396b0f5cf44ae7a63a66",
          "md5": "f5998332fa0b20177fa3d3fec518f5d2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.4.2.jar",
          "url": "lib-jvm-0.4.2.jar",
          "size": 20631,
          "sha512": "d544833d7978ce8ecd0efb2457f08c224302b57ab50dfd1045f63fb9c143ce59dde355fafdb6baceec4c9088022f9aa044e9ae250cbbe3cb35fd7f526ac61177",
          "sha256": "aaa907606ab6412de7a4e39cd4b810aac5ef415db8ec83e57bca1ef32b305811",
          "sha1": "adff1b30f7ca11fc5d5d396b0f5cf44ae7a63a66",
          "md5": "f5998332fa0b20177fa3d3fec518f5d2"
        }
      ]
    }
  ]
}
