{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.1.1.jar",
          "url": "compiler-0.1.1.jar",
          "size": 206061,
          "sha512": "23f001740c14ebfc155b56764aa9f63726e06210c089c51ca4c220f9ef50e594edf066395ac125a23242dca00a7dc0d9a8b9939123be5ccc4c1202fbd415d6ee",
          "sha256": "7914d47bf909a09eeab08bbc0e534fc30ee0770c4b08071f7faa9dacc4bec12e",
          "sha1": "4b9e31510005502491489fc1291fee9f18bdaef9",
          "md5": "5d602e29d603d7d5aecd888223009ad3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.1.1.jar",
          "url": "compiler-0.1.1.jar",
          "size": 206061,
          "sha512": "23f001740c14ebfc155b56764aa9f63726e06210c089c51ca4c220f9ef50e594edf066395ac125a23242dca00a7dc0d9a8b9939123be5ccc4c1202fbd415d6ee",
          "sha256": "7914d47bf909a09eeab08bbc0e534fc30ee0770c4b08071f7faa9dacc4bec12e",
          "sha1": "4b9e31510005502491489fc1291fee9f18bdaef9",
          "md5": "5d602e29d603d7d5aecd888223009ad3"
        }
      ]
    }
  ]
}
