{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.0/lib-coroutines-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosarm32-0.4.0.klib",
          "size": 3984,
          "sha512": "addfabf6b28a3bc1503aef5123237c3e25fd6068da128f91eb65fc722a88dd9b73529631ff58782ae6742078a8c6525be826dddede11cee5785b49a959498ae6",
          "sha256": "55d7c749e8da066847509938eb1e409620895197d500e7d04a1ce4791a91dc51",
          "sha1": "775dbbf795b9d164999a828bc66500be0f23df9e",
          "md5": "7e33c5d74ff5487256db4b904f5f5a27"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosarm32-0.4.0-metadata.jar",
          "url": "lib-coroutines-watchosarm32-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "ed2488242680411bda9cb8725da735c86afcfb6b79397432ea025c2ce35e55b2393da42bee1293fceea7f3ff477da9c92c4c018ea042a661a08aab31b7463561",
          "sha256": "68fc4049952b6c81f6166466caec6aacd369e5d04ffebe066ccdbe5502969bcb",
          "sha1": "8136e56a08ae3532374ed9323c14df6e11f7be3e",
          "md5": "4d1964b3efdbd7b214c7dd68bbd0dc9a"
        }
      ]
    }
  ]
}
