{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.2/lib-coroutines-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosarm64-0.8.2.klib",
          "size": 4185,
          "sha512": "f02a4142fa2c25eb3f81e88bb55a0db917930b1ba3fdcfb01e662e1964b16e6be69ebe6f08fd1523958d576e51c853db120ef28bfeb661abfa636fbea50bec47",
          "sha256": "871d52d959eacbb171f6730db3f11d26c388e58b921559dfd49e5ee6d4c90532",
          "sha1": "c05caa693b464555ffdb370fab5206e8e14e2b74",
          "md5": "a4666da7de74d3fbbd5528005fabe0cd"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosarm64-0.8.2-metadata.jar",
          "url": "lib-coroutines-iosarm64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "0c2cdb5e477909efdb16ed1f8d693acde1427cb1a0865f000e06283cb419b56fce1eae45554f0db8989d91a67567d310096f98c8b888222346f2f8884eb09523",
          "sha256": "d121e510b079086ee466911db5f2f9105fe91a64679c0b018bfec749a4e85fa4",
          "sha1": "8fba10c9e7cc75ec19ff9cc6fa8011bd0cb5a8ad",
          "md5": "ad979e532597442ef4b0e8f310b327e8"
        }
      ]
    }
  ]
}
