{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.1.0.klib",
          "size": 14545,
          "sha512": "c069f367b16c180f64018f87ee0afbb28843195c311d4fea925fa4b45cbdffdc21edb509031ff42c08f89f9f04cbd7d3492fbf069e3edcb4c1d8ca9abc66e010",
          "sha256": "3ff37f75c618b6117dbaa4580cb6977d42254d17fc1a23ffcad800e176ad9bbf",
          "sha1": "95a775d52432f9ca9633c6c88214196040f07ec9",
          "md5": "264ccb76aca770c754e9e40eb82ff71b"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.1.0-metadata.jar",
          "url": "lib-tvosx64-0.1.0-metadata.jar",
          "size": 3608,
          "sha512": "36680adda65076ac6b0e7a98379d6019096ad9944347e7c50eb6891628d9a8ff8fce0e31f034d547893d2351eb8ecb44cbfbf8c483f1f800f5eb6db1c05f011c",
          "sha256": "32f3ee7ca0b83a4a609929254d33305e4ae53190f26adbacb30ab90f1dadc61a",
          "sha1": "601e50e4215e7f96ba03aa713d4d19d33da1eb42",
          "md5": "60c3f25559db07f7c3fca68fc3a632f5"
        }
      ]
    }
  ]
}
