{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.6.1.klib",
          "size": 8178,
          "sha512": "ee3ebca0d5be36f443e8213f79faf3d1f7df9b564ca1860e0a91d67600e90acad2afc568b7f2a2eb8919ad44de5b57642061bb66979c8a06028b098fbd105162",
          "sha256": "907d235337f2cd3b7ea23bbb5e75a9867605196992644643ead970a09bbb3152",
          "sha1": "2d98b0401dacd2fadbd4f915d33f61af37cc1b6c",
          "md5": "496d257e5ae2f0fbb1fedb2f59c18aea"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.6.1-metadata.jar",
          "url": "lib-watchosarm32-0.6.1-metadata.jar",
          "size": 3852,
          "sha512": "31d6abb5082f200798bfb7c6e27b41b00f503eab41083efb8b2f0266a451f6db37bcd4c57a81b92171176623c624df26301989fac5d5ba86b8b18abe463ced77",
          "sha256": "9e69a541e8397d61901ccc0142576befc2ae8fd0bc9741f9df6cf7a2498395ef",
          "sha1": "681f8d165d6689819fa6071ac124051fc420be2e",
          "md5": "0dcd47b51d829fe456691fc086656dff"
        }
      ]
    }
  ]
}
