{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.3-SNAPSHOT/lib-0.0.3-SNAPSHOT.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.0.3-SNAPSHOT.klib",
          "size": 14592,
          "sha512": "462a09c2dddc418f294f21ac0bacd51b8c28cafab7dd62e0f6b6f9940c95a55d590472eea14977db8fd05861c60a2988f587ee6ef76ba544678658267f2c07c7",
          "sha256": "6f23729419d93386b2f24ce1bef7b9b24e2b29c7f9fe68002e8070c31f30fe88",
          "sha1": "01e7f6f7a4bb42f0b2ec01e295afa717b7a6b624",
          "md5": "0139862e465c3e9a54157fb1d324cfd2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.0.3-SNAPSHOT-metadata.jar",
          "url": "lib-watchosarm64-0.0.3-SNAPSHOT-metadata.jar",
          "size": 3750,
          "sha512": "2c96e9b10cdd2ea3fa520d86f6458242c7bf4573f4550b97f0fd207b7bfb98557f018e1510f59e1b45f362561904bb6cd92495f1de716250b2c59120ebb7e678",
          "sha256": "fbcee2b4beca9230e12b48bed2cc711358d2540c231ce437b33b9715c585823b",
          "sha1": "29ee9474d1cb066740867a71530d7697ea0c628a",
          "md5": "7f8b56a9ad8672b3b1879040335d599f"
        }
      ]
    }
  ]
}
