{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.4.1.klib",
          "size": 14590,
          "sha512": "f8e497c23548871d2ce5dc43d79fc52dc1574b844f0b2292741f8566633e8ec1df6a380895a54d018bfd68f09912bd9962694502bee8dd7acc683e6fe19b89dc",
          "sha256": "067c1ed0cc91b863d590c413909f0fa2a646c7a034b3ad37c9c94a872d1c1245",
          "sha1": "9be4cfde80348cab984b699159f55185467643ba",
          "md5": "58a871f2f6e1eaeef3303ec7723f16e6"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.4.1-metadata.jar",
          "url": "lib-tvosarm64-0.4.1-metadata.jar",
          "size": 4263,
          "sha512": "6e4da36749a1113b26ec4980d31a3cf30c8319c4524f169b4bc39dcfcf227b24547482ba1bf3d845a4a95bb29547a5bcf58afb1f0a304382832fbe4a6d5d25c4",
          "sha256": "16d6b4de7be164dff1d085a72031ade2844199927796d626e3bd5adc8b54b17c",
          "sha1": "2098295cbae51aed92132068c6881cc143b95832",
          "md5": "74a5a6a3e9e74e711142b01ae1deec4e"
        }
      ]
    }
  ]
}
