{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.2/lib-coroutines-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosarm64-0.4.2.klib",
          "size": 7346,
          "sha512": "b4be635a49110f9ae9ed8d3cb35088240607f21876d706a698049f93b408db835cf932d4fa776c7394f58e7bc920d6d00033f6053fc8b61d8c5b8ee6b7474cd6",
          "sha256": "5eed6d7506f37a07f2fa86cdfa54024bf1f061c92155e36464308b68f7456d2f",
          "sha1": "fedf73051d19241ed464b2fd7c8cd0ca7a48bb97",
          "md5": "56a47df1af03988cc7d75cb4fe151d50"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosarm64-0.4.2-metadata.jar",
          "url": "lib-coroutines-tvosarm64-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "afa14ecb224036e72bf678054b377821af628c7e9d01863e4f43dcad27ac07e0f5dc3d3f6363a240acbb43e60d5c0ff4e75e30047d339871b63f78059d98abda",
          "sha256": "e83a57e3c614717279c6f3e5449b4d3ae80a21a736c12ef2245ae671ba693ddb",
          "sha1": "80d752056b2637c5328757d089aabc00a38b5319",
          "md5": "2b5a23245f52a15de4d298245dac54c0"
        }
      ]
    }
  ]
}
