{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.2/lib-coroutines-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosarm64-0.4.2.klib",
          "size": 7337,
          "sha512": "f714f1d099e0bb37f729e4e8a9e7a983c27c03c84914d57a51549181f4a3ffcd31ca017501276d2412c27bbf7a5d31d66d83dcfa44e215ba5aa5678321161fdd",
          "sha256": "772148ebbd464507420953348bedf70f1027ac3441e3088eeaf0b238fb24b50d",
          "sha1": "73c43f85c38ed59ce672116b85f63b17b1acfee3",
          "md5": "1a16c17ec82c01c912dd9f337fe09f01"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosarm64-0.4.2-metadata.jar",
          "url": "lib-coroutines-iosarm64-0.4.2-metadata.jar",
          "size": 261,
          "sha512": "afa14ecb224036e72bf678054b377821af628c7e9d01863e4f43dcad27ac07e0f5dc3d3f6363a240acbb43e60d5c0ff4e75e30047d339871b63f78059d98abda",
          "sha256": "e83a57e3c614717279c6f3e5449b4d3ae80a21a736c12ef2245ae671ba693ddb",
          "sha1": "80d752056b2637c5328757d089aabc00a38b5319",
          "md5": "2b5a23245f52a15de4d298245dac54c0"
        }
      ]
    }
  ]
}
