{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.1/lib-0.1.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.1.1.klib",
          "size": 14800,
          "sha512": "341e777726c3219d6345abf42569b7f3b8db8e5a003358895097eba54095af2e5b9014ad74b6ee574241b72c377e73af63e7cc0d8beec3f532e5870ed1929ffa",
          "sha256": "724df6c05eaed86a8889fe38d1816c33aa4be7059678a30d646d1a12a9c18ad0",
          "sha1": "8dc0dac12e5418c3e685a6e99a872d751c17511e",
          "md5": "64ace19f4e38fb2ed2df568cef7c20de"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.1.1-metadata.jar",
          "url": "lib-watchosarm64-0.1.1-metadata.jar",
          "size": 3750,
          "sha512": "74ec53edffc4777360b2d4515fa3bb2bbcb358a1bb6a93c57dbcc2b9cfff2ff9445f054f6c9934de723e1760d5805306a8fd9d6a81aa305c5b6d73a8f8ac47ce",
          "sha256": "a03795b50ceef20c3b8e3ac786def187ea506d9aa9ace5a44e470b42265dd01c",
          "sha1": "2c1f77791f72288900a5d71bc79eab628de19b23",
          "md5": "3072322effb8ece26cfeb39fb7f5f970"
        }
      ]
    }
  ]
}
