{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.1.2.klib",
          "size": 14772,
          "sha512": "a9ff7def0bdea3d7378d8bceb9869bb6eb5b16c731f248d9b761210f78393bfab1a0c953a94f786fc02f54becaa8b4daab04ffb10f357311d97c070aee2f571f",
          "sha256": "20ddfcc8e1f8feef7c69c370d07b623d06cc80cbe6365f69a22640deaed15b74",
          "sha1": "55515c6be91b0d70c7a35f8663857ef859c86493",
          "md5": "a27551e1c4a9e0b57452e6a34b21b617"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.1.2-metadata.jar",
          "url": "lib-tvosarm64-0.1.2-metadata.jar",
          "size": 3608,
          "sha512": "f17ccac4754d84888d921740a0e5302010a4732fec2d030120f53e90652eee2c3417c3e38aaca6bfe2e1f9441e93f1e5fa06811b0c7a1a472e16ad28cdd31a6d",
          "sha256": "a48a6d634f2c156392f568f12dd350ea6e48731c62888fc3fbe8987addacd274",
          "sha1": "8ea79d186809c1dc1aff1614ee69c408a9fdd52b",
          "md5": "ecf07eb82dc89a8d9a51f845903cc840"
        }
      ]
    }
  ]
}
