{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.3.1.klib",
          "size": 14592,
          "sha512": "d3eb1b417c99704ed03182b74a34b5acdd9b9ba77a9884b263de902106d206eda938418b30643be2db959fd3c39d0f7f36ba063449cb8564949aa3ac257673b7",
          "sha256": "ebae6224597506dbfc0463badf0a237f85c56300debcd3608ce856253ac8188f",
          "sha1": "57c5f755750c9c93ef757cf74cb7a601f55b1e70",
          "md5": "251feb663f69cf236262ce2c06d4a7ea"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.3.1-metadata.jar",
          "url": "lib-watchosarm64-0.3.1-metadata.jar",
          "size": 3752,
          "sha512": "c69963f493c25676a79c5107fc97c49885b37187c349b2e940cbbedcebdc45db03a14ce9e16302cf4b41b7d30a60c46f986b9d157d4748eb0f9e760669607d41",
          "sha256": "64ba41fcae8c0f68d4dd464aeb3312992c28c0c2687e7597c3bdc7da18084503",
          "sha1": "010cefc3df6af8ccfaf1a07c2712d3b11b886772",
          "md5": "30fd9e6b697e817998ff130a42046a31"
        }
      ]
    }
  ]
}
