{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.1/lib-coroutines-0.4.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.4.1.klib",
          "size": 7112,
          "sha512": "0b642bb4f6bcac9fdf80d00053e8d5137c24c9550665a8d4ea7b860537d4bd40b94197cbabe81dc06d21b83f03911d5baac8908407340a078f9042b7bef1947e",
          "sha256": "3ce0f13d659fddb5095b5c52f2764067f9d5c63b65ed42139a2f2150f857f14f",
          "sha1": "06060916d6b7fd609a6b8c76b36b77fc1dd888ec",
          "md5": "9cbf79548d46f4522081c0edb3ca54a6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.4.1-metadata.jar",
          "url": "lib-coroutines-iosx64-0.4.1-metadata.jar",
          "size": 261,
          "sha512": "0db0ecf3f225ff1fc7ff8a6210c52c41157a18e94781827b762f2bdffdf234d1e40adfac3dbbad3bc75151039c5860bbae7fee3f242e0186bd5e4407967c3561",
          "sha256": "1347440e167ed1e3e94ee534c6ff058742e4966ff2420fbf9f0eba92f838613e",
          "sha1": "deff3849e3cabab4e6c4c348aa9ca3ab214ad7ba",
          "md5": "ade011928aa55fa7cd866a5b8ef88246"
        }
      ]
    }
  ]
}
