{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.3.1.klib",
          "size": 14575,
          "sha512": "3d1ef78d22dcb16f7e3f68da024e5c71329605aa7bc9d2d16e4239595ea3c0e95af510df19bf1d9331426a770ab59d28fa3de2a3782d72cc69fe363f202312cf",
          "sha256": "62d23d4f39c6bc954df1cec0eaa5c8b9dfdab684083390193b310d2d920535c4",
          "sha1": "663c979f231b3b272a3f9766c0dd28db53e7930f",
          "md5": "9229558f888f37af1ca905389e07c36e"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.3.1-metadata.jar",
          "url": "lib-watchosx64-0.3.1-metadata.jar",
          "size": 3752,
          "sha512": "c69963f493c25676a79c5107fc97c49885b37187c349b2e940cbbedcebdc45db03a14ce9e16302cf4b41b7d30a60c46f986b9d157d4748eb0f9e760669607d41",
          "sha256": "64ba41fcae8c0f68d4dd464aeb3312992c28c0c2687e7597c3bdc7da18084503",
          "sha1": "010cefc3df6af8ccfaf1a07c2712d3b11b886772",
          "md5": "30fd9e6b697e817998ff130a42046a31"
        }
      ]
    }
  ]
}
