{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.3.1.klib",
          "size": 14573,
          "sha512": "a2fa619d959a550eadf3a69423e9cbbebd8c3f4156d617b6945ad82ad1cfa39cb9fa0b92cc53ac269e92c4dd6855ce3ff7938277607cd9b1337c1e8e4c3480a1",
          "sha256": "f65c8f251fede79f85153b30e89537b2e1dab87afc612e7dce8be9e43f525a06",
          "sha1": "f3f51aef94caa3e2574f6ba65723caab4d0f5fab",
          "md5": "c56245f15ea46561000970b9bb8dd5f6"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.3.1-metadata.jar",
          "url": "lib-watchosx64-0.3.1-metadata.jar",
          "size": 4123,
          "sha512": "9fa36edf3a6b9f838961323caa71e47ea3ab5b85a7c5b90472a89e5b01dc7e3f1c192cc81a0aea58e2c378408f8098c065868744243b1c7acdcbb57d4f719416",
          "sha256": "173336b196b26f3b4b0bcc034d7561dd7e9482b780937fa5d0de8dd9f917a8e7",
          "sha1": "6ea1faaf2d382b1ea1d9c54eae6e31fdd1006eec",
          "md5": "09e9729760a500b16b36093df2bf401d"
        }
      ]
    }
  ]
}
