{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.1.2.klib",
          "size": 14743,
          "sha512": "e315fc477b386c171c89c06a86c22f8c7629399f30821954f98b0c573422d841a37901d2ff9b566b1fba6fa1b9142c04796087219808fa873ffa288af3dee1cd",
          "sha256": "235c0b52ae575e85443497ebd7f9129f3e42bbc5fba233d91a3812d5574c6f02",
          "sha1": "cd12a2937b18b46fff5606e4fe9b421f57ac978a",
          "md5": "fbc82166415f518af7b97d71eb1d49d5"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.1.2-metadata.jar",
          "url": "lib-iosx64-0.1.2-metadata.jar",
          "size": 3562,
          "sha512": "26b57b2ef09602fb3124b15a185250aba596ec977bcb91e0fe67e54eaa931b3fcf67e019d6a31547306b88410cd01e21bc82bbc0740278e1ee1f0f48ba382e5b",
          "sha256": "08db9279878e424590bb8fdef5b6e47ed3f3d059cf1668d82c6c68265c523e49",
          "sha1": "64003abfe1706d7b4218bcd50507dfa383e1eb05",
          "md5": "b72987665495c459847b01498c74e04a"
        }
      ]
    }
  ]
}
