{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.7.0.jar",
          "url": "compiler-0.7.0.jar",
          "size": 225467,
          "sha512": "d215086159d554299a69e88412d93adfc4efb7526a6468c0d6f88ea9761bec9d0c162203a97a553837e1b1d1bd77aa5da08c2ad9872c8e5891674461548e6f5c",
          "sha256": "917bd801ae225a03e7a3f367bf3060a861f98c22bc00cc3f13b9a7f8003e48b6",
          "sha1": "e8052f073a2224bb47dc463fe086ca6baccd0142",
          "md5": "06d622925beaad9e0817a1cbe8813321"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.7.0.jar",
          "url": "compiler-0.7.0.jar",
          "size": 225467,
          "sha512": "d215086159d554299a69e88412d93adfc4efb7526a6468c0d6f88ea9761bec9d0c162203a97a553837e1b1d1bd77aa5da08c2ad9872c8e5891674461548e6f5c",
          "sha256": "917bd801ae225a03e7a3f367bf3060a861f98c22bc00cc3f13b9a7f8003e48b6",
          "sha1": "e8052f073a2224bb47dc463fe086ca6baccd0142",
          "md5": "06d622925beaad9e0817a1cbe8813321"
        }
      ]
    }
  ]
}
