{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.0/lib-coroutines-0.8.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchossimulatorarm64-0.8.0.klib",
          "size": 4307,
          "sha512": "353c4900b89403ab48e9eb8bb8de7bb7b0f14f79f96bd45db26c72cf3090c72e5b6f6093cc9e0bd28e9ed4a2dbef76b6694373f34300f31bba0cc0ce2825907b",
          "sha256": "c04a8dcf2e58549aa860fffb3ff1c1ceb75ce7ff6864b6a92587d7d91ee9dcec",
          "sha1": "545cb2073b6ff3f0a721ba8e3cc1be8fe159bd70",
          "md5": "8b38aa44c80e8a3f6953c5b8a93205b5"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchossimulatorarm64-0.8.0-metadata.jar",
          "url": "lib-coroutines-watchossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "54c79a60c9c75a29d50dc9fa0e2d042e073e7fc187e3cb7db364203c37093b76e8dacc31d98412cbc837d405b8e3a1660727bd8c68d9de34bcfb55cf00dd0f00",
          "sha256": "fa4f47abdac67119d9bc7b5f750044ce5eaf9bd6dc71afd3f1b0f83b09c57d7e",
          "sha1": "55f0ff90c21650e2a79549cb0ae3b841194d2d4f",
          "md5": "e5cf512542bd0620744c32d668d9de90"
        }
      ]
    }
  ]
}
