{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.2.0/lib-0.2.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.2.0.klib",
          "size": 14799,
          "sha512": "86a81066f5a41988f55f25d951957258427b31a9ff23b4d4724b91a49a626845666044c8b73aeb8adcadf4e7a75b887e5daf279ab0670ac66a2d18f80bd1bbe0",
          "sha256": "964560874fdea57aa88dcaec3a3500405d4c150fc79eee6acc68e83b4f5f28b1",
          "sha1": "6039f1eaa11fab6556111503425731840cf458fc",
          "md5": "d4c020fd153721d5cb3ef0762dc86755"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.2.0-metadata.jar",
          "url": "lib-watchosarm32-0.2.0-metadata.jar",
          "size": 4126,
          "sha512": "15f11656a4b08b6a3af3482acb6dff5cd3568f9163ad2dd397952528f6d459c2a99c39447fc4532d90b91a648fc36045d9d44a24f694a71e21a0a04c894bc387",
          "sha256": "d38ea90df5a8664c43ae1fa4f298ad15f05ad860be131668baff19e66bd29412",
          "sha1": "ace03bfc7a7bf49978b2df37df4738c0fba9aac6",
          "md5": "d30ff7224e8cb2472aa457bf75d9699f"
        }
      ]
    }
  ]
}
