{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.0/lib-coroutines-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosarm64-0.6.0.klib",
          "size": 4189,
          "sha512": "bdb824d26339026ba885a86333a84a335349cf2070849c2768f7297e7110ec6bb61bb179cc2649798254fab3e799918a6c74a1f69e9f5ed661d31ef6bb18fef4",
          "sha256": "bfd1dc62dcf08e673f6f14038c21165442792ff8fff75129ef5fbff40c1bed4d",
          "sha1": "7915f916c23dafc0b185b36d861fb6364eaca387",
          "md5": "f739840d8768a12727ca27e816626b33"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosarm64-0.6.0-metadata.jar",
          "url": "lib-coroutines-iosarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "1fcdc5d614e84d4d099b4126d85fd0ac17f330a7fc084bf82d2b4a15f0ee4b33b9acf4ab562a13abf2ddd4bb7e41d7165b850dd04b72ec7c4a716376a4f075c4",
          "sha256": "801bf6062b239a27faa3b81e4e7f43211b0e0aff6a01f67bc5e9d128a03d69bd",
          "sha1": "11b55cfe9a249cc5591684ac4711260391247e23",
          "md5": "91adb4b5b3f7a77cea3011561cfb3ba7"
        }
      ]
    }
  ]
}
