{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.4.0/lib-coroutines-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-tvosx64-0.4.0.klib",
          "size": 3940,
          "sha512": "4759326a642560fc33600cb968484aa5611e8361b1578f2aa60a840c9becdd020bd51569b2d3065a585159e3d340ac94c64958284a61269bcd610dad74be298d",
          "sha256": "2492635f5d79b00fff90640e0f9c1fd3f09dfd80ab86c382df807a3f590216fd",
          "sha1": "c136bb125f42f2bc57d35d29b14ab15de0c83d8a",
          "md5": "ee80a3bf77f56e3b6b88daae71cc2f23"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-tvosx64-0.4.0-metadata.jar",
          "url": "lib-coroutines-tvosx64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "a6a7443cb87decb574afe40ac7fdf5c5d1e0d93b81de78e095ed7dd3a4190a63b19dd6e2f8cc7dede8812d2974575d52ec6c69015b26d6e672f6b81366f88977",
          "sha256": "be6620ee1218a707e0c922f236ffe5f499b5c6f9b94e180e025f54be1708a71b",
          "sha1": "fbd19734ae53a6ce2de72dd5b1616b78ecddcc53",
          "md5": "29d18f2789929e342005a193aa4835e0"
        }
      ]
    }
  ]
}
