{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.7.0/lib-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.7.0.klib",
          "size": 8118,
          "sha512": "3bf388ca1f49db3cd29e4dfedfb1ce255f0c4bb612a7010f7411368bca48fdf6ed33c369da8f04d6d4a2b3663c2b9212edabe6bca31e44d1acc428de5bd509b7",
          "sha256": "b464cb0eb403b864291eb9299e3a992b756011b4248207b11420bcc0d7e8f111",
          "sha1": "54373e32c28f33e1d1cbf505027c968861167dee",
          "md5": "7a58ef86ea78afef2da3645dc7f64740"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.7.0-metadata.jar",
          "url": "lib-iosx64-0.7.0-metadata.jar",
          "size": 4269,
          "sha512": "66cb1928ef686e3c9ec22f696763a6a32310a153eea9ca5745ec3e73c8d4277f0253e1fc16e43eb2419e5af16380ff570ea66c6bb3d4c807695ea8067675b407",
          "sha256": "88ab9403f83357f463685a8bc63b34f7e14e7283540fdf1d711e9b9c153374e6",
          "sha1": "613b4eb02882e499680953b8f8adebcacba1f611",
          "md5": "e9232fcacc0cda708d85f390df18f8b5"
        }
      ]
    }
  ]
}
