{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.1.0.klib",
          "size": 14592,
          "sha512": "462a09c2dddc418f294f21ac0bacd51b8c28cafab7dd62e0f6b6f9940c95a55d590472eea14977db8fd05861c60a2988f587ee6ef76ba544678658267f2c07c7",
          "sha256": "6f23729419d93386b2f24ce1bef7b9b24e2b29c7f9fe68002e8070c31f30fe88",
          "sha1": "01e7f6f7a4bb42f0b2ec01e295afa717b7a6b624",
          "md5": "0139862e465c3e9a54157fb1d324cfd2"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.1.0-metadata.jar",
          "url": "lib-watchosarm64-0.1.0-metadata.jar",
          "size": 3750,
          "sha512": "387baf66eefd317d39f16103f82655279c0f9bc93609ef41f6b3707b85a97c8600cff7d0d9aba9485fd4b64a158fc92b6e0c3ede66be151fd51af803bc8bf45e",
          "sha256": "2ecfacd83ca825d10ab87a09bb9f2e48383587ef596303f8c30f9727d36ab7de",
          "sha1": "ac2a0a7ebe9fb9471d3e4572a04163b59fcc4e26",
          "md5": "165aa286205ddbb82dd03ffa51c58f19"
        }
      ]
    }
  ]
}
