{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.2.0/lib-0.2.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.2.0.klib",
          "size": 14781,
          "sha512": "cefe250d47d0f6a26ad41095aa497d4fa962090a5662a11dbc7c6fda19e5cce9349c3b0a03f379c3d7f61fc129c1a13a95fd379a2957ddfbf386d43ca9aeb224",
          "sha256": "efb1e2d504525d637eb04e4d12dad7440d2603619dc0bfdd9acb8b7e597574a4",
          "sha1": "4bd671bc00d33a169bde6c72b80581a5d2a27ad3",
          "md5": "3df052b0a0bed18f4f22f7b628a7d3a9"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.2.0-metadata.jar",
          "url": "lib-watchosx64-0.2.0-metadata.jar",
          "size": 4126,
          "sha512": "9cdea09d534f5d866f246a9d63af4665f346a1b8c85a6c296728bb3a849dfc8a7d24d3bda865f775ccd384aa811dcfa70cb703dcd8dcc98fa69f56b927195aeb",
          "sha256": "13a6f32890c25130e05db89402d4e59953709519d5dad502c07a8a9ddb5ca631",
          "sha1": "69b66b322d87499824abceeae42b12fe08c2c03e",
          "md5": "7958bdd16dd337c869b338a760a8cd15"
        }
      ]
    }
  ]
}
