{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.3.1.klib",
          "size": 14562,
          "sha512": "3e90a2ede3d743a5707332aaf723dae8e7e490c1474af9d797568142d7bf4a7c4583992670c4c6cf04b931d1888cac6ed8398da764e5a641fa57668358778038",
          "sha256": "78bb61864f3e2e7c58a5732767c39e38816620b74008446bcb2642c7b38402dd",
          "sha1": "84617922bd54087fe4e3b78075b604ef7ff4cba2",
          "md5": "861c2f574685b94573bcd68673c3319a"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.3.1-metadata.jar",
          "url": "lib-tvosarm64-0.3.1-metadata.jar",
          "size": 3609,
          "sha512": "8daa3525ba78ec4d7eb965adce2365cc7ca12883d13fab22172b697a90e5455dced9be60351bf17eea9dc2e03e4aa78f502f8ad8dbf5cf209c8ce953700fc698",
          "sha256": "22589c0daa67efcb7d0bc0e869f0f6a8f28e7fb1810fed126eb979812831aff1",
          "sha1": "ece8e6a55c10b9c37ea0bb4ea63a14476f9b3f34",
          "md5": "5d4a08402fa55a74ce920971e450c0a5"
        }
      ]
    }
  ]
}
