{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.3.1.klib",
          "size": 14560,
          "sha512": "cc9d4bcc42ce5fcc3fc60c9080fffd59aa68b13a99c1db92150430d4ade2cbc9613211f48cc68331f316893d309a51a281d29df368a6253349aa9172b1f814b5",
          "sha256": "a0d01bfad0ddbd7bd34ee585e5627762a62ff109ea54ee943fd056d51030da88",
          "sha1": "c03aa8441997468322b196b9b24b03933cb9ff8f",
          "md5": "b4e9d82ad3a4466872414ecd70c26933"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.3.1-metadata.jar",
          "url": "lib-tvosarm64-0.3.1-metadata.jar",
          "size": 4259,
          "sha512": "cea94976d3f46325b29a8c2c5913a85d8b564bdd722cc339fbe383a6e034e606ac212a2b6c7e4a072d55af33e475996c3bb5ed48753ad58fdf5ac578aa482f2f",
          "sha256": "4cf8ab004e5e1d6415c5f394bd937c36dffca3207d95ca94ec37ac4510b43483",
          "sha1": "259f45b1abee6199bfc50f8343dd88f8b918c3a1",
          "md5": "53058aaf975ea9555d5d5ee9a7dbf333"
        }
      ]
    }
  ]
}
