{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-0.2.0-all.jar",
          "url": "lib-0.2.0-all.jar",
          "size": 4595,
          "sha512": "b50f0e7f48f956fdb60eb9c7b9aa226fd42042c67f6b3d7ae3e90c202175fdf46b38a8c50d8a6eec45bf96e23d35b160c89b5bd38dc5d607e3c3e2d954a349bc",
          "sha256": "877be4d84b07a5eb1291cff8b258705376e6e323bda5e806e798a91705f0086e",
          "sha1": "95856903c7da962ca261ebc6da4c6b6980a801bd",
          "md5": "056e4015558d0b55f83e7baae2813f5d"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.2.0.jar",
          "url": "lib-0.2.0.jar",
          "size": 8811,
          "sha512": "1dd05c465e94b355522886a3d8c98983f17074de9e4419e7d7ec13ffc9e1216bd5e35a6b36f6d80c1fb5b5d9115c8120ada66674e5cee0f7e893e5630a7980dc",
          "sha256": "8d497ade558b2bedf501acca3086f547eb7a66d08f77b6f398064913546f428b",
          "sha1": "2270fee6d3c93d98dae6930211fed9ef2f70dc3e",
          "md5": "9c7ad209640ed583fa2b38ff2adfc6ec"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.2.0/lib-iosarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.2.0/lib-iosarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.2.0/lib-iossimulatorarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.2.0/lib-iossimulatorarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.2.0/lib-iosx64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosx64/0.2.0/lib-iosx64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.2.0/lib-js-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.2.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-js/0.2.0/lib-js-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-js",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.2.0/lib-jvm-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/0.2.0/lib-jvm-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-jvm",
        "version": "0.2.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.2.0/lib-tvosarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosarm64/0.2.0/lib-tvosarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.2.0/lib-tvosx64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-tvosx64/0.2.0/lib-tvosx64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-tvosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.2.0/lib-watchosarm32-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.2.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm32/0.2.0/lib-watchosarm32-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm32",
        "version": "0.2.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.2.0/lib-watchosarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosarm64/0.2.0/lib-watchosarm64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.2.0/lib-watchosx64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-watchosx64/0.2.0/lib-watchosx64-0.2.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-watchosx64",
        "version": "0.2.0"
      }
    }
  ]
}
