{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.0/lib-0.6.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm64-0.6.0.klib",
          "size": 8177,
          "sha512": "4e9fd78232c15e3c1c147cfe8c64981541768088c4700b201e6e6aafc81b9b0acdbf1cf31be8181efe3eda8a1bb0472e625dc50a4ba4d8953dea1e087c3842c1",
          "sha256": "8476988280281efb58e47942f0227f99441a3334691faed00a577e24392b1f96",
          "sha1": "1110ccbebe204514be6102131d4ce8e580dee290",
          "md5": "2d71ff709075ebeb7b44b669ce081cbd"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm64-0.6.0-metadata.jar",
          "url": "lib-watchosarm64-0.6.0-metadata.jar",
          "size": 3845,
          "sha512": "f87ce71bf5d7945f43dc4e020229dfa3bfaba3b20e395b27e83232162ede27bdb6214ea7051fb759f476f67deb052a8a0c1056c69472cbab9d82f0e1cba29bd6",
          "sha256": "9bbfda374680575cc8d259049d927059fa53e2c8d767298ce0982224c3d27db5",
          "sha1": "add7c616f28bbbebe5031a5c861e724dcc8491e7",
          "md5": "cc431b2d9484e37d872870c894b96ed1"
        }
      ]
    }
  ]
}
