{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.0/lib-0.5.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosarm64-0.5.0.klib",
          "size": 8464,
          "sha512": "ca8250bc735a3f0ae1c2b01ff2905ea2466ec5f6a111f8906238f1193a299f6b70914777bca195e80448c6cbbdfc05063097e169ba6ea66cd01fa757137818b5",
          "sha256": "3ac4e7d9aa905c6e384bac2c6dd0a02f91d484d984570ba25375cc6b1be458fd",
          "sha1": "33bd0619cf2d914313a060c509d2b7f374250280",
          "md5": "d720c2a1568b57c0041a357b685caed6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.5.0-metadata.jar",
          "url": "lib-iosarm64-0.5.0-metadata.jar",
          "size": 4225,
          "sha512": "2c81c9e16c89f2bc56a06681c6c01ff01f561ca809119a5c8b7b8a2ef1659f0d5164f6c3069495955b70cd50bdfed06fb3bdb6eef4401b9aef8ef3125acd4d7f",
          "sha256": "b5bdae128d9f6af1558bf72aaec15304b806d8055e7bcdad463c34a6223ba9ec",
          "sha1": "40ad3ba043471b60f64389118608d66e3dddec95",
          "md5": "3d05a51dacafe202c1d5c412ce09fb58"
        }
      ]
    }
  ]
}
