{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosarm32-0.1.2.klib",
          "size": 14801,
          "sha512": "34e523ed69f8f821e83e27d4f7b7a9b034f16193951b681a42dd28f6a2c06ce978928e3c12d29f4a1e49190b3da300af49d2be13fbbcfc3d1ce00b297d24d941",
          "sha256": "3e54ffa9c3a320f5f6f1403d219da7bd9a8548875ad92d4ff179a128d876b32e",
          "sha1": "fa3ef81ef11557bba4b7faf2ccac2204616c237e",
          "md5": "7d199b636fd565035600a94513ddabc9"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosarm32-0.1.2-metadata.jar",
          "url": "lib-watchosarm32-0.1.2-metadata.jar",
          "size": 3750,
          "sha512": "ac9e06b91e7cfdc371de598fce755ff27510fbdb83370a6868356ba002b86cae526e0f972639b1effe2abf1f13a15b84d59277e4761ec0ffbee081ddb82c4410",
          "sha256": "a80120c700e0d1b7f7ba5fd0ecb308171d62d7085c11a31e2de14a58068b9b5a",
          "sha1": "c254d7be389c106fd027a4616b348b131206006f",
          "md5": "c7a93b46d3adc43e3f893cca7867cb04"
        }
      ]
    }
  ]
}
