{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.2.klib",
          "url": "lib-js-0.1.2.klib",
          "size": 14176,
          "sha512": "8c26df6272eb3c65f560570c2878c12ddc1450b73b0364e435a0e12b1958e252b10c616ca5df6ac24565ec67fd694b8098d9514e7ababceac8436d3a708d43e2",
          "sha256": "a4d4561f2179b45082540aabc9c3400db5dddfcf851adaf4176f986674a6e6a6",
          "sha1": "e771c02c6c400b478ececa1fa3dc7dc6f68dc752",
          "md5": "fbe42dbfa211f59a0b60728bff700f27"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.2.klib",
          "url": "lib-js-0.1.2.klib",
          "size": 14176,
          "sha512": "8c26df6272eb3c65f560570c2878c12ddc1450b73b0364e435a0e12b1958e252b10c616ca5df6ac24565ec67fd694b8098d9514e7ababceac8436d3a708d43e2",
          "sha256": "a4d4561f2179b45082540aabc9c3400db5dddfcf851adaf4176f986674a6e6a6",
          "sha1": "e771c02c6c400b478ececa1fa3dc7dc6f68dc752",
          "md5": "fbe42dbfa211f59a0b60728bff700f27"
        }
      ]
    }
  ]
}
