{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.6.1/lib-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosarm64-0.6.1.klib",
          "size": 8148,
          "sha512": "4f84bc70acce73ad80b192bd28de0532a0cba7548317dbcfa34377137ce050b057864084310874a879f49eb45073d3f8194cfe6e07cbcf3855c650640623e2ef",
          "sha256": "bc0637721fea1eec0aff6d76567acaacc0d111b9decc06d27d617b14394c1580",
          "sha1": "f01508697b304f854f086939a0fc0f72afc801f0",
          "md5": "cd4aa99b6368f3839dc384b64826642b"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-0.6.1-metadata.jar",
          "url": "lib-tvosarm64-0.6.1-metadata.jar",
          "size": 3976,
          "sha512": "cc4d50ec6111efc25917716fe7128ee4b4648a62cbb5fd94560ea72acc36deeb2d715e54ce7be1c18eda85bf9a559dcc5c0f801b4e8929d5f90e2697e13f5efc",
          "sha256": "c4c5519ab915de98363babf0096252b1d78aacdd2d9f560ff4e4a8e9e9e24ead",
          "sha1": "da7d9f17ec099e39ad7ebacb601b1ce1c3219ae0",
          "md5": "f76eb505e40d81c30f8dd244e81ab516"
        }
      ]
    }
  ]
}
