{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.2/lib-0.1.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.1.2.jar",
          "url": "lib-jvm-0.1.2.jar",
          "size": 20607,
          "sha512": "a7e7e943b0f0872446f3e7cd36e138371a0ccf67781af00ec1fa7977f3f70db0b75065bc047b44f1920e4ff7f08842aaaefca844cc067d0a958fd51db0249af6",
          "sha256": "589bfd072fd92e4ed9f3a85cca895a5798f26b16f08a1cb148632e8deff15e2c",
          "sha1": "f529af2a25b5b9aa261b2aad5c79124ecefb64a4",
          "md5": "72f1241c6012e56a0ee5616dd9c84330"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.1.2.jar",
          "url": "lib-jvm-0.1.2.jar",
          "size": 20607,
          "sha512": "a7e7e943b0f0872446f3e7cd36e138371a0ccf67781af00ec1fa7977f3f70db0b75065bc047b44f1920e4ff7f08842aaaefca844cc067d0a958fd51db0249af6",
          "sha256": "589bfd072fd92e4ed9f3a85cca895a5798f26b16f08a1cb148632e8deff15e2c",
          "sha1": "f529af2a25b5b9aa261b2aad5c79124ecefb64a4",
          "md5": "72f1241c6012e56a0ee5616dd9c84330"
        }
      ]
    }
  ]
}
