{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.1.0.jar",
          "url": "lib-jvm-0.1.0.jar",
          "size": 20607,
          "sha512": "509efce9dc05e8201d7144d93ed887b827d51acd46331c858e68759f68a0f3a6e3ab422ee638cb3574c14191dc4b13996a499e330701519e6f9ecbcf78f5e5a9",
          "sha256": "b7429791e54b45a07b6cd162bd948eb7d4b2038bf6a67f20450f76d0778faf9c",
          "sha1": "384a178c595b4b01253d429a9c643cf8ea4b0d66",
          "md5": "79aa2ccfb6849b97ed08860962c0cb44"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.1.0.jar",
          "url": "lib-jvm-0.1.0.jar",
          "size": 20607,
          "sha512": "509efce9dc05e8201d7144d93ed887b827d51acd46331c858e68759f68a0f3a6e3ab422ee638cb3574c14191dc4b13996a499e330701519e6f9ecbcf78f5e5a9",
          "sha256": "b7429791e54b45a07b6cd162bd948eb7d4b2038bf6a67f20450f76d0778faf9c",
          "sha1": "384a178c595b4b01253d429a9c643cf8ea4b0d66",
          "md5": "79aa2ccfb6849b97ed08860962c0cb44"
        }
      ]
    }
  ]
}
