{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.2.jar",
          "url": "compiler-0.4.2.jar",
          "size": 222387,
          "sha512": "08a00597a6122496c2fb09987828888089e03e369e0986fc40957dae70cac0b5df8bad952bd187ce8a215856551df4c3670c028d670a2d7740f3bce94577d05a",
          "sha256": "2aa428d2260c1435c9e1fcc89a8a1e94a26399938d3479654f58d9900ed70263",
          "sha1": "fa541f76bf46965f5f25fa03030fd1b76e71f48b",
          "md5": "0d235f85f581c2b9e9c51d196e6891e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.4.2.jar",
          "url": "compiler-0.4.2.jar",
          "size": 222387,
          "sha512": "08a00597a6122496c2fb09987828888089e03e369e0986fc40957dae70cac0b5df8bad952bd187ce8a215856551df4c3670c028d670a2d7740f3bce94577d05a",
          "sha256": "2aa428d2260c1435c9e1fcc89a8a1e94a26399938d3479654f58d9900ed70263",
          "sha1": "fa541f76bf46965f5f25fa03030fd1b76e71f48b",
          "md5": "0d235f85f581c2b9e9c51d196e6891e8"
        }
      ]
    }
  ]
}
