{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.0/lib-0.4.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.4.0.klib",
          "size": 14562,
          "sha512": "0e824e9e197ce727949871cc7ed217e761a215ade8ffe5bd3a1626bbf14ddf1a6e01c16efb724e4e2df5532239ba3a937003f4218d7e17aa36c110316495a8de",
          "sha256": "885dc8a4ad7b5f00c8ffb6b2892262270ea7404995a8bf2315c598a10dd9ba6d",
          "sha1": "e4306e51a40a547e664e0c9754d2694d233f55b5",
          "md5": "35461a55f49d4304e002e2c946c30a27"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.4.0-metadata.jar",
          "url": "lib-iosx64-0.4.0-metadata.jar",
          "size": 4558,
          "sha512": "35245b6bb98e6312e4425e5a8d31afcb13b26bc7c54e123801848f425595edd91c3316ad61f1f392697cb59f25f46d69fab2986be2cd2880e8f0f30fc896e1fb",
          "sha256": "cc343e4e7a7e4d220d880c59511a19069d4025c353568921500e5526311b30a9",
          "sha1": "e0665bb149c00db2ef2c399bcfcc727700389e49",
          "md5": "812d21e477d2984b24a01106fc918d2a"
        }
      ]
    }
  ]
}
