{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.8.1.klib",
          "size": 6829,
          "sha512": "2d958e71292a37f2363c4250fcf0ac82f954f28f3dd62dd530e08b222de9a0817b9a1fc5fd454f69a0734f3a014b990609b2455abef1412538f3303b84061abc",
          "sha256": "17823d3a65dbecc60156f0f56254be01ddda5885f7d7d4b6227fe7b6d1babc7c",
          "sha1": "7746fc9018adae0cc98a71a1be6d0128ea8c31b2",
          "md5": "f8de3a970e6fb68ce58502793c132c65"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.8.1-metadata.jar",
          "url": "lib-watchosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "1b1a931f5359752216160f7f20855dfb44529ea0fa3f8859d17f1f6c1360cac5ef4633da85108469884ef3a6661e73d12713404320668d166a65618d88869fcd",
          "sha256": "17054fcc38a962adc236ddfe7d011ed2f954a3a9079983f52b69bbbb54388f4b",
          "sha1": "26b0936bd2cd15dba601980e13aa21ca1bbb87d2",
          "md5": "6335f5ecd9a3e04c2c51deffbb217945"
        }
      ]
    }
  ]
}
