{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.1/lib-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.8.1.klib",
          "size": 6836,
          "sha512": "0d12350c93ed436429fee61524ad3e29e4beff6e442949f9e2dffffe5f54149026ebfbe60f3ba1f2220e9750dbf8982950b6968b51de3617f9e7305d2ea4f05c",
          "sha256": "22a2c03691bd778ae6e206a50e1bf30136254f45cea3ba39559c2f6c4118964a",
          "sha1": "88eb4619dfdb2f973a373f9eb05be6aacc7666c9",
          "md5": "f97eb81812993d0393ba70536b0b8983"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.8.1-metadata.jar",
          "url": "lib-watchosx64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "423e49116a634e8aaa867de91a06912e4b61d154c5f037e1f2916a11424770e76a2c43a6b4b1c73e7b16a4e146a19bbdf2bbbed3dafb42d7284e01fbf7b3a3c8",
          "sha256": "0132130f8ade1e3a99b62e8574d23b7d183e8fc37953495599049cbe388bbd90",
          "sha1": "0665cd0f2292f88f5d74b52c01b7c98bf900b433",
          "md5": "aeccf2fbd22fb8aaab8e971985631e63"
        }
      ]
    }
  ]
}
