{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.8.2/lib-0.8.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.8.2.klib",
          "size": 6829,
          "sha512": "2d958e71292a37f2363c4250fcf0ac82f954f28f3dd62dd530e08b222de9a0817b9a1fc5fd454f69a0734f3a014b990609b2455abef1412538f3303b84061abc",
          "sha256": "17823d3a65dbecc60156f0f56254be01ddda5885f7d7d4b6227fe7b6d1babc7c",
          "sha1": "7746fc9018adae0cc98a71a1be6d0128ea8c31b2",
          "md5": "f8de3a970e6fb68ce58502793c132c65"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.8.2-metadata.jar",
          "url": "lib-watchosx64-0.8.2-metadata.jar",
          "size": 261,
          "sha512": "3a28b92265d527534ecb036c63bb9a48b23bdfc1c3ca6a0a0759699fda2f61c901d834825244b1dafc3b6a4762d79aa33f9291975340c7e43b3e8d227ac4b469",
          "sha256": "9393abc114691f4c8326872f1b05059d96ccf15c8aba9fc119af3bac7fcc683e",
          "sha1": "bc26ab3ea45826b9b0a336fd0268bee42cda25f4",
          "md5": "8c77a8c5cd6e28697c328b417e1dc226"
        }
      ]
    }
  ]
}
