{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.0/lib-0.5.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.5.0.klib",
          "url": "lib-js-0.5.0.klib",
          "size": 7456,
          "sha512": "36b5d45fd18f996fbccf0ae4972df39cefc2485606f293bd2365d2891a5c128d6ef7e3f80883acafde1ba45d497ae1616ad27958273f96c991df1b2624e13813",
          "sha256": "0435546a932afeac7ec7a32b1bb5fc7fa00c2cc48450552c23a05211ee5753da",
          "sha1": "d83a89dd45df8e6e2878a20a36bdd32564c5c526",
          "md5": "fb14d3736d7713466c6ab3b67f593481"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.5.0.klib",
          "url": "lib-js-0.5.0.klib",
          "size": 7456,
          "sha512": "36b5d45fd18f996fbccf0ae4972df39cefc2485606f293bd2365d2891a5c128d6ef7e3f80883acafde1ba45d497ae1616ad27958273f96c991df1b2624e13813",
          "sha256": "0435546a932afeac7ec7a32b1bb5fc7fa00c2cc48450552c23a05211ee5753da",
          "sha1": "d83a89dd45df8e6e2878a20a36bdd32564c5c526",
          "md5": "fb14d3736d7713466c6ab3b67f593481"
        }
      ]
    }
  ]
}
