{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.3.1.klib",
          "size": 14534,
          "sha512": "8b9eeb4229594ee13b489e8a1c8486822f11d4f7b2af1be5f1c2a7eb0993597953bc3cdd4fea8080f0355970ce856ea5335c9d3fb57b3a9bcaa592095cfaea42",
          "sha256": "1dd71c2c2c7c556a7bf27ccb4d0b0d71cd42964fde669c67839e80fc25852589",
          "sha1": "9fe68a1cc71cf75c51a870c51998e6935f7c3af1",
          "md5": "f450758bd7569d35c89a522c181f127c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.3.1-metadata.jar",
          "url": "lib-iosx64-0.3.1-metadata.jar",
          "size": 3563,
          "sha512": "7e1aa49441d026b7b866becfc27fae81440bb2f3e90ee6476f13a9488a549d92541b611705b11f65d849add031618986f48f7a9d7d1f0d67df2ed51ad1f1c9f8",
          "sha256": "8a82d4c4e2c56d3e3111ccddc26afccd4a056c7512c2101d9552ef0bb968e585",
          "sha1": "6a7a237f5a9d7291fb5862999d95185c17fd260f",
          "md5": "02e6c1c07aa6a771883993ae8405d1a9"
        }
      ]
    }
  ]
}
