{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.1/lib-0.1.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.1.klib",
          "url": "lib-js-0.1.1.klib",
          "size": 14176,
          "sha512": "9ab5c9ab6baf9135d71c68bcfc70caeccbfdbfdc39596b99d4327cc58ea59299bd088a3e4806a236df9a5d50ab44bd419a4e0bbe7b239d3396a13940cb475867",
          "sha256": "0528f685336f054cd2d80e1cb092d0def679abc3962564c8f743bfaae5ac85f5",
          "sha1": "3bebb4b47f739198fdea44b1b555a9134be2f60e",
          "md5": "71e3080cfa9365c49914aa5dfc9508cb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.1.1.klib",
          "url": "lib-js-0.1.1.klib",
          "size": 14176,
          "sha512": "9ab5c9ab6baf9135d71c68bcfc70caeccbfdbfdc39596b99d4327cc58ea59299bd088a3e4806a236df9a5d50ab44bd419a4e0bbe7b239d3396a13940cb475867",
          "sha256": "0528f685336f054cd2d80e1cb092d0def679abc3962564c8f743bfaae5ac85f5",
          "sha1": "3bebb4b47f739198fdea44b1b555a9134be2f60e",
          "md5": "71e3080cfa9365c49914aa5dfc9508cb"
        }
      ]
    }
  ]
}
