{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iossimulatorarm64-0.8.1.klib",
          "size": 4274,
          "sha512": "1f80054a75b5278729a536433473ee2477e8069bcdcc79a2efb6f162ef0c2d7d39c60cf1151cda61ab15fbb4be622ffc03e778355d74aa4b74990922b373b89d",
          "sha256": "e3912c78a1cb8a755ee0dd5576d12aafdf20855736dbde70e2c42a428d69eefd",
          "sha1": "0ad9157a3562e8b27f32c44a93d1611b5e171373",
          "md5": "43d088bb625cec1365c435b4ec3dee93"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-iossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f44f047ac2b0af45f3e563c3999981bb640f1fab60e27aa7bedcc83838f8f2591ec1ba7910e03c404ad142f69f5cf58e514b8b604e939e9a73ec2077ee1edbc5",
          "sha256": "f02ac83f65030fa6d824138b5fa0a3408abeb877e15c071f30b0efe519c14b2a",
          "sha1": "2124f1e45a2fa5df7c87922ccc27081a8b2d5066",
          "md5": "a950aecc98c6498d4ea9621c059c77ed"
        }
      ]
    }
  ]
}
