{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.8.1/lib-coroutines-0.8.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iossimulatorarm64-0.8.1.klib",
          "size": 4271,
          "sha512": "ae4bb9e815251c0fbf0926c072f969f7f03d37683fa810b84efac6dccc34a3aa2046f96a9b50ce4ebe120ff112478bb5111045311632e0fbd060e759d06ac58c",
          "sha256": "147b6e60bf5f74daaf7253018a97b40cecd159c7732edf9bbb323c10bab17fbb",
          "sha1": "710dfb1ebf9da728531a6e54a3f13dad19dc4317",
          "md5": "485efe694d77cc8be575311eacab00f9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iossimulatorarm64-0.8.1-metadata.jar",
          "url": "lib-coroutines-iossimulatorarm64-0.8.1-metadata.jar",
          "size": 261,
          "sha512": "f378ff9d5d4d7f77843d55e7da7fae43a5ef6804243b2c922b25ac723ff394375eda89f090172846132881a65b623041389e4a4692d9e59dccbbc240ba47e516",
          "sha256": "0d8f0d120ad5779d25746965c15220d63a2344c233231dd95a8a093ee17ee44c",
          "sha1": "95ff7760faa3013dd4378c521c2024ca862c6ca8",
          "md5": "85b5f72e38280dc527a61b609dc1dfd9"
        }
      ]
    }
  ]
}
