{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.1.0.klib",
          "size": 14534,
          "sha512": "cef36e98739b02b2dee7ee8bb92e91beb666a57ea579e2f17865c1f4d7f51bd4486f5cc7a915f1086c351431d4fdfde2d64f0b248a31dc5db5e8bd614b9da426",
          "sha256": "491d733b7f581751873fc6ae3f9e5960a7dd558d68d4142ebfd5d75ebbe8328f",
          "sha1": "0513624b2ca16978468cabc2a3470c2d0012b4a9",
          "md5": "ddb0b42f9fc159566e22d010f54e4e06"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.1.0-metadata.jar",
          "url": "lib-iosx64-0.1.0-metadata.jar",
          "size": 3562,
          "sha512": "a77db4e04e783750a9fa6f4c0272caac9d36413308d8591971b29bcefcaed6101f6b013c7f180bf5e595e1e3fe546ede23fea538160e1338119b88c526a3a21f",
          "sha256": "758b1ee56317bd99af9f925772db536c97d49152137d4f375a0cbfa65219c17e",
          "sha1": "3c7f5931925b14bd668493f4e68801322c49bfb1",
          "md5": "cb6e1373eb9bc4fbcd97cf066394e51d"
        }
      ]
    }
  ]
}
