{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iosx64-0.1.0.klib",
          "size": 14534,
          "sha512": "cef36e98739b02b2dee7ee8bb92e91beb666a57ea579e2f17865c1f4d7f51bd4486f5cc7a915f1086c351431d4fdfde2d64f0b248a31dc5db5e8bd614b9da426",
          "sha256": "491d733b7f581751873fc6ae3f9e5960a7dd558d68d4142ebfd5d75ebbe8328f",
          "sha1": "0513624b2ca16978468cabc2a3470c2d0012b4a9",
          "md5": "ddb0b42f9fc159566e22d010f54e4e06"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-0.1.0-metadata.jar",
          "url": "lib-iosx64-0.1.0-metadata.jar",
          "size": 3562,
          "sha512": "d73b2c406a73cff0525282321b0a42678810518e2d772611749f701499e9460b0ed85ee862be8a3e8ef36cc5fbc510b48717b84d15890e152706d68cf5d87d20",
          "sha256": "4ea74d172e4c6782e39a95fd8ca112c73f263d52abc6c6c2a67dff67835e4484",
          "sha1": "1cc3441779f9c608846c045caa3077ef2da8e712",
          "md5": "448b7b02883e68416b219114b7e265ef"
        }
      ]
    }
  ]
}
