{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.1.0.klib",
          "size": 14655,
          "sha512": "fa61bcd923f48883d19d4cd5223b702b4c307bc4793dc536416f3b093b8c64a49dcef4f1c5394844e4eef8045a624c422df73ee920d49ba1a41ec4c7d0425f3a",
          "sha256": "d0301af9ccfb355c445e733f85149294cc2080a60a0aae5a51d32a7fed87a721",
          "sha1": "3ea104630db1c80afc8fa2a9e5f5a1211f05197f",
          "md5": "c4460bc776663329881d49c1314f89d5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "7c2d97c7d4db2ad177d9876902d4fd941ca294a475364e03c76695ea94c3888b535a4a005fb4fdd345dd3c61d7871d179bb13a861488cc6273564d11965291a9",
          "sha256": "6c9031b6200aced10d5baf7e6b56bc097b5d2960a6d6079581e8deb1a3a2b3ab",
          "sha1": "bfd5fd0129643d7a25700fa9726e195515474b8b",
          "md5": "f2732e06261e8d957b71427808ddb730"
        }
      ]
    }
  ]
}
