{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.1/lib-0.4.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.1.klib",
          "url": "lib-js-0.4.1.klib",
          "size": 14203,
          "sha512": "4c10ad5bc72094f7810f36e262418bcee6a5c0b46a8988b2fbf014c3ff4c2769629456c0158674883596ecaccd32374e36358a38e8281667d527ca882b959d05",
          "sha256": "3a3ec3f25803c55309cdea00b0e625242a8eb4424cc91818601611fb43c4e132",
          "sha1": "ea620cc84fd97268d76a9bd1efbdb90f83ad1cf7",
          "md5": "653f4a731bc406de7aad10cca5894f97"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-js-0.4.1.klib",
          "url": "lib-js-0.4.1.klib",
          "size": 14203,
          "sha512": "4c10ad5bc72094f7810f36e262418bcee6a5c0b46a8988b2fbf014c3ff4c2769629456c0158674883596ecaccd32374e36358a38e8281667d527ca882b959d05",
          "sha256": "3a3ec3f25803c55309cdea00b0e625242a8eb4424cc91818601611fb43c4e132",
          "sha1": "ea620cc84fd97268d76a9bd1efbdb90f83ad1cf7",
          "md5": "653f4a731bc406de7aad10cca5894f97"
        }
      ]
    }
  ]
}
