{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-metadata-0.6.0.jar",
          "url": "lib-coroutines-0.6.0.jar",
          "size": 2209,
          "sha512": "84be481c4195f8118fa82ef6fdf7d8991e9867696048deb609a98240693366b396f784091451e4d41fb9c3216cfc70d888ce5b576f569e6f1a0f409b9daec508",
          "sha256": "53842103b360123c6ecbf26f1f7401a050a17fd1a100b359386a05ef15be0b75",
          "sha1": "b8aa0763c5947251bb692cb60e57e504aa2030fe",
          "md5": "67d35f4a1eae9b1f48d4cc0781e0b568"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosarm64/0.6.0/lib-coroutines-iosarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosarm64/0.6.0/lib-coroutines-iosarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iossimulatorarm64/0.6.0/lib-coroutines-iossimulatorarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iossimulatorarm64/0.6.0/lib-coroutines-iossimulatorarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iossimulatorarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosx64/0.6.0/lib-coroutines-iosx64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-iosx64/0.6.0/lib-coroutines-iosx64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-iosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-coroutines-js/0.6.0/lib-coroutines-js-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lib-coroutines-js/0.6.0/lib-coroutines-js-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-js",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-coroutines-jvm/0.6.0/lib-coroutines-jvm-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-coroutines-jvm/0.6.0/lib-coroutines-jvm-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-jvm",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosarm64/0.6.0/lib-coroutines-tvosarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosarm64/0.6.0/lib-coroutines-tvosarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosx64/0.6.0/lib-coroutines-tvosx64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-tvosx64/0.6.0/lib-coroutines-tvosx64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-tvosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm32/0.6.0/lib-coroutines-watchosarm32-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm32/0.6.0/lib-coroutines-watchosarm32-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm32",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm64/0.6.0/lib-coroutines-watchosarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosarm64/0.6.0/lib-coroutines-watchosarm64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosarm64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosx64/0.6.0/lib-coroutines-watchosx64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosx64",
        "version": "0.6.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-coroutines-watchosx64/0.6.0/lib-coroutines-watchosx64-0.6.0.module",
        "group": "deezer.kustomexport",
        "module": "lib-coroutines-watchosx64",
        "version": "0.6.0"
      }
    }
  ]
}
