{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-watchosx64-0.1.0.klib",
          "size": 14575,
          "sha512": "938c9528ddcfe26b1929a13d2fc2bb8a427067295fee548f02de7bb9c2a8604c76c1c4bad2b6b415e2559c0e655f89fd0119578bc9403c34360fe4917911a1f9",
          "sha256": "05a15c67f3082aa7d1e59a8ccd3a3767277fb21474b82727c3a52194aec4f36e",
          "sha1": "943ea37fa807dcf2e7fea6451cd3d18d328d2718",
          "md5": "1aeda276c2f71a2259f2a5958bbd9d6f"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx64-0.1.0-metadata.jar",
          "url": "lib-watchosx64-0.1.0-metadata.jar",
          "size": 3750,
          "sha512": "387baf66eefd317d39f16103f82655279c0f9bc93609ef41f6b3707b85a97c8600cff7d0d9aba9485fd4b64a158fc92b6e0c3ede66be151fd51af803bc8bf45e",
          "sha256": "2ecfacd83ca825d10ab87a09bb9f2e48383587ef596303f8c30f9727d36ab7de",
          "sha1": "ac2a0a7ebe9fb9471d3e4572a04163b59fcc4e26",
          "md5": "165aa286205ddbb82dd03ffa51c58f19"
        }
      ]
    }
  ]
}
