{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.7.0/lib-0.7.0.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.7.0.klib",
          "size": 8237,
          "sha512": "04f6b39b92da74c20e691dc6c2acdd1d621b7abcfbf7181ff7719d4925c1b57fbb15d7629cf665239e7bcb3bbe98863071fa75a30a91d10b448acc20b76aceb8",
          "sha256": "5a4c93adc4c7c4de2c0e63f95143c7bd7e96b13d7c2f4144be400ebc31bd426a",
          "sha1": "c2e0e987b6f4cde7773b88bc0cd3b3077f777bcf",
          "md5": "5bb400935d2f677eadcea3c7c635a2b1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "b026d39927e2667292a980b999fb2ebe7934fbd872ee09bb2853497a4e73bc4c2fc4ca80a2667a21c7d947a30a7df434b1eadcec1bda19dcdcd8a8f364dd9db8",
          "sha256": "6e89f757c00d8b98704af769c7d7f38571dcab00009dcc6495b4be5e8d0b2fab",
          "sha1": "62a12b6219998a12b18a8ebbff69ac1f52a0d8b4",
          "md5": "909f0763de4b047550a1b3d5a7af6b26"
        }
      ]
    }
  ]
}
