{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.0.3-SNAPSHOT/lib-0.0.3-SNAPSHOT.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.0.3-SNAPSHOT.klib",
          "size": 14655,
          "sha512": "fa61bcd923f48883d19d4cd5223b702b4c307bc4793dc536416f3b093b8c64a49dcef4f1c5394844e4eef8045a624c422df73ee920d49ba1a41ec4c7d0425f3a",
          "sha256": "d0301af9ccfb355c445e733f85149294cc2080a60a0aae5a51d32a7fed87a721",
          "sha1": "3ea104630db1c80afc8fa2a9e5f5a1211f05197f",
          "md5": "c4460bc776663329881d49c1314f89d5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.0.3-SNAPSHOT-metadata.jar",
          "url": "lib-iossimulatorarm64-0.0.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a2f86c58c6a361a14c98fe37ce10c03339b8ea31eb21a544e2cc113227a5b6e2f19d86adbc69784571e47cb5b22b4fa6fb6a0de7499d972bf2e6d23d870dac2a",
          "sha256": "96331d11dce98e90ddf63d6b67c19914916ac2795644384601c88febdaa4386f",
          "sha1": "fd9623b90595bc7e89838f4c3d67daed8be4cd30",
          "md5": "eeba5fe8c60c02a492fb791477127bd4"
        }
      ]
    }
  ]
}
