{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.6.0.jar",
          "url": "compiler-0.6.0.jar",
          "size": 226216,
          "sha512": "5a5e7ed8b7c0a90eb4ebf9880e11de72cd333eb9f6ef2a2b983f0bfc2deb7e55e4d1c116460d05f0bb05b58bd14e66d24abebaf927deb9422b00ac56209ce1e1",
          "sha256": "9dc74874f058257bf5f42db191977aab00331858e4518cdbb95af7445d23a09a",
          "sha1": "57782655342a404ee2e267e828cb39a34dd9290e",
          "md5": "03d62705e1d4ce7a2c52abe383ca80cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib-coroutines",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.21-1.0.5"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.21-1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.6.0.jar",
          "url": "compiler-0.6.0.jar",
          "size": 226216,
          "sha512": "5a5e7ed8b7c0a90eb4ebf9880e11de72cd333eb9f6ef2a2b983f0bfc2deb7e55e4d1c116460d05f0bb05b58bd14e66d24abebaf927deb9422b00ac56209ce1e1",
          "sha256": "9dc74874f058257bf5f42db191977aab00331858e4518cdbb95af7445d23a09a",
          "sha1": "57782655342a404ee2e267e828cb39a34dd9290e",
          "md5": "03d62705e1d4ce7a2c52abe383ca80cc"
        }
      ]
    }
  ]
}
