{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.3.1/lib-coroutines-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-watchosx64-0.3.1.klib",
          "size": 3966,
          "sha512": "76884378a4115133c9796dec734770fa5f948166ed49996226f6fd07bc7af5af371e712caec321adafd7206fcebf2a603039f963d1d5264d2eb21d7bdcbcea38",
          "sha256": "6622b3230b06b3aabf92889a145b40e838b905f09b55d15dd46d35e442c708a6",
          "sha1": "de707c52ba4ce21a53a746e6385af20fbda0e0ec",
          "md5": "ef856a1b16c130b1e1ab5ea4497e475f"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-watchosx64-0.3.1-metadata.jar",
          "url": "lib-coroutines-watchosx64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "d859250890e7e1465fa8ced98453359213584064f23d1564c1df922f3e8b42fe5c03f7dacf28e952906b7e381a04b59129c183ad283ef4100994ffef77c0f1cc",
          "sha256": "64e6ccd1550b2e3dc90453d461116446e272c2886b65dcf9653b57710f15ccd4",
          "sha1": "6b39e2361e74d2e9d385c28fea6bb64aece0813e",
          "md5": "55dfdcc7d4ac83af6857a0064eef1fbd"
        }
      ]
    }
  ]
}
