{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.4.2/lib-0.4.2.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.4.2.klib",
          "size": 14783,
          "sha512": "bf1408592873b6b5fcef315d0f99dd435da4dae8c374c2e972e57e8e31eb0ed9394624d26aaf1f8a4297c53b88091330027a4ea0258adc6df3d2401bcabe0051",
          "sha256": "7069b0a96edda4bd5079da6c23324862246bac8c9242af854ab2c23a52c0d81b",
          "sha1": "49d79623e5295b00826048b774e39165283e1d8e",
          "md5": "81dfaf0a28ffddda00dac3b07757b396"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.4.2-metadata.jar",
          "url": "lib-tvosx64-0.4.2-metadata.jar",
          "size": 4268,
          "sha512": "394d3e53a3dffc27bb1aad4f820617c83faf3e74f9ea68e62a3ce5d81ee019b4e4b2bb0b99b1fcb72bbcdcae15eb9edec8bcd2eb91ef89b5497a85cf158349e6",
          "sha256": "ebb0e0678b793b6cd601c5f113d5cbd634d228975855f4824c2b1626debee76b",
          "sha1": "dc07be47e20abd3cad36bb8099db1397d1c0629b",
          "md5": "3a862bff0f4424dad9069087d0afd4b9"
        }
      ]
    }
  ]
}
