{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-iossimulatorarm64-0.3.1.klib",
          "size": 14655,
          "sha512": "4ed7083e6501e4523bb7e24d9d51b086272fd2dea66d805ca55d4db8b028461f3294cbc0776bba8d3ae8fbb4a969a6397ea9384d93a8ab3e30e9af2718be9099",
          "sha256": "3a3566ed6f016667e793e507af7269fd2f76f77b856e337ddd700ed7f5493071",
          "sha1": "053ce4cb96d5935a283e36d7e230e33bad119733",
          "md5": "c581092a9b9556fb4b4abc02ac9c8797"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.3.1-metadata.jar",
          "url": "lib-iossimulatorarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "6beddc26a308de843edb97d9135ff1d1c51c8eee617832afc0b2cfb0aaed5a1fb0f2ff09d69fd9583943ad0a4e37e503872d6e731d546f6665b61247e752eba1",
          "sha256": "85c002f5ab1aa496a257d8d10fdfbec8cdfdab549771d040a33425cdd6a8832a",
          "sha1": "6001ccf15a1ea17008a601c8790c22b22159ccf4",
          "md5": "294eb9db897b8b919887e0eae9dcaf58"
        }
      ]
    }
  ]
}
