name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Verify PR - unit tests & code style
        run: |
          echo Good

      # Commented plugin for now as it only supports ubuntu
      #- name: Publish Unit Test Results
      #  uses: EnricoMi/publish-unit-test-result-action@v1
      #  if: always()
      #  with:
      #    files: compiler/build/test-results/**/*.xml

      - name: Run integration tests
        id: integration-test
        run: |
          cd samples
          body=$(ls -al)
          body="${body//$\n/%0A}"
          echo "::set-output name=body::$body"
          echo ${{ github.event.number }}
          echo ${{ github.event.pull_request.number }}
          cd -

      - uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.pull_request.number }}  # remove comments from the current PR

      - name: Post integartion test result
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.integration-test.outputs.body }}