{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.1.jar",
          "url": "lib-jvm-0.3.1.jar",
          "size": 20607,
          "sha512": "2350b9010e0c829cdd2085f23deee80b9a4cdac8c00980da630e5395466bb9482b12dd102b22992c1effa55177b7b5e183d10c80288dd89ce461b7d8c13d6294",
          "sha256": "5fec42aa26656ac371e5fddde977d318997f40fc1d9affafb2c060446c9a97de",
          "sha1": "2e490da6557265dfebc944f5ad648dc7766ce76b",
          "md5": "62c2e685511c6ebb7aa4daae6cd4277c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-jvm-0.3.1.jar",
          "url": "lib-jvm-0.3.1.jar",
          "size": 20607,
          "sha512": "2350b9010e0c829cdd2085f23deee80b9a4cdac8c00980da630e5395466bb9482b12dd102b22992c1effa55177b7b5e183d10c80288dd89ce461b7d8c13d6294",
          "sha256": "5fec42aa26656ac371e5fddde977d318997f40fc1d9affafb2c060446c9a97de",
          "sha1": "2e490da6557265dfebc944f5ad648dc7766ce76b",
          "md5": "62c2e685511c6ebb7aa4daae6cd4277c"
        }
      ]
    }
  ]
}
