{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.3.1.klib",
          "size": 14543,
          "sha512": "5dd38b50efd1d1a2d6672186f5f59d3636b0c7e18a85b69c96be44546ee9f5311d9fb50d88365560c3b19d16ca8f7f7d1aa14f662b45d126b6a10606e88ae3f2",
          "sha256": "a4ea5dca1dc7eb16e8f9813847a85c1529d3df909e0f1bcf9d225ed760be5998",
          "sha1": "a180467d049eb927793912b30413a41dde43198a",
          "md5": "136f8f78fdff61b9be2d555e1047be30"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.3.1-metadata.jar",
          "url": "lib-tvosx64-0.3.1-metadata.jar",
          "size": 4259,
          "sha512": "c4ef2806b302f09559d16bcc6c4bce0af4f878f6c8c397e7af2cdc4b042237433563fb1cea9afb8d65e7d9272cb26ba8139d69d5597b73cfa03f85b2e0fb13a8",
          "sha256": "f13c18162c506729ed971c57fcdb999358f9dcf223927130d3cd1822f0406531",
          "sha1": "e7b3802fa47bceef0f461e7f31fe71b238de1e4b",
          "md5": "82509038000909edc2e347d3dbfac805"
        }
      ]
    }
  ]
}
