{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.1/lib-0.3.1.module",
    "group": "deezer.kustomexport",
    "module": "lib",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-tvosx64-0.3.1.klib",
          "size": 14545,
          "sha512": "0e838768bc87a9649d50d593861eaf9f1d9c290878fcafcde34e92863407e9517e516c761fb4ab2adb48d0b73520b71bf6268b2149bea4bfce9f0e6ff33a27f7",
          "sha256": "2da350f05aa55c0deab8bf158ad5ef9bb77617917788e3a260eafb66bdc195ac",
          "sha1": "b3f1d6082b6a4e1cf9b081bd641a97bad74afae5",
          "md5": "6e499dbe6a66c774609f7721b6e21bc2"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosx64-0.3.1-metadata.jar",
          "url": "lib-tvosx64-0.3.1-metadata.jar",
          "size": 3609,
          "sha512": "8daa3525ba78ec4d7eb965adce2365cc7ca12883d13fab22172b697a90e5455dced9be60351bf17eea9dc2e03e4aa78f502f8ad8dbf5cf209c8ce953700fc698",
          "sha256": "22589c0daa67efcb7d0bc0e869f0f6a8f28e7fb1810fed126eb979812831aff1",
          "sha1": "ece8e6a55c10b9c37ea0bb4ea63a14476f9b3f34",
          "md5": "5d4a08402fa55a74ce920971e450c0a5"
        }
      ]
    }
  ]
}
