{
  "formatVersion": "1.1",
  "component": {
    "group": "deezer.kustomexport",
    "module": "compiler",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.0.3-SNAPSHOT.jar",
          "url": "compiler-0.0.3-SNAPSHOT.jar",
          "size": 205340,
          "sha512": "b2ee38c526e4e92f4210bbbd5ef91d4645e8bbf37bde080b7b3b3e0c0216ff5076cc34d7f1ba9f49cd6f2953cd67b06ff7ce4b8e3b89ba9bc8bfc8fd571233fc",
          "sha256": "b3eb4b4495ba6e6c21a2a06f627b404e98305f5da838fbeb29cecb7a5f8887c1",
          "sha1": "61b479ab6b79c76cef33b417c27d1d92aca6d022",
          "md5": "9be0170c7a4961ffe1393d2b41fa189d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.0.3-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-reflect"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.0-1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-0.0.3-SNAPSHOT.jar",
          "url": "compiler-0.0.3-SNAPSHOT.jar",
          "size": 205340,
          "sha512": "b2ee38c526e4e92f4210bbbd5ef91d4645e8bbf37bde080b7b3b3e0c0216ff5076cc34d7f1ba9f49cd6f2953cd67b06ff7ce4b8e3b89ba9bc8bfc8fd571233fc",
          "sha256": "b3eb4b4495ba6e6c21a2a06f627b404e98305f5da838fbeb29cecb7a5f8887c1",
          "sha1": "61b479ab6b79c76cef33b417c27d1d92aca6d022",
          "md5": "9be0170c7a4961ffe1393d2b41fa189d"
        }
      ]
    }
  ]
}
