{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib-coroutines/0.6.1/lib-coroutines-0.6.1.module",
    "group": "deezer.kustomexport",
    "module": "lib-coroutines",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines.klib",
          "url": "lib-coroutines-iosx64-0.6.1.klib",
          "size": 4172,
          "sha512": "5d94a19ab9b3f4a9b333ea96f2b1dfcaab08cf75762f9bebbd1248c387da534dd912eaef8b3b2d622ea46d4c7d1c1b3aa7bd7952a8dff148d39e2b3ac132114d",
          "sha256": "4c9de12497314b095dbdcdc38ca8ea8ba4863eecc6b540a4a6742ee2692664b6",
          "sha1": "8e375d9408b10847f43c5acca78faf317649a2a0",
          "md5": "389d9c40be9251d2209a1ee310dd03dc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "deezer.kustomexport",
          "module": "lib",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-coroutines-iosx64-0.6.1-metadata.jar",
          "url": "lib-coroutines-iosx64-0.6.1-metadata.jar",
          "size": 261,
          "sha512": "f442120ee7fb620e2b7c8c452a48eb33c3b373378be1110f4e0a357b90a9f9421292d8d89819b0a561801c695b78e021e49d084861ed48c83a70aeb30fe1ef15",
          "sha256": "b55ab54aae66da0b9237b916904a633c499862af9826b520eb0c1c353faf4ce6",
          "sha1": "a0b5d0545f19299391f85cdf4b24a6b5b8c5021f",
          "md5": "13b9451c9aab7e2b128d9ace3304b07e"
        }
      ]
    }
  ]
}
